### ISSUE TITLE
Footer Logo Link Destination Field Not Working With External Links

### ISSUE THREAD

**Issue by pfini** [az-digital/az_quickstart#1006]
### Problem
Public facing website QS2 theme white screens when the theme's Footer Logo Link Destination field is filled with anything but `<front>`.
### Describe Bug
I am changing the logos in the header and footer.  We use the footer logo as the parent item for the website unit so the footer logo will be different than the header.  

The different footer logo works fine until I need to change the **Footer Logo Link Destination** to something _other than_ `<front>`.  When I do that and save and then go back to the public facing site, I get a white screen with this message: 

**The website encountered an unexpected error. Please try again later.**  

The site's PHP error comes up with this:  

> Symfony\Component\Routing\Exception\RouteNotFoundException: Route “https://medicine.arizona.edu/” does not exist. in Drupal\Core\Routing\RouteProvider->getRouteByName() (line 206 of /code/web/core/lib/Drupal/Core/Routing/RouteProvider.php).  

### To Reproduce

1. In the site, go to Appearance then Arizona Barrio (theme) settings
2. Scroll down to the Footer Logo Image tab and click to open
3. in the Footer logo link destination field enter external URL
4. Save changes
5. click Back To Site
6. See Error:  **The website encountered an unexpected error. Please try again later.**  

## Proposed resolution
I don't have a workaround for this at this time.

### Expected behavior

Entering an external URL in the Footer Logo Link Destination field should work as expected as footer logos may represent the parent unit to the website and need to redirect to other than `<front>`

### Desktop :
 - Mac OS 10.14.6
 - Browser: Chrome
 - Version Version 92.0.4515.159 (Official Build) (x86_64)

## Additional context
The website I am currently working on:
[https://dev-urology-qs2.pantheonsite.io/](https://dev-urology-qs2.pantheonsite.io/)

**Comment by smayden** [comment]
This was addressed in #1101 and included in release 2.0.8
