### ISSUE TITLE
Default admin configuration

### ISSUE THREAD

**Issue by barrettbaffert** [az-digital/az_quickstart#101]
**Do not disclose security vulnerabilities here, please email us instead: 
az-digital-security@list.arizona.edu**

## User Story(s)

As a ‹role›, I'd like to ‹feature short description› [ , in order to ‹value it adds›. ]

As a ‹role›, I'd like to ‹feature short description› [ , in order to ‹value it adds›. ]

…

## Conditions of satisfaction
- [ ] Should ‹testable condition that should be satisfied›
- [ ] Should ‹testable condition that should be satisfied›
- [ ] …

**Comment by camikazegreen** [comment]
Most of the need for this issue was resolved by our work on roles and permissions.
