### ISSUE TITLE
Styling on footer links broken

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#1012]
Looks like the changes in this PR https://github.com/az-digital/az_quickstart/pull/940 has broken something with the styling of the links/headers in the footer. 

## Problem/Motivation
Some problem with templates not being used (probably due to naming issues). 

### Describe the bug
![image](https://user-images.githubusercontent.com/10873398/131415954-f691e6d9-b9f2-44cd-8755-49cb7213d683.png)

Looks like issue with the template names
Making a separate issue for the white background on footer links (introduced by the work we did on putting nav over text on media)

**Comment by trackleft** [comment]
With both templates
```
themes/custom/az_barrio/templates/navigation/menu--sub_footer.html.twig -> themes/custom/az_barrio/templates/navigation/menu--sub-footer.html.twig
```
https://github.com/az-digital/az_quickstart/pull/706/files#diff-b38289e1ed832bb6f64de029543b15ed855bf2860ede9e5be6268048a15e2738
then
```
themes/custom/az_barrio/templates/navigation/menu--sub_footer_topics.html.twig ->
themes/custom/az_barrio/templates/navigation/menu--sub-footer-topics.html.twig
```
https://github.com/az-digital/az_quickstart/pull/706/files#diff-3a118625057c1545d7bd9c572865666053745638fa6dd3aa46a09bfa8742a15b


But also in the yml file I think we should get rid of the underscores.
https://github.com/az-digital/az_quickstart/pull/706/files#diff-a58e2952890c5baef8911a1fe643cffd26e724e2995501626f9ef40aa6547facR24

https://github.com/az-digital/az_quickstart/pull/706/files#diff-0c2aaf0be1dae07638108754830823ad612cffda8e1e9f8fea7a9157ddd34d1bR24

https://github.com/az-digital/az_quickstart/pull/706/files#diff-502c5f4b099319b62184ad5633eb517b4eec5fb3e376e3ceee84086b53e74b22R24

Etc

**Comment by trackleft** [comment]
Then for the block templates. We can just use these names
```
<!-- FILE NAME SUGGESTIONS:
   x menu--sub-footer.html.twig
   * menu--az-footer-information-for.html.twig
   * menu.html.twig
-->```
