### ISSUE TITLE
ESlint failing in ProboCI, Lando, ddev due to dependency problems

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#1016]
## Problem/Motivation
Our ProboCI builds are all currently failing the ESlint step.

### Describe the bug
```
$ npm install --no-progress --global eslint-config-drupal-bundle
...

npm WARN eslint-plugin-prettier@4.0.0 requires a peer of eslint@>=7.28.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-prettier@4.0.0 requires a peer of prettier@>=2.0.0 but none is installed. You must install peer dependencies yourself.
...

$ eslint --color .
Error while loading rule 'prettier/prettier': context.getPhysicalFilename is not a function
TypeError: Error while loading rule 'prettier/prettier': context.getPhysicalFilename is not a function
    at Object.create (/usr/local/lib/node_modules/eslint-config-drupal-bundle/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:123:40)
    at createRuleListeners (/usr/local/lib/node_modules/eslint-config-drupal-bundle/node_modules/eslint/lib/linter.js:682:21)
    at /usr/local/lib/node_modules/eslint-config-drupal-bundle/node_modules/eslint/lib/linter.js:841:31
    at Array.forEach (<anonymous>)
    at runRules (/usr/local/lib/node_modules/eslint-config-drupal-bundle/node_modules/eslint/lib/linter.js:781:34)
    at Linter._verifyWithoutProcessors (/usr/local/lib/node_modules/eslint-config-drupal-bundle/node_modules/eslint/lib/linter.js:1003:33)
    at /usr/local/lib/node_modules/eslint-config-drupal-bundle/node_modules/eslint/lib/linter.js:1046:35
    at Array.map (<anonymous>)
    at Linter.verify (/usr/local/lib/node_modules/eslint-config-drupal-bundle/node_modules/eslint/lib/linter.js:1045:42)
    at Linter.verifyAndFix (/usr/local/lib/node_modules/eslint-config-drupal-bundle/node_modules/eslint/lib/linter.js:1138:29)
$ exit
```

## Proposed resolution

- Investigate whether we still want to use the `eslint-config-drupal-bundle` which is currently being globally installed for the ProboCI ESlint step or if it would be better to use the tooling provided by our `package.json` file

### Expected behavior

ESlint should be run against all (custom) Javascript files provided by AZ Quickstart using the same ESlint rules as Drupal core.

## Additional context
UADIGITAL-2168
[Original commit adding step to ProboCI config](https://github.com/az-digital/az_quickstart/commit/17ead9bb69613d622a298c17912efb00f788cd4b)

**Comment by trackleft** [comment]
FYI when I run ` npm install --global eslint-config-drupal-bundle` I don't see the peer dependency issue.

**Comment by joeparsons** [comment]
> FYI when I run ` npm install --global eslint-config-drupal-bundle` I don't see the peer dependency issue.

Same node version? (12.18.1)

**Comment by trackleft** [comment]
OK, when I use 12.18.1 I do see the error.

➜  ~ nvm use 12.18.1
Now using node v12.18.1 (npm v6.14.5)
➜  ~ npm install --global eslint-config-drupal-bundle

/Users/chrisgreen/.nvm/versions/node/v12.18.1/bin/prettier -> /Users/chrisgreen/.nvm/versions/node/v12.18.1/lib/node_modules/eslint-config-drupal-bundle/node_modules/prettier/bin-prettier.js
/Users/chrisgreen/.nvm/versions/node/v12.18.1/bin/eslint -> /Users/chrisgreen/.nvm/versions/node/v12.18.1/lib/node_modules/eslint-config-drupal-bundle/node_modules/eslint/bin/eslint.js

> core-js-pure@3.13.1 postinstall /Users/chrisgreen/.nvm/versions/node/v12.18.1/lib/node_modules/eslint-config-drupal-bundle/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN eslint-plugin-prettier@4.0.0 requires a peer of eslint@>=7.28.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-prettier@4.0.0 requires a peer of prettier@>=2.0.0 but none is installed. You must install peer dependencies yourself.

+ eslint-config-drupal-bundle@1.0.3
added 253 packages from 246 contributors in 5.713s


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New major version of npm available! 6.14.12 → 7.15.0      │
   │   Changelog: https://github.com/npm/cli/releases/tag/v7.15.0   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

**Comment by joeparsons** [comment]
Looks like we should be using a newer version per this security advisory (as of yesterday), anyway:
https://nodejs.org/en/blog/vulnerability/aug-2021-security-releases2/

**Comment by trackleft** [comment]
When I update npm to latest, it works
npm upgraded to: v7.21.1

**Comment by joeparsons** [comment]
> When I update npm to latest, it works
> npm upgraded to: v7.21.1

Wouldn't that require switching to a non LTS release of node/npm?  Not sure we want to do that...

**Comment by joeparsons** [comment]
I think the problem stems from this pacakge declaring `eslint-plugin-prettier` as a bundle dependency but not defining a version constraint for it:
https://github.com/shaundrong/eslint-config-drupal-bundle/blob/master/package.json

**Comment by trackleft** [comment]
I think in that package.json, they can add 
```
{
  "engines": {
    "npm": "~6.14.15"
  }
}
```
