### ISSUE TITLE
Add global footer content

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#1049]
## Motivation
Some websites use/modify the global footer on their sites in QS1. We want to have similar functionality in QS2

### Is your feature request related to a problem? Please describe.
We've already built the menu and block structures for most of the global footer (styling and social media still in progress). But we need a way to get the default content for the global footer in place as an option in QS2

## Proposed Resolution

We discussed in the 9/24 Friday meeting using starter content that would live inside a Footer module. This would allow sites to turn on the global footer content without having to use other starter/demo content.

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Anonymous user - able to see the content when it is enabled
- Authenticated user - able to see the content when it is enabled
- Content editor - able to see the content when it is enabled
- Content administrator - able to edit the menus where this content lives
- Administrator - able to enable the footer content

### Footer - Main
- (https://talent.arizona.edu) Employment
- (https://cirt.arizona.edu) Emergency Information
- (https://www.arizona.edu/title-ix) Title IX / Non-Discrimination
- (https://www.arizona.edu/campus-safety) Campus Safety
- (https://cirt.arizona.edu/ualert) UAlert
- (https://www.arizona.edu/copyright) Copyright
- (https://www.arizona.edu/campus-accessibility) Campus Accessibility
- (https://www.arizona.edu/contact-us) Contact Us
- (https://www.arizona.edu/website-feedback) Feedback

### Footer - Information For
- (https://www.arizona.edu/admissions) Future Students
- (https://www.arizona.edu/students) Current Students
- (https://www.arizona.edu/faculty-staff) Faculty & Staff
- (https://www.arizona.edu/alumni-donors) Alumni & Donors
- (https://www.arizona.edu/parents-visitors) Parents & Visitors
- (https://corporate.arizona.edu) Corporations & Businesses

### Footer - Topics
- (https://www.arizona.edu/about) About the University
- (https://www.arizona.edu/academics) Academics
- (https://www.arizona.edu/arts-museums) Arts & Museum
- (https://www.arizona.edu/athletics-recreation) Athletics & Recreation
- (https://www.arizona.edu/colleges-schools) Colleges, Schools, Departments
- (https://diversity.arizona.edu) Diversity
- (https://www.environment.arizona.edu) Environment & Sustainability
- (https://global.arizona.edu) Global Engagement
- (https://www.arizona.edu/health-sciences) Health & Medical
- (https://www.arizona.edu/libraries) Libraries
- (https://uaforyou.arizona.edu) Outreach & Extension
- (https://research.arizona.edu) Research & Innovation
- (https://www.arizona.edu/purpose-mission-values) Purpose, Mission & Values

### Footer - Resources
- (https://directory.arizona.edu/index) A-Z Index
- (https://www.arizona.edu/calendars-events) Calendars
- (https://map.arizona.edu) Campus Map
- (https://news.arizona.edu) News
- (https://directory.arizona.edu/phonebook) Phonebook
- (https://www.arizona.edu/weather) Weather

### Footer - Social Media
- (https://facebook.com/uarizona title="Visit our Facebook page") Facebook
- (https://twitter.com/uarizona title="Visit our Twitter page") Twitter
- (https://instagram.com/uarizona title="Visit our Instagram page") Instagram
- (https://linkedin.com/edu/university-of-arizona-17783 title="Visit our LinkedIn page") LinkedIn
- (https://youtube.com/universityofarizona title="Visit our YouTube page") YouTube

**Comment by akslay** [comment]
- Use `az_demo` content as a reference point for creating default menu content. Should be able to copy the files needed and update machine names, labels, descriptions, etc. to pertain to Global Footer.
- `az_demo.install` lines 18-23 need to be included in the module file (update accordingly to match `az_global_footer` machine names)
- Include an `az_global_footer.install` file and include `hook_install()` and `hook_uninstall()' functions (update accordingly to match `az_global_footer` machine names)
- Include a `.json` file for the menu data in `az_global_footer/data`
- Include `az_global_footer_links.yml` file in `az_global_footer/migrations` (update accordingly to match `az_global_footer` machine names.

**Comment by akslay** [comment]
Verbiage will need to be added to the module (and maybe on Quickstart documentation site as well) informing site admins that enabling the module might overwrite any existing links they have in the `Footer - Main` menu. Recommend moving those links to a separate/custom menu?

**Comment by trackleft** [comment]
Please add config to turn on this setting https://github.com/az-digital/az_quickstart/blob/main/themes/custom/az_barrio/config/install/az_barrio.settings.yml#L34
In the .install file.

**Comment by smayden** [comment]
@michaelhagedon noticed an issue on a site he was building with the title on the menu switching out when a child menu item was placed in the menu. See this [slack conversation](https://uarizona.slack.com/archives/C0SAW6H4J/p1640036072063300).

This might be good to test to see if we can recreate the issue as we get the final elements of the global footer finished (it may be slightly out of scope, but it is fairly common for people to edit the content fo the global footer).
