### ISSUE TITLE
Migrate menus

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#1065]

**Comment by camikazegreen** [comment]
A decision was made to specifically only migrate front-end Quickstart 1 menus:

- Main nav
- Utility links
- Footer menus

**Comment by joeparsons** [comment]
Looks like we may have to wait until Drupal core 9.3.0 to be able to migrate only certain menus using the `menu_link` migrate source plugin provided by Drupal core:
https://www.drupal.org/node/3219548
