### ISSUE TITLE
Invisible close/exit button in editor

### ISSUE THREAD

**Issue by elyssanaval** [az-digital/az_quickstart#1071]
### Describe the bug
The close button in the text editor modal screen is not visible. The `<button> `  element is there and it is functioning well, but it appears to be missing since the color is the same as the background color of the modal header.

### To Reproduce

1. Go to any page with a text editor.
2. Open the text editor. Click on  the "Media Library" icon.
3. In the modal/dialog box, there is no close/exit button. See top/right corner of the modal box.

Note: This problem occurs in other editor toolbar options such as "Embed Content", "Insert Bootstrap Grid Columns", and "Embed Custom Block."

##  Screenshots
**Button in default state**
<img width="1344" alt="CloseButton1" src="https://user-images.githubusercontent.com/11656335/136300042-57118379-cc67-4025-a1e7-58bbbfb6643f.png">

**Button in hover state**
<img width="1315" alt="CloseButton2" src="https://user-images.githubusercontent.com/11656335/136300057-f74b2909-bc3a-4f4b-9172-3827ec58f330.png">

**Comment by camikazegreen** [comment]
Background on what that dialog box should look like in Claro here: https://www.drupal.org/project/drupal/issues/3023311

**Comment by joeparsons** [comment]
Seems this may be a Boostrap Barrio issue:
https://www.drupal.org/project/bootstrap_barrio/issues/3227133
