### ISSUE TITLE
Define Mapping between paragraph item, sections and blocks

### ISSUE THREAD

**Issue by barrettbaffert** [az-digital/az_quickstart#108]
**Do not disclose security vulnerabilities here, please email us instead: 
az-digital-security@list.arizona.edu**

## What is the problem that we want to solve?
A clear description of what's being investigated and why.

## Conditions of satisfaction
- [ ] The considered options are documented
- [ ] A recommended next step is documented
- [ ] An estimate of time and effort is provided for the recommendation
- [ ] …

**Comment by camikazegreen** [comment]
Mapping flow charts are being added here as the are created:
https://drive.google.com/drive/folders/15uqQ0-c3VlmbNT9V0Z4nEE-0GbG1_vpS?usp=sharing

**Comment by mschmeling14** [comment]
Closed. Work not performed. Decided to go a different direction.
