### ISSUE TITLE
Allow content editors to edit any media

### ISSUE THREAD

**Issue by aslaymoore** [az-digital/az_quickstart#1085]
## Problem/Motivation
Editors should be able to edit any media. Currently they are only able to edit something they uploaded themselves.

### Describe the bug
Permissions are set so that only content admins can "edit any" media, which means if you didn't upload the document/image you can't modify it. Content editors should be able to edit any media (just like they can edit any content), otherwise the content admin role would need to be added to standard site editors.

## Proposed resolution
Modify permissions for content editor role so they can "edit any" media.

**Comment by smayden** [comment]
I believe this issue was recently fixed: https://github.com/az-digital/az_quickstart/pull/1025
