### ISSUE TITLE
Composer version in drupal/core-dev-pinned causing security GH actions workflow to fail

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#1093]
## Problem/Motivation
The composer version [pinned in in drupal/core-dev-pinned](https://github.com/drupal/core-dev-pinned/blob/9.2.7/composer.json#L15) is currently causing our security GH actions workflow to fail on all PRs & commits.

### Describe the bug
Example failure:
https://github.com/az-digital/az_quickstart/runs/3955221623

Composer security vulnerability details:
https://github.com/composer/composer/security/advisories/GHSA-frqg-7g38-6gcf

### To Reproduce
Create a PR.

## Proposed resolution
We could consider using an inline composer alias to use a newer composer version `as` the version specified by drupal/core-dev-pinned or just wait for a core update.

**Comment by trackleft** [comment]
Closing as outdated
