### ISSUE TITLE
Add News view to match C/A "Content Hub" mockups

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#1103]
## Motivation
Casual Astronaut frequently includes a "Content Hub" section in their mockups. This commonly includes a category filter, custom view title, featured article, and category tags on the news teasers (separate issue).

### Screenshot
![image](https://user-images.githubusercontent.com/59745109/157512920-7435dd6f-49f4-444c-91dd-afa7143c91f5.png)

## Solution
- [ ] Add a new view to News that includes a category filter for existing taxonomy
- [ ] #1500
- [ ] Add new view to News using the Feature display mode
- [ ] Connect the view displays into one /content-hub page

**Comment by camikazegreen** [comment]
Here are six other mockups of content hubs provided for various projects by Casual Astronaut.

**Minerals**
https://invis.io/BR11W094WUF3#/459894296_2_Content_Hub
 
**Veterinary Medicine**
https://invis.io/M611K70NA24J#/457057832_7_Content_Hub
 
**Department of Surgery**
https://projects.invisionapp.com/share/XSZWYGD65VZ#/screens/442258919
 
**Optical Sciences**
https://projects.invisionapp.com/share/KTYVEZK92WG#/screens/432639331
 
**Environment**
https://invis.io/U7OHEES3G4E#/324382627_7_Content_Hub
 
**Cals Invest**
https://invis.io/Q7126ZDQS3Z5#/462574275_6_Content_Hub
