### ISSUE TITLE
AZ Person email addresses wrapping

### ISSUE THREAD

**Issue by akslay** [az-digital/az_quickstart#1104]
## Problem/Motivation
AZ Person email addresses on the card view mode wrap if they exceed the length of the container, which creates an awkward visual appearance.

## Proposed resolution
Need to have a group discussion, but perhaps implement an ellipses? Or other solution.

##  Screenshots
![Screen Shot 2021-10-26 at 9 03 49 AM](https://user-images.githubusercontent.com/52931751/138917570-468225ea-4c68-472c-8b9b-725d9d471379.png)

**Comment by danahertzberg** [comment]
Duplicate of #1328
