### ISSUE TITLE
Migrated users are getting added as Administrators instead of Authenticated

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#1143]
## Problem/Motivation
When migrating people, we want to give them the permission with least-privilege, and then have the person migrating the site assign the appropriate roles.

### Describe the bug
During the migration workshop, we saw that all of the migrated users were being given the Adminisrator role.

### To Reproduce

1. Run the az_migration group.
2. Check the users that were migrated. They are added as Administrators instead of Authenticated.

**Comment by trackleft** [comment]
@camikazegreen if we want all users to be mapped to authenticated we can just change this to authenticated
https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_migration/migrations/migrate_plus.migration.az_user.yml#L52
