### ISSUE TITLE
Clean up scrollbar jank for full-width bg paragraphs.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1151]
> I'm not sure what is causing this, but now on Probo, when I navigate to the homepage most of the menu items are gone...
> 
> Overall, the horizontal scrollbars are present during page load, and then go away once it is complete.

I loaded the pages before the demo content was fully added, I cleared cache, please try again
https://14005782-4f60-4d3c-bae8-b4ee7e4e0199.probo.build/pages/text-background

There is some level of jank, but I think that might be because of the load order, which we can address in a follow-up in my opinion. RTBC

_Originally posted by @trackleft in https://github.com/az-digital/az_quickstart/issues/1140#issuecomment-974310370_

**Comment by danahertzberg** [comment]
Per Chris: resolved with sidebar ticket
