### ISSUE TITLE
Update WWW link for wordmark in red bar to point to https url

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#1153]
## Motivation
The link on the University of Arizona workmark in the red bar at the top of all Quickstart 2 sites currently points to http://www.arizona.edu. It should ideally point to https://www.arizona.edu

### Is your feature request related to a problem? Please describe.
Pointing to the http link redirects to https, so not really a user facing problem. But having 301 redirects is less ideal for SEO.

### Describe the solution you'd like
Should be simple enough to link to https

**Comment by danahertzberg** [comment]
https://github.com/az-digital/az_quickstart/blob/main/themes/custom/az_barrio/templates/layout/page.html.twig#L90-L92
