### ISSUE TITLE
Update documentation related to 2.0.10

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#1158]
Issues covered in this release:

Those that might need documentation:

Closes: #1005 Refactoring captions on news to use image caption (#1108) - DONE Updated: https://quickstart.arizona.edu/create-content/adding-news-pages

Closes #654: On presave, check if there is an overridden thumb, if there is replace it on the video (#913) - DONE Updated: https://quickstart.arizona.edu/create-content/images-videos-and-files

Closes #1064 - Fix reorder people (#1115) - DONE updated this page: https://quickstart.arizona.edu/create-content/people-directories/managing-people

These don't seem like they need documentation:
Closes #1122 Updates editorial workflow to allow published to published (#1126)
Closes #1066: Add larger space around content options to paragraph types (#1068)
Closes #1154: Remove problematic role mapping from az_user migration. (#1155)
Closes #1128: Migration improvements for source paragraph items containing field collections. (#1130)
Closes #1139: Fixes horizontal scrollbars on full-width paragraphs. (#1140)
Update Arizona Bootstrap to 2.0.13 (#1149)
Closes #1083 Ensure paths are migrated for all content types. (#1124)
Closes #1123 Migrate redirects (#1141)
Closes #1143 Migrated users are getting added as Administrators instead of Authenticated (#1148)
Closes #1065: Added migration for Quickstart menu links. 
Closes #1127: Added marquees to flexible page migration. (#1125)
Update drupal/webform requirement from 6.0.5 to 6.1.0 (#1113)
Update drupal/smart_date requirement from 3.4.2 to 3.4.3 (#1086)
Update README.md (#1120)
Close #1044 Allow site builders to customize text on media paragraphs through the UI. (#1059)
Update drupal/media_library_edit requirement from 2.0 to 2.1.0 (#1097)
Update drupal/exclude_node_title requirement from 1.2 to 1.3.0 (#1095)
Closes #805: Fix button classes and path in carousel migration. (#1112)
Closes #882: Migration for D7 flexible page content type (to az_page). (#895)

**Comment by trackleft** [comment]
##Full width paragraph improvements.

### For Content Editors

- Improved full-width paragraph editor experience to show background within the edit page.
- Added the ability to override video cover images on full-width media paragraphs.
- Added Responsive images to full-width backgrounds

### For Site-builders
- Added the ability to modify full-width paragraph view modes through the UI

Intermediate fix for full width backgrounds showing a horizontal scroll bar.

**Comment by smayden** [comment]
> ## Full-width paragraph improvements.
> ### For Content Creators, and Editors
> * Improved full-width paragraph editor experience to show background within the edit page.
> * Added the ability to override video cover images on full-width media paragraphs.
> 
> ### For Site-builders
> * Added the ability to modify full-width paragraph view modes through the UI
> 
> Intermediate fix for full width backgrounds showing a horizontal scroll bar.

@trackleft Were you thinking these as things to highlight about the release in a news item for content editors? Or notes on specific documentation to update. I updated the video thumbnail info on the page about images/videos, but I'm not sure the other bullets tie to specific documentation to update.

**Comment by trackleft** [comment]
Oh, I was thinking for the news item for content editors.
