### ISSUE TITLE
Create Person content type

### ISSUE THREAD

**Issue by barrettbaffert** [az-digital/az_quickstart#116]
The MVP of the Person content type will match the D7 version of the content type. The addition of user functionality may or may not be added post-MVP (pending decision).

- [x]  Create content type and add necessary fields
- [x]  Style main view mode
- [x]  Add and configure "card" view mode
- [x]  Add and configure "row" view mode
- [x]  Add "Category" taxonomy
- [x]  Add "Category - Secondary" taxonomy
- [ ]  Add CSS file + styles for any Person-specific styles not included in bootstrap
- [ ] Export all configuration/templates/code & create pull request

**Comment by akslay** [comment]
Drupal issue related to exposing the title field in view modes:
https://www.drupal.org/project/contrib_tracker/issues/2607758

**Comment by trackleft** [comment]
It was determined that using the User entity type as content would be less ideal than adding a permission that allows authenticated users to edit their own content.

Related to: #3553
