### ISSUE TITLE
Make option for wider text area for text on media more obvious to content editors

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#1166]
## Motivation
Note: the details functionality originally described here already exists in QS2 when choosing the 'none' content position. This is not obvious to content editors, so this ticket should be repurposed to improve the language used on that option.

Original ticket:
For the old marquee in QS1, the text box when aligned centered was much wide than what we have with the current box style for Text on Media in QS2.

Quickstart 1 example from Arizona.edu homepage:
![image](https://user-images.githubusercontent.com/10873398/144291795-00d90b38-9d33-41d7-bb96-4945f218d1a4.png)

Quickstart 2 example:
![image](https://user-images.githubusercontent.com/10873398/144291985-fcb78725-9343-468d-8f2f-367c843670ab.png

### Is your feature request related to a problem? Please describe.
The current settings will likely pose a problem for migrated content and/or sites that frequently use this paragraph/pattern for displaying content over an image on larger screens (8+ key pages on WWW)

### Describe the solution you'd like
Update the column-width styles for Box style-centered to be col-lg-12 to match the QS1 marquee center style. 

### Describe alternatives you've considered
We could consider giving content editors choices around the box size, but I worry this would be overly complicated. I think the current smaller-sized box will look less than ideal across most use cases.

**Comment by trackleft** [comment]
This can be done by selecting the none option 
![image](https://user-images.githubusercontent.com/1023167/144305996-12432aa8-49a7-4eb1-b8d6-a8097a6d2467.png)

**Comment by trackleft** [comment]
We should change this setting to full-width.
