### ISSUE TITLE
Person content type demo content

### ISSUE THREAD

**Issue by barrettbaffert** [az-digital/az_quickstart#119]

**Comment by camikazegreen** [comment]
Link to Probo build with existing people: https://341447d4-2ea6-49f5-95c9-695d19dd094d--site-migration.probo.build/jsonapi/node/az_person
Link to existing person migration: https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_migration/migrations/migrate_plus.migration.az_node_person.yml
Link to existing demo module: https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_demo/migrations/az_demo_menu_links.yml
