### ISSUE TITLE
Reassess card deck width settings

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#1207]
## Motivation
The Arizona Bootstrap documentation relates the medium breakpoint with tablet sizes. However, the card deck settings for tablet width set the small breakpoint.

- [Bootstrap docs](https://digital.arizona.edu/arizona-bootstrap/docs/2.0/layout/overview/#responsive-breakpoints)
- [Current tablet card deck settings](https://github.com/az-digital/az_quickstart/blob/46f1fa473b136b7d45e7840bfa31d0a8354b11fa/modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZCardsParagraphBehavior.php#L53)

## Proposed resolution
Change the card deck width for tablet settings to set the medium breakpoint. And change the desktop settings to only set the large breakpoint.

Change [desktop settings](https://github.com/az-digital/az_quickstart/blob/46f1fa473b136b7d45e7840bfa31d0a8354b11fa/modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZCardsParagraphBehavior.php#L26) to the following:
```
    // Card deck width for desktop.
    $form['card_width'] = [
      '#title' => $this->t('Cards per row on desktop'),
      '#type' => 'select',
      '#options' => [
        'col-lg-12' => $this->t('1'),
        'col-lg-6' => $this->t('2'),
        'col-lg-4' => $this->t('3'),
        'col-lg-3' => $this->t('4'),
      ],
      '#default_value' => $config['card_width'] ?? 'col-lg-4',
      '#description' => $this->t('Choose how many cards appear per row. Additional cards will wrap to a new row. This selection sets the cards per row on desktops with automatic defaults set for tablet and phone. Override cards per row on tablet and phone in Additional options.'),
    ];
```

Change [tablet settings](https://github.com/az-digital/az_quickstart/blob/46f1fa473b136b7d45e7840bfa31d0a8354b11fa/modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZCardsParagraphBehavior.php#L53) to the following:
```
    // Card deck width for tablets.
    $form['az_display_settings']['card_width_sm'] = [
      '#title' => $this->t('Cards per row on tablet'),
      '#type' => 'select',
      '#options' => [
        'col-md-12' => $this->t('1'),
        'col-md-6' => $this->t('2'),
        'col-md-4' => $this->t('3'),
        'col-md-3' => $this->t('4'),
      ],
      '#default_value' => $config['az_display_settings']['card_width_sm'] ?? 'col-md-6',
      '#description' => $this->t('Choose how many cards appear per row. Additional cards will wrap to a new row. This selection sets the cards per row on tablets.'),
      '#weight' => 1,
    ];
```

**Comment by akslay** [comment]
Would it be plausible to bring up this issue again and have it included sooner as a bug fix rather than an enhancement? (It looks pretty bad on the smaller side of the "desktop" breakpoint when there's a sidebar), and I've been getting increasing questions/complaints from site builders about the width of cards.

Example:
![Screen Shot 2022-05-04 at 9 23 08 AM](https://user-images.githubusercontent.com/52931751/166726403-0d4f8e5a-51c3-4da4-a1ff-d65ab452c647.png)
