### ISSUE TITLE
Persistent main nav borders

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#1208]
When disabling or removing the main nav block from the navigation region (top nav) the borders remain when they shouldn't.

See above image for gray lines
![image.png](https://images.zenhubusercontent.com/5eb9d10a2b1f2c51836b60e3/7f937373-75e4-4ede-a32b-25a09ab41a6d)

**Comment by cpoff** [comment]
After a little experimentation, I found border-top and border-bottom applied to the navbar-offcanvas class, but there's no borders at all in the navbar class. I toggled the offcanvas class using inspector and it toggled them.

I'd like to walk through the steps where the navbar is added/removed so I can then see the action that's (possibly) adding the class or not removing the existing class.

**Comment by joeparsons** [comment]
> That _might_ broaden the impact a little too much. But I'll look into it.
> 
> Really where I'm at now is the simple question: Why are Off Canvas attributes impacting desktop/non-mobile displays?

https://github.com/az-digital/arizona-bootstrap/blob/main/scss/_navbar-offcanvas.scss#L230-L231

**Comment by trackleft** [comment]
I think this might actually be a quickstart issue with az_barrio and could probably be "fixed" by unchecking the box in the theme.

**Comment by trackleft** [comment]
In Quickstart the off canvas nav is actually a setting that is independent from the menu block.
If they remove the block the setting can still be set and they could use their own nav block.
Might be able to refactor it a bit to allow more flexibility in terms of which breakpoint to show which version of the menu for example. Or to allow removing those borders and still use the off canvas menu.
https://github.com/az-digital/az_quickstart/blob/main/themes/custom/az_barrio/templates/layout/page.html.twig#L133-L151
