### ISSUE TITLE
Allow bulk operations to update content/taxonomy terms

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#1212]
## Motivation
Bulk operations in Quickstart 1 allowed you to change a value or taxonomy term across multiple pieces of content. This is very useful and saves time for sites with large amount of content.

Quickstart 1: (with "change value" option):
![image](https://user-images.githubusercontent.com/10873398/147970518-aa0d94d9-dbb5-42c4-9dd9-0801ba7337c3.png)

Quickstart 2:
![image](https://user-images.githubusercontent.com/10873398/147970367-e6f48d57-9863-463c-ad01-3ad9cae39f4e.png)

### Is your feature request related to a problem? Please describe.
This feature is particularly useful for applying taxonomy terms. For example, on a departmental website you need to apply a new taxonomy term to 200+ people, it would be very laborious to edit each person and add the term.

### Describe the solution you'd like
It would be nice if it could function the same as in Quickstart 1 with the "change value" option (need to investigate what is possible in Drupal 9)

### Roles and Permissions considerations
Ideally this functionality could be used by:
- Content administrator
- Administrator

**Comment by smayden** [comment]
In Quickstart 1 this appears to be configured on the Nodes (Content) view under Fields for Bulk Operations: Content

![image](https://user-images.githubusercontent.com/10873398/147976525-fa0e47ce-a0c6-448b-bf56-c4edc5768fc9.png)

I suspect that the module View Bulk Operations is being used for this.

**Comment by akslay** [comment]
Looks like we might need to add this module to allow for that functionality: https://www.drupal.org/project/views_bulk_edit
