### ISSUE TITLE
Mobile menu/search break if you turn off institutional header wordmark logo

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#1222]
## Problem/Motivation
In working on getting Arizona.edu into Quickstart 2, we are noticing that when you turn off the institutional header wordmark logo in the theme settings (necessary for WWW) the red header area on small screens is broken.

![image](https://user-images.githubusercontent.com/10873398/149567586-2691f04a-4dd2-4955-a8db-f387062660ba.png)

### Describe the bug
When you turn the setting off, the redbar disappears on mobile. The search icons and menu hamburger still appear, but are not functional at all. The Mobile menu can not be navigated.

![image](https://user-images.githubusercontent.com/10873398/149567719-336542c6-c597-4cdc-a2d1-01cae69b050c.png)

### To Reproduce

1. Go to '/admin/appearance/settings/az_barrio'
2. Uncheck the checkbox under Institutional Logo Settings
3. Go to the homepage and view on small screen
4. Attempt to access mobile menu

### Expected behavior

It is expected that the redbar would appear and the search/menu icons would still function. Most sites use the institutional wordmark, but it is redundant on Arizona.edu and some other sites.

**Comment by joeparsons** [comment]
I think this may be due to these styles in UA Zen not existing in AZ Barrio:
https://bitbucket.org/ua_drupal/ua_quickstart/src/7.x-1.x/themes/custom/ua_zen/css/styles.css?at=7.x-1.x#lines-268:272
