### ISSUE TITLE
Text on Media PHP error: [] operator not supported for strings

### ISSUE THREAD

**Issue by akslay** [az-digital/az_quickstart#1225]
### Describe the bug
On the most recent version of Quickstart 2.0 (2.0.13), the following PHP error occurs after save when you add a Text on Media component to a Flexible Page.

```
Error: [] operator not supported for strings in Drupal\az_paragraphs\Plugin\paragraphs\Behavior\AZTextWithMediaParagraphBehavior->view() (line 260 of /code/web/profiles/custom/az_quickstart/modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php)
```

### To Reproduce

1. Create a Flexible Page
2. Add a Text on Media component and fill out all the fields
3. Save the page

Upon save, you should see the error.

**Comment by akslay** [comment]
Might be related to this change?
https://github.com/az-digital/az_quickstart/pull/1186
https://github.com/az-digital/az_quickstart/releases/tag/2.0.12

**Comment by trackleft** [comment]
Is this a new site? or an updated site?

**Comment by akslay** [comment]
It's a "new" site that's been receiving upstream updates. Still in development

**Comment by joeparsons** [comment]
Not sure why the issue is happening but a bandaid fix would be to add something like this to the `view()` method of the text on media behavior class (before the line that appends a class).
```
if (isset($build[‘#attributes’][‘class’])) {
  $class = $build[‘#attributes’][‘class’];
  if (!is_array($class)) {
    $build[‘#attributes’][‘class’] = [$class];
  }
}
```

**Comment by trackleft** [comment]
This is where the real issue lies https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZDefaultParagraphsBehavior.php#L169

**Comment by trackleft** [comment]
@akslay you can turn this off /admin/structure/paragraphs_type/az_text_media
![image](https://user-images.githubusercontent.com/1023167/149596058-d882b1c5-0caa-432c-959b-0d88c9215cfa.png)

**Comment by akslay** [comment]
Ahh haaa. Yep that fixed it on this site; thanks Chris! I'll leave this ticket open though for the issue you pointed out.
