### ISSUE TITLE
Routing of menu links are broken on some migrated sites.

### ISSUE THREAD

**Issue by Carris-Toupin** [az-digital/az_quickstart#1230]
## Problem/Motivation

Routing of Primary Nav parent and child menu links are not being migrated properly. 

### Describe the bug

See this site: https://live-azs-uxua.pantheonsite.io/

Parent Links:  The content for parent links are migrated, but is not placed in the parent link. 

### To Reproduce

Pages that are mostly broken (Can be edited but not viewed)
/about 
/mentors (contains content from Entity Embed)
/initiatives 
/participant-pool

Parent menu links are broken and missing their landing page content. The page can be navigated and edited in Content.
/get-involved
/initiatives

## Proposed resolution

Please resolve issues to work similar to the UAS site

### Expected behavior

Normal AZS site behavior.

### Desktop (please complete the following information):

Problem is evident on all devices, OS's and browsers.

**Comment by natebyerley** [comment]
This is definitely a redirect issue.  I've detailed the issue here: https://docs.google.com/spreadsheets/d/1rkBitetwy9AH9-HRvmZubdXr3Qd0eqLqNTVWIw9wkDQ/edit#gid=1201776939

**Comment by natebyerley** [comment]
Another example of parent links not clickable, on a much cleaner site than uxua: 
https://gcr.arizona.edu/ | https://live-azs-gcr3.pantheonsite.io/home

**Comment by natebyerley** [comment]
I'm not sure this is an issue we need to keep open.  This is generally due to non-relative nav links on origin site, not a failure of migration.  I would advise closing this ticket.  The only persistent nav issue is multiple home links, but this is a simple fix and low priority (not sure if it has its own issue)

**Comment by natebyerley** [comment]
Issue has not persisted.  Closing.
