### ISSUE TITLE
Contacts that are being migrated for Events are also being added to other Pages.

### ISSUE THREAD

**Issue by Carris-Toupin** [az-digital/az_quickstart#1232]
## Problem/Motivation
Contacts that are attached to Events are also being added (randomly?) to Pages.

### Describe the bug

On this page: https://live-azs-uxua.pantheonsite.io/learn-ux

The following contacts are not suppose to be there.

Bob Liu
bobliu@arizona.edu
Adriana Picoral
adrianaps@arizona.edu
Adriana Picoral
adrianaps@arizona.edu

On this page: https://live-azs-uxua.pantheonsite.io/learn-ux/our-guide-ux/getting-started

The following contacts are not suppose to be there.

Rebecca Blakiston
blakisto@arizona.edu

### To Reproduce

Various places on this site: https://live-azs-uxua.pantheonsite.io/

## Proposed resolution

TBD

### Expected behavior

For migrated sites to retain similar functionality to UAS sites.

##  Screenshots

![Screen Shot 2022-01-18 at 4 26 27 PM (3)](https://user-images.githubusercontent.com/97066045/150021403-d8477e01-f734-48fb-be34-9b1b2812e84e.png)

### Desktop (please complete the following information):

Problem exists on all OS’s, Browsers and devices.

**Comment by smitahantzios** [comment]
Hi Team,

Please explain the issue more. 

- What are the other pages that the contact to be attached ? 
- Also please provide the relation/mapping of the contact to the other pages. 
- Do we need to write extra migration script to map the contact to the other pages ?

cc: @danahertzberg  @joeparsons

**Comment by trackleft** [comment]
@smitahantzios I think you'll have to migrate the D7 version of uxua to a fresh quickstart site locally to reproduce this.
Then I think you can go to the specified pages and see if the contact paragraphs are being added to the wrong pages.
They might be unpublished.

On the d9 site you'll have to find which pages the contacts paragraphs are supposed to be attached to.

**Comment by smitahantzios** [comment]
@trackleft - I have analysed the D7 DB & D9 migrated DB. All contacts are migrated and attached to the correct references. Please see the details below. Guide me if I am wrong.

**D7 DB** 

{ field_data_field_uaqs_contacts --> 65 records only and it is attached to "uaqs_event" }

**D9 Migrated DB** 

{migrate_map_az_paragraph_contact --> 65 records that is all records for contacts are migrated }
{node__field_az_contacts --> 65 records and all are referenced to "az_event" }

Also checked randomly some of the "az_event" nodes in migrated D9 sites. All seems to correctly displaying.

Some examples are below :

<img width="1227" alt="Example 1" src="https://user-images.githubusercontent.com/11652557/156351492-05cddfa1-6d75-4717-b679-5528b1cbd72b.png">

<img width="1177" alt="Example 2" src="https://user-images.githubusercontent.com/11652557/156351549-e387cff9-a517-4325-9c0d-f1948536fe55.png">

**Comment by danahertzberg** [comment]
@Carris-Toupin Please confirm if this issue is still happening

**Comment by trackleft** [comment]
This is definitely still happening, and I think I know why.

Field Collections on D7 and Paragraphs on D7 can have the same `item_id` since they reside in different database tables on the source site.

When we do migration_lookup here: https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_migration/migrations/migrate_plus.migration.az_node_flexible_page.yml#L114

We are just finding the `item_id` in the lookup table and attaching the new paragraph to to field.

**Comment by trackleft** [comment]
Ok, I think we can just remove contacts in the migration lookup for flexible page since I don't think we even allow contacts on flexible pages in quickstart 1.
