### ISSUE TITLE
Blank Text areas are getting added to many pages.

### ISSUE THREAD

**Issue by Carris-Toupin** [az-digital/az_quickstart#1238]
## Problem/Motivation
Extra text areas are appearing in the migrated site that were not present in the original site.

### Describe the bug
 When looking at the View tab on the migrated page it looks fine, but in the Edit tab you can see an addition Text area was created with no content in it. This 'extra' text area is not present in the original site.

### To Reproduce
UAS site example: https://uxua.arizona.edu/learn-ux/research-testing

AZS site example: https://live-azs-uxua.pantheonsite.io/learn-ux/research-testing

## Proposed resolution
TBD

##  Screenshots

Edit tab on UAS site:
![Screenshot 2022-01-18 at 19-53-50 Edit Flexible Page Research testing UX UA](https://user-images.githubusercontent.com/97066045/150043187-0bd80b5f-9085-4e8c-a406-a2a3b1071810.png)

Edit tab on AZS site:
![Screenshot 2022-01-18 at 19-55-14 Edit Page Research testing Arizona Site](https://user-images.githubusercontent.com/97066045/150043349-4e3577c2-87e8-4737-8ea8-2a18edd45aa7.png)

### Desktop (please complete the following information):
 
Problem exists on all OS’s, Browsers and devices.

**Comment by natebyerley** [comment]
This may be a duplicate issue, as I think this might have been handled in 2.2.0, though I do not see that here.

**Comment by trackleft** [comment]
This was fixed in the 2.2 release
