### ISSUE TITLE
Bottom spacing not migrating with content elements

### ISSUE THREAD

**Issue by natebyerley** [az-digital/az_quickstart#1246]
**Do not disclose security vulnerabilities here, please email us instead: 
az-digital-security@list.arizona.edu**

## Problem/Motivation
On multiple migration test sites, Bottom Spacing for content elements (Text, Text on Media, Cards, etc.) is set to 0 on migrated sites, when original site has non zero spacing settings. 

### Describe the bug

Compare the spacing between elements on this UA Site: https://hsi.arizona.edu/studentresources 
And the lack of between element spacing on the migrated site https://live-azs-hsi1.pantheonsite.io/studentresources

Note space between last element on footer: https://gcr.arizona.edu/congressional-internship
And no space above footer: https://live-azs-gcr3.pantheonsite.io/congressional-internship

### Expected behavior

"Bottom Spacing" setting for content elements on a page should match between existing and newly migrated sites.

##  Screenshots

See links above, issue is not hard to see.

### Desktop (please complete the following information):
 
Not device specific.

### Smartphone (please complete the following information):

Issue present on all devices.

**Comment by natebyerley** [comment]
This is a medium priority issue. Setting bottom space is often overlooked when working on pages, so requires reopening and editing pages for each slight change, requiring visual review with each change.  It can also complicate testing and review. If we knew original settings came over by default, we could ignore bottom spacing on all successfully migrated content.

**Comment by trackleft** [comment]
This was fixed in 2.2 as far as I know

**Comment by trackleft** [comment]
This was fixed in 2.2 as far as I know as part of this PR https://github.com/az-digital/az_quickstart/pull/1345
