### ISSUE TITLE
Delete uaqs_navigation_overlay_menu_scroll.js.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1252]
## Conditions of satisfaction
Ensure that https://github.com/az-digital/az_quickstart/blob/main/themes/custom/az_barrio/js/uaqs_navigation_overlay_menu_scroll.js is unused and delete if it is.

**Comment by danahertzberg** [comment]
@trackleft What's the motivation behind this?

**Comment by trackleft** [comment]
That file is not in use as far as I can tell.

**Comment by trackleft** [comment]
I was mistaken, this is actually used
