### ISSUE TITLE
Update linkit module for SA-CONTRIB-042 (moderately critical security update)

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#1253]
## Problem/Motivation
https://www.drupal.org/sa-contrib-2021-042

## Proposed resolution
Update linkit to 8.x-4.4

**Comment by trackleft** [comment]
I don't think we are using linkit yet https://github.com/az-digital/az_quickstart/blob/main/composer.json

**Comment by joeparsons** [comment]
Oh yeah.  😅
