### ISSUE TITLE
Create news content type

### ISSUE THREAD

**Issue by barrettbaffert** [az-digital/az_quickstart#128]
Match QS1

**Comment by smayden** [comment]
A few questions on the requirements for matching what we have on QS1:

- I'm assuming that at least for the pre-release we will not have the Extra Info paragraph under Extra Body Content
- The current content type brings in a field collection for contacts. It looks like Field Collection is not included for D8/D9. Thoughts on best way of creating this functionality? Is the contacts used on events as well?

**Comment by danahertzberg** [comment]
> * I'm assuming that at least for the pre-release we will not have the Extra Info paragraph under Extra Body Content

I agree.
