### ISSUE TITLE
Views with exposed filters cause editing issues

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#1296]
## Problem/Motivation
When I add a view with exposed filters to a page via the Views paragraph type, I am unable to edit paragraph content.

### Describe the bug
Paragraph preview renders the filters in the form display. The form is no longer functional when filters are displayed.

### To Reproduce
1. Create a view with exposed filters and use ajax
2. Add new view to Views paragraph type selection
3. Add new view to a page
4. Save the page
5. Edit the page
6. Attempt to edit a paragraph

## Proposed resolution
Investigate whether this is an issue with the view, ajax, or the rendering of the paragraph in the editing view.

### Expected behavior
I should be able to edit paragraphs on a page.

**Comment by joeparsons** [comment]
We may be able to fix this by changing the field display options in the `preview` view mode for views paragraphs. (Probably by hiding the views field in the preview view mode).

**Comment by joeparsons** [comment]
Related viewsreference project issues on drupal.org:
https://www.drupal.org/project/viewsreference/issues/2938433
https://www.drupal.org/project/viewsreference/issues/3129609
