### ISSUE TITLE
Explore options for adding the DAM Intelligence Bank Drupal connector to Quickstart 2.

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#1313]
## What is the problem that we want to solve?
The university has adopted Intelligence Bank as the Digital Asset Manager for the university to make it easier to share images, videos and other digital assets around the whole university. 

Intelligence Bank provides a couple of different options for granting access to this DAM within Drupal sites: https://www.drupal.org/project/intelligencebank

This spike is to determine what the best path forward is to incorporate access to Intelligence Bank inside of Quickstart 2

## Conditions of satisfaction
- [ ] The considered options are documented
- [ ] A recommended next step is documented
- [ ] An estimate of time and effort is provided for the recommendation

**Comment by camikazegreen** [comment]
This actually looks like it should be a pretty straightforward enhancement, with one very obvious caveat: I can't actually figure out how to connect it to our specific instance of Intelligence Bank, and this isn't covered in any of their documentation. 

However, the rest of the implementation looks pretty simple:

- Add the required modules as Composer dependencies
  - 'drupal/intelligencebank:^2.4'
  - 'drupal/entity_browser:^2.6'
- Enable the modules (there is also a CK Editor plugin available, but I think we'd rather access this via the Media Browser, which can provide a consistent experience between our paragraphs and the CK Editor)
<img width="1104" alt="Screen Shot 2022-02-11 at 12 35 11 PM" src="https://user-images.githubusercontent.com/1509771/153657802-35ea9c5f-e113-4301-a139-a628aa75061c.png">
- Map the Media Types at /admin/config/services/ib_dam/media
<img width="817" alt="Screen Shot 2022-02-11 at 12 37 30 PM" src="https://user-images.githubusercontent.com/1509771/153658101-beec83de-e31b-413d-a066-67dd9c50bb3d.png">
- Enable the IntelligenceBank option for any paragraphs that we would like to enable it for, example /admin/structure/paragraphs_type/az_text_media/fields/paragraph.az_text_media.field_az_media
<img width="307" alt="Screen Shot 2022-02-11 at 12 39 36 PM" src="https://user-images.githubusercontent.com/1509771/153658371-fcbefd56-c7f7-472b-b15d-c5b7edbfa899.png">
- Then it will be available directly in the Media browser.
<img width="1145" alt="Screen Shot 2022-02-11 at 12 40 18 PM" src="https://user-images.githubusercontent.com/1509771/153658462-67c3eb69-dbaa-4a3a-98be-f556bc5f72fe.png">

Remaining exploration needed for:
- Figuring out how to connect this to our specific instance of IntelligenceBank (assets.arizona.edu). I'm hoping that we don't have to enable this domain by domain, because I think that would be a failure case.
- Figuring out how to enable this for our compound fields (Cards)

**Comment by trackleft** [comment]
On their website in italics at the bottom of the page
```
Note that it will need to be enabled on your platform before you can start using it. Please contact your Customer Success Manager or [helpdesk@intelligencebank.com](mailto:helpdesk@intelligencebank.com) to get started connecting IntelligenceBank with your Drupal environment.```

**Comment by danahertzberg** [comment]
This ticket is to determine direction for implementing. New ticket will be created for implementing by 2.4.0 release in July 2022.

**Comment by danahertzberg** [comment]
Biggest concern right now: This adds a separate media type instead of using the existing type

**Comment by trackleft** [comment]
I think we can close this issue with a new issue for implementation.
