### ISSUE TITLE
Enabling Global Footer module produces errors, breaks structure > menu

### ISSUE THREAD

**Issue by natebyerley** [az-digital/az_quickstart#1317]
## Problem/Motivation
Attempting to enable Global Footer (GF) module on a migrated site (azs-president)

### Describe the bug
When GF module is installed, error is generated saying that menu blocks that GF module is trying to install already exist.  These menu blocks are: 

block.block.az_barrio_footer_menu_info
block.block.az_barrio_footer_menu_main
block.block.az_barrio_footer_menu_resources
block.block.az_barrio_footer_menu_social_media
block.block.az_barrio_footer_menu_topics

Sure enough, every site (migrated, or not), already have these blocks installed. 

After, GF Module shows installed, but /admin/structure/menu is broken. 

For example, I just enabled (2/15) the GF footer on this site: https://test-azs-covid19.pantheonsite.io/admin/structure/menu

### To Reproduce

Install GF Module on any site.

Note, before install, that all footer blocks already exist at /admin/structure/menu

## Proposed resolution

Above my pay grade.

<img width="1450" alt="Screen Shot 2022-02-15 at 9 36 21 AM" src="https://user-images.githubusercontent.com/97116860/154108825-e3793ad6-97db-4d47-bb9c-f1c9afe5fcd2.png">
<img width="1299" alt="Screen Shot 2022-02-15 at 9 26 19 AM" src="https://user-images.githubusercontent.com/97116860/154109121-5e28f6d8-44e4-46e9-b447-a56e0ce60b04.png">

**Comment by joeparsons** [comment]
We discussed this in our Campus Web Services dev team standup this morning.

We think this is a result of the exported footer blocks getting moved from the install config for the install profile to the global footer module that was introduced in https://github.com/az-digital/az_quickstart/pull/1200.

A potential resolution would be to add an update hook (probably to the install profile) that deletes the blocks from the active config if the global footer module is not installed.

**Comment by trackleft** [comment]
To get around this issue on existing sites without having to update the codebase you can run the following commands before enabling the global footer.

```
drush config:delete block.block.az_barrio_footer_menu_info  
```

```
drush config:delete block.block.az_barrio_footer_menu_main  
```

```
drush config:delete block.block.az_barrio_footer_menu_resources  
```
```
drush config:delete block.block.az_barrio_footer_menu_social_media  
```
```
drush config:delete block.block.az_barrio_footer_menu_topics
```

**Comment by trackleft** [comment]
Related issue https://github.com/az-digital/az_quickstart/issues/1318
