### ISSUE TITLE
Investigate Trellis integration requirements 

### ISSUE THREAD

**Issue by barrettbaffert** [az-digital/az_quickstart#132]
**Do not disclose security vulnerabilities here, please email us instead: 
az-digital-security@list.arizona.edu**

## What is the problem that we want to solve?
A clear description of what's being investigated and why.

## Conditions of satisfaction
- [ ] The considered options are documented
- [ ] A recommended next step is documented
- [ ] An estimate of time and effort is provided for the recommendation
- [ ] …

**Comment by danahertzberg** [comment]
Unnecessary at this point
