### ISSUE TITLE
Changes sometimes lost when editing html source in standard editor

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#1322]
## Problem/Motivation
In prepping content for the Arizona.edu launch we are noticing that content edits sometimes don't save when editing multiple paragraphs at the same time.

### Describe the bug
On pages with multiple paragraphs, some changes are lost when editing the html source in the ckeditor (when the standard editor is still selected). Only the last paragraph edited in this way seems to save.

### To Reproduce

1. Create a page
2. Add several text paragraphs with content in them
3. Save your page
4. Edit the page
5. Edit multiple paragraphs and make edits by clicking on "Source" in the ckeditor to edit the source code
6. Make changes to styles in the HTML code (e.g. classes on a paragraph, or heading styles) on multiple paragraphs
7. Save the page
8. Notice where changes actually occur.

## Proposed resolution
I don't know a resolution, but right now we are having to save the page after editing each paragraph as a workaround.

### Expected behavior

Ideally changes would not be lost...

**Comment by smayden** [comment]
Noticed when editing content on Arizona.edu that this issue is still happening. 

https://www.arizonae.edu/highlights

1. Edited the page
2. Edited a text paragraph and clicked on "Source" to edit the html source code
3. Clicked on source again once I finished editing that html
4. Clicked on edit for a different text paragraph lower on the page and edited source again.
5. Saved my page
6. Noticed that only the updated in the second edit saved.

**Comment by Carris-Toupin** [comment]
I have noticed this with migration sites.
https://live-azs-aging.pantheonsite.io/

1. Edit page
2. Add media (image or video hosted on Youtube)
3. Edit a second text box further down the page.
4. Save at the bottom of the Edit screen
5. I do not see the media in the first edited area. Only the second area was updated.

**Comment by joeparsons** [comment]
This issue/patch might be related: https://www.drupal.org/project/drupal/issues/3095304

**Comment by joeparsons** [comment]
Someone also created a new issue in the Paragraphs module issue queue for this earlier today (no patch yet): https://www.drupal.org/project/paragraphs/issues/3273947

**Comment by joeparsons** [comment]
Found another issue that may be related based on Shoshana's additional findings:
https://www.drupal.org/project/drupal/issues/3102249
