### ISSUE TITLE
Add default permissions for content editor role for quick node clone.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1339]
Blocked by #1315 |

## Motivation
Address adding permissions separately from the PR adding quick_node_clone

Since we need to address overall methodology for adding default permissions for modules that are not enabled by default, or are introduced via release.
### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Content editor
   - can clone page
   - can clone news
   - can clone event
   - can clone person

**Comment by smayden** [comment]
This was addressed by: #1518
