### ISSUE TITLE
Resolve 9.3.x permissions issue(s)

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#1340]
~Blocks PR #1181~

Need to determine a way to address permissions in a Drupal core 9.3.0-compatible way

https://www.drupal.org/node/3193348

**Comment by joeparsons** [comment]
## Remaining issues after merging #1181

Various permissions are not being preserved by QuickstartConfigProvider:
- Entity Bundle permissions (e.g. `edit / own X entity`) generated by node, taxonomy, etc modules for entity bundles included in other modules (e.g. webform)
- `Assign X role` permissions for the Role Delegation module
- `use text format full_html` permission
