### ISSUE TITLE
Sidebar appears behind full-width elements in Firefox

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#1356]
## Problem/Motivation
In looking at other sidebar issues, it was noted that the sidebar is appearing behind text with background and text on media elements at the top of the page in Firefox.

In testing this appears to be a separate issue from #1331.

### Describe the bug
In Firefox, a sidebar navigation menu will appear hidden behind Text on Media and Text with Background paragraphs that are at the top of the page.  

This is happening both with the current 2.1.1/2.1.2 release as well as 2.0.X releases that I tested locally.

Text with Background example:
![image](https://user-images.githubusercontent.com/10873398/156227278-9586ce66-9704-4156-8c8e-cd81a1e6de4c.png)

Text on Media example:
![image](https://user-images.githubusercontent.com/10873398/156227393-a1e8c112-9d61-4ecc-a8fb-2b10daadd4bc.png)

Example from Psychology sandbox:
https://live-azs-psychology.pantheonsite.io/graduate-programs/phd-clinical-psychology

In testing this bug only appears to happen in Firefox browsers. It does not happen in Chrome or Safari.

### To Reproduce

1. Create a page
2. Add a text with background or text on media full-width paragraph to the page
3. Add the page to a menu
4. Save the page
5. View the page in Firefox

## Proposed resolution
Still researching...

### Desktop (please complete the following information):
 - Browser: Firefox (on at least three different devices)

**Comment by michaelhagedon** [comment]
The `sidebar_first` region has a flex order of -1 and maybe Firefox is doing this?
https://www.w3.org/TR/css-flexbox-1/#painting

**Comment by michaelhagedon** [comment]
Setting classes `order-1` on the `sidebar_first` region div and `order-2` on `main` partially fixes this on Firefox 97 without messing with `z-index`. Still problems, though:
![image](https://user-images.githubusercontent.com/645924/156457284-d67b3ce0-3e5e-41ce-9ce6-6549ff5cbb40.png)

**Comment by michaelhagedon** [comment]
More info: for Text on Media, playing the video _shows_ the menu. Pausing the video _hides_ the menu again! I do see a `background: none !important;` in the `az-video-playing` class that is being added when we play the video...
