### ISSUE TITLE
Global Footer (after 2.2 Update) Formatting Incorrect

### ISSUE THREAD

**Issue by natebyerley** [az-digital/az_quickstart#1384]
## Problem/Motivation

Testing implementation of Global Footer after 2.2 release (manually applied) to a manually migrated site.

### Describe the bug

Global footer organization looks correct on, but the spacing/formatting isn't right.

### To Reproduce

1. Applied 2.2 update
2. Tried to install Global Footer module
3. Got error (see screenshot)
4. Ran drush commands to delete blocks
5. Re-installed Global Footer module with success
6. Inspected footer, noticed formatting issues.  See 2nd screenshot.

<img width="1771" alt="Screen Shot 2022-03-07 at 3 49 25 PM" src="https://user-images.githubusercontent.com/97116860/157136013-2f831435-7bc9-4c9c-9a02-b231bf57a1c9.png">

<img width="1771" alt="Screen Shot 2022-03-07 at 4 18 58 PM" src="https://user-images.githubusercontent.com/97116860/157136035-40426ad1-bc05-4d3e-8fc4-3dc40a005f4e.png">

**Comment by trackleft** [comment]
@natebyerley did you happen to run the update on that site?

**Comment by trackleft** [comment]
I found that for some reason the [navbar_classes are being added to the navs in the footer](https://github.com/az-digital/az_quickstart/blob/main/themes/custom/az_barrio/templates/layout/page.html.twig#L80-L86).

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/1023167/157757566-49fece35-4e92-490d-a8f8-3dd207ef9ca0.png">

**Comment by trackleft** [comment]
On the RDIbc site, I saw this when updating
```
>  [notice] Legacy global footer blocks not deleted because config differences detected. Blocks will need to be manually deleted with drush in order to install Quickstart Global Footer module.
```

**Comment by joeparsons** [comment]
> On the azs-rdibc site, I saw this when updating
> 
> ```
> >  [notice] Legacy global footer blocks not deleted because config differences detected. Blocks will need to be manually deleted with drush in order to install Quickstart Global Footer module.
> ```

That's expected the if site wasn't updated to the latest Quickstart `2.0.x` release before upgrading to `2.1.x` or if config distro updates weren't applied while still on a `2.0.x` release.
