### ISSUE TITLE
Create Side Menu Block

### ISSUE THREAD

**Issue by barrettbaffert** [az-digital/az_quickstart#139]
In Structure > Blocks

**Comment by tadean** [comment]
Basic side menu block appears to already exist. Investigating theme changes needed for feature parity and necessary D9 `menu_block` settings.

**Comment by danahertzberg** [comment]
@tadean There may have been some confusion. I wasn't aware the block already existed. So I don't think any further work is needed for this ticket/Early Adopters release.

**Comment by danahertzberg** [comment]
After looking at the PR, adding the root parent as the title is a good addition. The styles should probably be addressed in bootstrap instead of the theme/quickstart.

**Comment by tadean** [comment]
> After looking at the PR, adding the root parent as the title is a good addition. The styles should probably be addressed in bootstrap instead of the theme/quickstart.

Noticed this issue in the queue:
#444
