### ISSUE TITLE
Change Grid Page display of AZ Person view to show fewer cards per row

### ISSUE THREAD

**Issue by bberndt-uaz** [az-digital/az_quickstart#1396]
## Problem/Motivation
The cards on the default Quickstart directory page are too narrow, causing names and email addresses to break across two lines.

Related issue: #1328 

### Describe the bug
Currently, on desktop screens, the Grid Page display of the Quickstart AZ Person view shows four cards per row. This results in some last names being pushed to a new line and all email addresses ending in @email.arizona.edu being broken across two lines. This behavior also occurs on tablet screens, where this display shows three cards per row.

### To Reproduce

1. Go to the directory page with a grid display on any Quickstart 2 site or enable the demo content in a test Quickstart site.
2. Notice how many names and email addresses are broken across two lines.

## Proposed resolution
Change the styling for this display to show three cards per row for desktop screens and two cards per row for tablets. This change would allow most names to appear on one line. The email address for people with shorter NetIDs would also appear on one line, even if the address ends in @email.arizona.edu.

### Expected behavior

I expect the default page display to provide a better fit for the typical content.

##  Screenshots
Current grid display:

![image](https://user-images.githubusercontent.com/74572157/157985554-820255b1-20d5-4c7b-8b0c-68634e865253.png)

Proposed grid display:

![image](https://user-images.githubusercontent.com/74572157/157985602-9982ad73-a224-4ed0-a794-0dea7ec570e0.png)

### Desktop (please complete the following information):
 - OS: macOS
 - Browser: Chrome
 - Version: 2.2

### Smartphone (please complete the following information):
 - N/A

**Comment by trackleft** [comment]
Sounds fine to me

**Comment by bberndt-uaz** [comment]
@trackleft and @danahertzberg suggested that we could add a new display for this instead of modifying the default display.

**Comment by bberndt-uaz** [comment]
Also see this issue from @trackleft: [Add additional "3 column" displays for views that have a grid view display for use on pages with one sidebar](https://github.com/az-digital/az_quickstart/issues/1645)
