### ISSUE TITLE
Add natural image style 

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#1403]
## Problem/Motivation
I want my embedded media to respect alignment selections when using natural size.

### Describe the bug
No image style exists for the natural image size (img-fluid is not being applied to image)

### To Reproduce
1. Embed small media in natural size
2. Select center alignment
3. Save page
4. Image is not centered

## Proposed resolution
Add image style for natural size

### Expected behavior
Embedded media should appear at its original natural size and aligned with selected setting.

**Comment by cpoff** [comment]
The left align seems to only happen because of the display attributes (`display:block`). I think I have this fix in two parts:

1. Add a wrapper div around the figure to set a new class. Media Type > Manage Display Natural Size. I added a field group wrapper called Align Natural Image and assigned the class: `align-natural-image`.
2. Add class CSS to style.css:

```
.align-natural-image {
	display: flex;
}
```
`display: grid` also appears to work just the same as flex, so we can swap if needed.

**Comment by cpoff** [comment]
![Uploading Screen Shot 2022-04-07 at 2.24.42 PM.png…]()

**Comment by cpoff** [comment]
![Screen Shot 2022-04-07 at 2 24 42 PM](https://user-images.githubusercontent.com/730076/162828575-b5bb5e82-3ece-4208-8be4-bd5289736cbb.png)

**Comment by cpoff** [comment]
![Screen Shot 2022-04-11 at 1 41 47 PM](https://user-images.githubusercontent.com/730076/162828671-32b25403-cac3-42d3-85bb-a32543fb64a7.png)

**Comment by bberndt-uaz** [comment]
Would adding the "img-fluid" class to images using the "Natural Size" display mode be within the scope of this issue as well? As @danahertzberg mentioned in the issue description, this class is not added with the "Natural Size" display mode but it is added with the other four display modes. I think the class would be helpful for preventing large images from breaking out of their container.

**Comment by cpoff** [comment]
The sm, med, lg, and square image styles all place a max-width on the figure. Then the actual HxW is applied to the img explicitly. With the Natural Size, I can't really put a max-width on it, and the img-fluid only works on the img and not the figure. I assume the img-fluid class is added by the theme?

**Comment by trackleft** [comment]
This is where the `img-fluid` class is added by the theme
https://github.com/az-digital/az_quickstart/blob/caec8c5750e126107b4f14d981af0302ff57e722/themes/custom/az_barrio/az_barrio.theme#L154-L158
