### ISSUE TITLE
Make content full content with within full width paragraph types

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#1405]
## Motivation
Since sidebar no longer appears on top of full width elements, I want their content to span the full width of the content space.

### Is your feature request related to a problem? Please describe.
Follow up ticket to https://github.com/az-digital/az_quickstart/issues/1202
Related to https://github.com/az-digital/az_quickstart/issues/1404
Resolved with https://github.com/az-digital/az_quickstart/issues/1405

**Comment by trackleft** [comment]
Fixed https://github.com/az-digital/az_quickstart/issues/1404
