### ISSUE TITLE
Change default CAS host to shibboleth.arizona.edu

### ISSUE THREAD

**Issue by MarkFischer** [az-digital/az_quickstart#1426]
When Shibboleth took over the CAS protocol, we can now just go direct to shibboleth.arizona.edu instead of webauth.arizona.edu. This cuts out one 302 redirection, and gets around one very rare bug with CAS auth to webauth.arizona.edu.

## Conditions of satisfaction
- [ ] CAS server hostname should be changed to shibboleth.arizona.edu in cas.settings.yml

**Comment by trackleft** [comment]
We should probably update Quickstart 1 as well https://bitbucket.org/ua_drupal/ua_cas/src/f18ac0bafd7ebcd4a59794e778af8aeb19badd94/ua_cas.strongarm.inc#lines-66

Though, if we do, we should also update the readme.

**Comment by MarkFischer** [comment]
<img width="636" alt="Screen Shot 2022-03-24 at 11 24 23 AM" src="https://user-images.githubusercontent.com/11525680/160452481-496867f1-e033-4407-8f9c-2b71edd1ae7d.png">
<img width="932" alt="Screen Shot 2022-03-24 at 12 52 53 PM" src="https://user-images.githubusercontent.com/11525680/160452498-d4c62ef4-6386-42e2-9cce-13e54354afac.png">

**Comment by MarkFischer** [comment]
Note, keeping the "University of Arizona WebAuth" for user facing text is fine. WebAuth is still the 'brand' for SSO.
