### ISSUE TITLE
Add default bottom spacing of 3 or 4 for Person page, Event page - match with News page

### ISSUE THREAD

**Issue by natebyerley** [az-digital/az_quickstart#1435]
- Person and Event pages have zero bottom spacing.  See screenshots.
- News pages have maybe 1 or 2 bottom spacing. Screenshot for this as well.
- Looking at default top and side spacing on all pages, it feels like a default bottom spacing for Person, Event and News pages should be 3 or 4. 

<img width="1515" alt="Screen Shot 2022-03-29 at 8 25 13 AM" src="https://user-images.githubusercontent.com/97116860/160648980-2606e7b5-b011-4f02-8c8e-c83f8658726e.png">
<img width="1515" alt="Screen Shot 2022-03-29 at 8 27 55 AM" src="https://user-images.githubusercontent.com/97116860/160649046-08d2e1c9-7474-4190-ba70-0048a3d2e5e8.png">
<img width="1515" alt="Screen Shot 2022-03-29 at 8 29 17 AM" src="https://user-images.githubusercontent.com/97116860/160649146-1bea4e43-aa53-4106-9635-cabd47a2051c.png">

**Comment by smayden** [comment]
FYI this ticket discusses the same issue: https://github.com/az-digital/az_quickstart/issues/746 (perhaps just close #746 in favor of this ticket?)
