### ISSUE TITLE
Empty caption/address space on all person images.  Hide space if no caption.

### ISSUE THREAD

**Issue by natebyerley** [az-digital/az_quickstart#1436]
There is a space under person images where a caption or address info goes - but most person images have no caption, yet the space remains.  Hide space if no caption
<img width="1515" alt="Screen Shot 2022-03-29 at 9 01 48 AM" src="https://user-images.githubusercontent.com/97116860/160656037-1cb9c233-f4e8-457a-a190-8372b986a14d.png">
<img width="1515" alt="Screen Shot 2022-03-29 at 8 25 13 AM" src="https://user-images.githubusercontent.com/97116860/160656077-3a8ac46d-808e-434f-821d-7278e7ac12c9.png">
.

**Comment by danahertzberg** [comment]
Remove caption from person views all-together
