### ISSUE TITLE
Event times do not display

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#1438]
## Problem/Motivation
Testing updates from QS 2.1.2 to 2.2.3

### Describe the bug
Times of events do not display

### To Reproduce

1. Update QS site to version 2.2.3
2. View existing event or create a new event with specific time (not all day)

## Proposed resolution
Investigate smart date/range or AP style contrib updates

### Expected behavior
Time appears before date

### On version 2.1.2
https://quickstart.arizona.edu/live-training
![image](https://user-images.githubusercontent.com/59745109/160897288-071dcbb1-7489-4d89-a518-6688744a917f.png)

### After 2.2.3 update (no time)
https://test-azs-quickstart.pantheonsite.io/live-training
![image](https://user-images.githubusercontent.com/59745109/160897138-b898528a-8d37-4331-8b63-fa883f9b0281.png)

**Comment by joeparsons** [comment]
These seems to be related to the Date AP Style module update we applied as part of #1258.

**Comment by joeparsons** [comment]
Changes made to Date AP Style module between 8.x-1.0 and 8.x-1.4:
https://git.drupalcode.org/project/date_ap_style/-/compare/8.x-1.0...8.x-1.4

**Comment by trackleft** [comment]
The issue is with this block of code 

https://git.drupalcode.org/project/date_ap_style/-/blob/8.x-1.x/src/ApStyleDateFormatter.php#L313-378

The else if should be on this condition https://git.drupalcode.org/project/date_ap_style/-/blob/8.x-1.x/src/ApStyleDateFormatter.php#L316

**Comment by trackleft** [comment]
The patch that worked https://www.drupal.org/files/issues/2021-05-24/3167284-support-smartdate-16.patch
