### ISSUE TITLE
Expand permissions for content admin role

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#1490]
## Motivation
In the ramp up to launch Arizona.edu in Quickstart 2 there were several key functions/permissions needed that currently cannot be addressed in the content admin role.

### Is your feature request related to a problem? Please describe.
Content admins need access to:

- Site Information (set homepage, 403, 404)
- Configure block css classes
- Tag Manager configuration (add Tag Manager ID)
- Reports (view reports related to search, 403, 404, etc)
- Metatag module configuration (configure defaults for different content types)
- Quick Node Clone

### Describe the solution you'd like
Expand content admin role to include permissions to the areas outlined above. 

### Roles and Permissions considerations
- Content administrator - would expand permissions

**Comment by smayden** [comment]
To add the site information, I think we will want to do something similar to what was done to add Site name to the Arizona Quickstart Settings under Configuration:

https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_core/src/Form/QuickstartCoreSettingsForm.php

(and I'll probably need help to do so...)

**Comment by smayden** [comment]
Also, curious people's opinions on adding permissions for Quick Node Clone.
-Content admins only? Or should Content editors also have access?
-Should it be for all 4 content types? (permissions are set per content type)
-How does it working setting permissions for a module that is disabled by default? Do the permissions just exist and then magically work when enabled? Or is this aspect of the ticket blocked by #1340

**Comment by trackleft** [comment]
> Also, curious people's opinions on adding permissions for Quick Node Clone. -Content admins only? Or should Content editors also have access? -Should it be for all 4 content types? (permissions are set per content type) -How does it working setting permissions for a module that is disabled by default? Do the permissions just exist and then magically work when enabled? Or is this aspect of the ticket blocked by #1340

 I think we can just include the per content type permissions that quickstart manages and leave the rest up to whoever manages the site.
