### ISSUE TITLE
asset-packagist is down

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#1491]
## Problem/Motivation
asset-packagist.org is currently down and all Quickstart composer builds are failing.

Seems to be a known issue and one that may not be resolved right away:
https://github.com/hiqdev/asset-packagist/issues/146

### Describe the bug
Anyone trying to build Quickstart with composer right now is running into errors like this one:

```
Error: curl error 28 while downloading https://asset-packagist.org/packages.json: Connection timed out after 10004 milliseconds
```

### To Reproduce
`composer install`

## Proposed resolution
Since it looks like connectitvity to asset-packagist may not be restored right away, we should probably look into mirroring the NPM / Bower packages we need on our own GitHub org temporarily or something.

### Expected behavior

`composer install` should work.

**Comment by SilverFire** [comment]
Asset-packagist is up, sorry for the troubles. You can find an explanation in the original issue: https://github.com/hiqdev/asset-packagist/issues/146#issuecomment-1106742011
