### ISSUE TITLE
Long-term solution to asset-packagist unavailability

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#1493]
## Problem/Motivation
We need a better long-term solution to #1491.

### Describe the bug
See #1491.

### To Reproduce
`composer install`

## Proposed resolution
Add individual npm/bower libraries as individual [`vcs` composer package repositories](https://getcomposer.org/doc/05-repositories.md#vcs)

We may also want fork/mirror the source code repos for each library in our own GitHub org so that we can add (or modify) a composer.json file to each library that sets the package `type` that we need.

### Expected behavior
`composer install` works.

**Comment by joeparsons** [comment]
## Source code repos for npm/bower packages currently used in Quickstart

- `bower-asset/chosen`: https://github.com/harvesthq/chosen-package
- `npm-asset/blazy`: https://github.com/dinbror/blazy
- `npm-asset/jquery-ui-touch-punch`: https://github.com/furf/jquery-ui-touch-punch
- `npm-asset/slick-carousel`: https://github.com/kenwheeler/slick

**Comment by mmunro-ltrr** [comment]
Taking a quick look at that unusual use of a Bower asset for `chosen`. This came from https://www.drupal.org/project/chosen/issues/3102250#comment-14006749 and was connected with the first use of asset-packagist in https://github.com/az-digital/az_quickstart/pull/561 but in the original Drupal issue thread there are some alternatives as well.

**Comment by joeparsons** [comment]
Access to asset-packagist has been fully restored.
