### ISSUE TITLE
Add new Feature display mode to News content type

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#1500]
Add new display mode to News to allow for manual embed of new style (view addressed separately)

**Comment by danahertzberg** [comment]
I believe these two files should add the new display mode.

- modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_feature.yml
- modules/custom/az_core/config/install/core.entity_view_mode.node.az_feature.yml

[news az_feature files.zip](https://github.com/az-digital/az_quickstart/files/8527187/news.az_feature.files.zip)

**Comment by cpoff** [comment]
I'll plug this in today. As I recall, on the original feature build we also updated the News view (views.view.az_news.yml). We'll find out soon enough.

**Comment by smayden** [comment]
I notice that the left column of the news feature is outdented compared to the title of the page.

![image](https://user-images.githubusercontent.com/10873398/165995739-c351cb5b-2fb6-488f-906f-a4e6ef7316da.png)

**Comment by trackleft** [comment]
> I notice that the left column of the news feature is outdented compared to the title of the page.

Good eye!

**Comment by trackleft** [comment]
Here is what the docs say about this https://digital.arizona.edu/arizona-bootstrap/docs/2.0/components/card/#horizontal
