### ISSUE TITLE
Migration Using GH Action does not work if there are videos on the site.

### ISSUE THREAD

**Issue by Carris-Toupin** [az-digital/az_quickstart#1514]
**Do not disclose security vulnerabilities here, please email us instead: 
az-digital-security@list.arizona.edu**

## Problem/Motivation
This is a blocker for using the GH Migration Action for many sites. The migration fails.
### Describe the bug
Migration fails during GH Action

### To Reproduce

Migrate a site with videos (especially on the front page) to see the errors.

## Proposed resolution
Change the script to be able to accommodate migration of videos. 

### Expected behavior

Videos should migrate, but will accept migration working for all other content, but videos do not migrate.

##  Screenshots
If applicable, add screenshots to help explain your problem. (Need a tool to share screenshots or screencasts as URLs? Try [monosnap](https://monosnap.com)

**Comment by trackleft** [comment]
Fixed #1673
