### ISSUE TITLE
Disable per user contact forms by default.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#152]
## User Story(s)
As a site builder, I do not typically enable per user contact forms.

**Comment by joshuasosa** [comment]
Are you thinking that just the individual user contact forms should be turned off, or all contact forms including the site-wide one? On UAQS, the contact module isn't enabled at all by default. As a site builder in my department, I at least prefer to keep that module off by default as most of the sites I build don't utilize it, and management doesn't want it.
