### ISSUE TITLE
Allow users to delete files - File Delete Module

### ISSUE THREAD

**Issue by natebyerley** [az-digital/az_quickstart#1527]
## Problem/Motivation

Certain files cannot be deleted - and are visible in the /admin/content/files, but not visible in /admin/content/media. Files directory does not allow any action to be taken on files, though files can be deleted within Media directory. Obviously confusing for clients, this also presents potential security/legal issue if a client receives a takedown request, a privacy request or a copyright infringement situation and can’t delete the file in a timely manner.

### Describe the bug

Files persist in /admin/content/files that cannot be viewed/edited/deleted in /admin/content/media.  Links to known issues:

- https://www.drupal.org/project/drupal/issues/2936175
- https://www.drupal.org/project/drupal/issues/3027324

## Proposed resolution

Add [File Delete (D8/D9)](https://www.drupal.org/project/file_delete) to Quickstart

NOTE: The one issue I see with implementing this module is that it only allows file delete if the file is used in 0 places.  If the file is in use, you cannot delete.  _How would client find uses of file on site if not known?_  Is it possible to have Drupal reveal *where* the file is used (not just the number of times it is used) on the site. 

### Expected behavior

Delete option for files on /admin/content/files

**Comment by joeparsons** [comment]
Actual core issue: https://www.drupal.org/node/3324270

This will be fixed in Drupal core as of 10.1.0.  See change record: https://www.drupal.org/node/3324270
