### ISSUE TITLE
Allow users to replace files, also rename files through re-upload

### ISSUE THREAD

**Issue by natebyerley** [az-digital/az_quickstart#1528]
## Motivation

To keep parity with features in D7/QS1, we should enable the Media Entity File Replace module by default: https://www.drupal.org/project/media_entity_file_replace.

This would enable users to replace a file without breaking the link to the file, and would (presumably) also provide the ability to 'rename' a file (while preserving embedded instances of the file on the site) by re-uploading the same (or a new) file with a different name.

### Is your feature request related to a problem? Please describe.

Problem is that users expect similar file management capability in D9 as D7, when the ability to replace and rename files in D9 is currently unavailable (was fairly easy in D7).

## Proposed Resolution

Enable Media Entity File Replace module by default in Quickstart 2 - https://www.drupal.org/project/media_entity_file_replace

### Roles and Permissions considerations

A clear and concise description of how each of the following roles would be impacted by this change:

- Anonymous user - N/A
- Authenticated user - N/A
- Content editor - would allow user to replace files
- Content administrator - would allow user to replace files
- Administrator - would allow user to replace files

**Comment by akslay** [comment]
> I'd love to see a PR for this

Here 'ya go! 😄 
https://github.com/az-digital/az_quickstart/pull/2311
