### ISSUE TITLE
Add LinkIt module - make linking to .pdfs easy for migration/content editors

### ISSUE THREAD

**Issue by natebyerley** [az-digital/az_quickstart#1529]
## Motivation

Linking to .pdfs or other files in text links/buttons is cumbersome - content editor must track down the link to the .pdf and then manually add that link.  Easy to grab the wrong link along the way.  Also, during migration .pdf links may break, and need to be made relative, this module would be a big improvement in content level user experience.

SASG team used this module frequently with their clients with rave reviews.

## Proposed Resolution

Enable LinkIt - https://www.drupal.org/project/linkit in Quickstart 2 by default

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Anonymous user - N/A
- Authenticated user - N/A
- Content editor - can use a searchbar to find a linked element
- Content administrator - can use a searchbar to find a linked element
- Administrator - can use a searchbar to find a linked element

**Comment by Carris-Toupin** [comment]
I am not sure if this module would also fix the issue of being unable to use the link field in a card for a PDF or file. The link field in a card will not accept a page path and gives an error that the user does not have permission to use that path.

**Comment by akslay** [comment]
I'm going to close this issue as a duplicate in favor of the original (#397 ), but have referenced it in the commends so we don't lose your comments.
