### ISSUE TITLE
Update quick_node_clone to 1.15 for SA-CONTRIB-2022-038

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1531]
## Problem/Motivation
A new security advisory was raised today that includes quick_node_clone

### Describe the bug
[SA-CONTRIB-2022-038](https://www.drupal.org/sa-contrib-2022-038
)

## Proposed resolution
We should update quick_node_clone to 1.15

**Comment by joeparsons** [comment]
This is good:
>This vulnerability is mitigated by the fact it only affects sites that also use the Groups contributed module.
