### ISSUE TITLE
Paragraph theme suggestions for custom themes don't work

### ISSUE THREAD

**Issue by joshuasosa** [az-digital/az_quickstart#1535]
## Problem/Motivation
My department uses a custom child theme based on az_barrio that resides in Drupal 9's web/themes directory. An attempt at overriding a paragraph theme suggestion by copying it over to the custom child theme results in the custom paragraph theme suggestion being ignored.

### Describe the bug
Paragraph theme suggestions are ignored due to a theme path check in az_paragraphs.module (az_paragraphs_theme_registry_alter()) that doesn't account for themes in the regular themes directory.

Of course, the project doesn't have to account for other themes outside the az_quickstart profile. But it's seems like a simple enough change to easily add support for this case.

## Proposed resolution
Change the pattern check from `'#/themes/#'` to `'#themes/#'` to resolve the issue.

Further, for a simple string check like this, regex shouldn't be used. It's recommended to use the faster strpos when regex isn't needed.
`strpos($theme_registry[$key]['theme path'], 'themes/') === false`

### Expected behavior
Paragraph theme suggestions should work in other themes (e.g., child themes).

**Comment by trackleft** [comment]
I think we should support this

**Comment by joeparsons** [comment]
Looks like the [`hook_theme_registry_alter()` implementation](https://github.com/az-digital/az_quickstart/blob/743b5177cbe480ed7f952a17b516ec9ac4f89ec7/modules/custom/az_alphabetical_listing/az_alphabetical_listing.module#L28) in the `az_alphabetical_listing` module is also affected by this.
