### ISSUE TITLE
Add IntelligenceBank integration to Text on Media

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#1550]
## Motivation
The University is rolling out a Digital Asset Manager called IntelligenceBank to make it easier for everyone at the university to share digital assets. Integrating this into Quickstart will make it accessible to hundreds of marketers and communicators across campus to help ensure successful adoption. 

This will also solve one of the biggest pain points for site owners: how to find good images to tell their stories.

## Proposed Resolution
The first step in adding this integration, is to make these assets available for Text on Media. As the element that has the most impact with images, it is a great place to start.

### Describe the solution you'd like
In the media field of the Text on Media, there should be two buttons as shown here:
<img width="582" alt="Screen Shot 2022-05-11 at 2 43 06 PM" src="https://user-images.githubusercontent.com/1509771/167952790-503a671f-d7d9-43f7-87d1-a74d2583c793.png">

Clicking into the Add Arizona Digital Assets button would pull up the full IntelligenceBank Asset Browser (for authenticated users) using the Entity Browser widget (configured at /admin/structure/paragraphs_type/az_text_media/form-display). 
<img width="1032" alt="Screen Shot 2022-05-11 at 5 50 37 PM" src="https://user-images.githubusercontent.com/1509771/167970375-adc58a07-bad2-4fae-9112-3838b2eb1d44.png">

If an image is selected from Arizona Digital Assets, this is how it would display on the form:
<img width="486" alt="Screen Shot 2022-05-11 at 2 46 16 PM" src="https://user-images.githubusercontent.com/1509771/167953153-16071631-65be-41eb-b878-8f44c2057fa2.png">

When selecting an image, there will be two options (Download and CDN), supporting each of these can be separate tickets.
After selecting an image, there will be a Settings screen that should _only_ have two options: Alternative Text and Title.

If an image is selected from Media, this is how it would display on the form:
<img width="394" alt="Screen Shot 2022-05-11 at 2 47 08 PM" src="https://user-images.githubusercontent.com/1509771/167953251-ea05c2ca-ee55-4611-8e51-334e14da82ea.png">

In either case, the alternative option is not displayed unless the image is removed.
The Text on Media should now display the same regardless of the image source.
Support for the "Media Aspect Ratio" space around content setting will require further discussion and can likely be a follow-up.

### Describe alternatives you've considered
The ideal experience would be to have the IntelligenceBank assets directly selectable using the core Media library, but we don't know the timeline for this to get implemented by their developers. (https://www.drupal.org/project/intelligencebank/issues/3177500) The current form of Media Library integration only displays assets that have already been imported through the Entity Browser. This alternative is our next best implementation.

### Roles and Permissions considerations
Same permissions as Media

**Comment by danahertzberg** [comment]
Look into this implementation for ONE Conference. If too difficult, circle back to CKEditor button (not ideal). Will have future related tickets.

**Comment by trackleft** [comment]
Since an intelligence bank integration could create media entities I think, if our initial MVP allowed adding images via the`/admin/content/media` and then use those media items within quickstart components.
