### ISSUE TITLE
AZ News: Re-add summary field custom link text on News items like on UAQS

### ISSUE THREAD

**Issue by joshuasosa** [az-digital/az_quickstart#1552]
## Motivation
On UA Quickstart, news items can set custom links with link text, which are used in places like news blocks and views. Custom links can still be used on AZ Quickstart, but the custom link text is missing as an option.

### Is your feature request related to a problem? Please describe.
Some sites I work with have cases where content maintainers want to link to external sources, including outside news articles or videos. Having the news block say "Read more" for all news items is insufficient to describe the link, especially in the case of linking to a video where it'd be more appropriate to have text say "Watch" or "Learn more."

The text should be customizable per node like it was in UA Quickstart, along with a sensible default.

Consider also re-adding "Open URL in a New Window" and "Custom link class" options like on UAQS.

### Describe the solution you'd like
Re-enable link text for the Summary field custom link on news items.

### Describe alternatives you've considered
Removing the link text altogether is an option that UANews uses for their news stories. Giving the option to add text is still preferred, but the default could optionally be to remove any text to be in line with UANews strategy.

### UA Quickstart News Summary Fields
![Web capture_12-5-2022_115137_uaqs ddev site](https://user-images.githubusercontent.com/4400438/168147751-7822add2-ce38-41e8-bedb-b9185ecf5577.jpeg)

### AZ Quickstart News Summary Fields
![image](https://user-images.githubusercontent.com/4400438/168147432-b6226146-4e39-40c3-aacf-46204a149e97.png)

Example of news blocks where custom link text is used:
https://president.arizona.edu/
https://science.arizona.edu/
https://strategicplan.arizona.edu/

**Comment by trackleft** [comment]
This has been blocked by
https://www.drupal.org/project/drupal/issues/2880632#comment-12324016

#1552 is a workaround I think we can live with.
