### ISSUE TITLE
Contextual links hidden/cut off when block is shorter than contextual links menu

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#157]
When attempting to edit or move and accordion block up or down within layout builder, when I click the edit icon, the contextual links menu is cut off.

<img width="1066" alt="Screen Shot 2020-04-20 at 10 02 01 AM" src="https://user-images.githubusercontent.com/1023167/79778797-30285b80-82ee-11ea-83c8-d37b593ee6ad.png">

This is the result of the z-index introduced on this line.
https://github.com/az-digital/az_quickstart/blob/441a61d8e0de1732e9ff0496a8831369a4fa8bb4/modules/custom/az_flexible_page/css/az_flexible_page_layout.css#L7-L10

**Comment by mschmeling14** [comment]
Closed. Work not performed. Decided to go a different direction.
