### ISSUE TITLE
Sidebar nav top margin calculation issue

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#1584]
- White space/top margin calculation issue on campus rec test site
- https://2-3-0-sasg-rec.pantheonsite.io/ 
- Needs more testing – apply to site with full-width content and sidebar already existing
- Ashley looking into new query fix

**Comment by bberndt-uaz** [comment]
@akslay @trackleft  I did a little testing at https://2-3-0-sasg-rec.pantheonsite.io/sports/intramural-sports/sport-offerings and it looks like the issue may be related to the bottomMargin value being used in the calculation of sidebarTopMargin. It seems that the bottomMargin string with "px" included needs to be converted to a number:

![image](https://user-images.githubusercontent.com/74572157/169597049-a54b755f-a42c-4c53-be4a-a1c9cfaa0001.png)

When parseFloat is used on bottomMargin and "px" is added as we set the value of sidebarTopMargin, the sidebar seems to be placed in the right spot:

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/74572157/169596854-b5c6d581-050e-4052-a10a-c2c918fb8c99.png">

**Comment by trackleft** [comment]
So I guess it was working with the demo content because those all have zero bottom margin?
