### ISSUE TITLE
Verify icons and carousel renderings are not an issue

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#1585]
## Verify icons rendering
- Apply 2.3.0-beta1 release to site with global footer already enabled
- Verify icons appear next to in connect menu

## Verify carousel rendering
- Apply 2.3.0-beta1 release to site with carousel already enabled
- Verify carousel appears on homepage

**Comment by trackleft** [comment]
It appears that the icon setting was unchecked in the theme
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/1023167/169611105-e9af9c36-c917-4871-9376-951b38d538a9.png">

**Comment by trackleft** [comment]
Now we know that that setting still works.

**Comment by trackleft** [comment]
We can close this now that we know this is not an issue
