### ISSUE TITLE
Move Person content type display back into UI-based management

### ISSUE THREAD

**Issue by joshuasosa** [az-digital/az_quickstart#1648]
## Motivation
Content types in Drupal come with the ability to manage displays through the UI. It is a core feature and part of Drupal's philosophy for site builders. 

At 2022's Driesnote, Drupal's vision is "Drupal is for ambitious site builders".
At 2021's Driesnote, he stated "Drupal should empower site builders who are less technical and want to build in the UI with a great UX."

Removing the ability for site builders to alter the Person content type displays makes it harder for them to make any meaningful changes to these displays.

### Is your feature request related to a problem? Please describe.
One of my department's sites requires an additional custom field on the Person content type: Publications. This field is separate from the other fields and cannot be included in another field (e.g., Bio). Adding the Publications custom field to the Person content type's default display is the usual method provided by Drupal to make such a custom field viewable. But the field does not show up. This issue is due to Person content type displays being explicitly overridden as twig files that don't account for custom fields that can be added through the UI.

Since it's possible to add customizations, the project should not make it harder on site builders and developers to implement new features that extend AZ Quickstart.

### Describe the solution you'd like
Remove the twig file overrides and re-add display customizations in the UI as was done in UA Quickstart.

## Additional context
Resolving this issue would negate the need for #721.

**Comment by danahertzberg** [comment]
This is definitely needed. Blocker for this issue would be figuring out a way to implement the mobile functionality via the UI. 

Currently the twig template duplicates the name and job title displays so they can be rendered above the image on mobile, but next to the image in the same column as the body on desktop. So we need that to be recreated without duplication somehow first.

**Comment by joshuasosa** [comment]
> Currently the twig template duplicates the name and job title displays so they can be rendered above the image on mobile, but next to the image in the same column as the body on desktop. So we need that to be recreated without duplication somehow first.

Here's a possible solution:
https://stackoverflow.com/questions/50141694/one-tall-div-next-to-two-shorter-divs-on-desktop-and-stacked-on-mobile-with-boot/50145570#50145570

Using demo content to try this solution:
```
<div class="row d-flex d-md-block">

  <div class="col-12 col-md-4 order-1 float-left">
    <div class="card mb-4 mb-md-0">
      <div>
        <figure style="max-width: 360px;">
          <div class="field field--name-field-media-az-image field--type-image field--label-visually_hidden">
            <div class="field__label visually-hidden">Image</div>
            <div class="field__item">  <img class="img-fluid image-style-az-small" src="/sites/default/files/styles/az_small/public/placeduck10.jpg?itok=WEjfO8cm" width="360" height="360" alt="Anders And" loading="lazy" typeof="foaf:Image">
            </div>
          </div>
        </figure>
      </div>
      <div class="card-body pb-0">
        <p>Communications W32</p>
      </div>
      <ul class="list-group list-group-flush border-0 py-3">
        <li class="list-group-item border-0 py-0"><a href="tel:031-667-1071">031-667-1071</a></li>
        <li class="list-group-item border-0 py-0"><a href="tel:053-246-1514">053-246-1514</a></li>
        <li class="list-group-item border-0 py-0">
          <div class="field field--name-field-az-email field--type-email field--label-hidden field__item"><a href="mailto:donald@email.arizona.edu">donald@email.arizona.edu</a></div>
        </li>
        <li class="list-group-item border-0 py-0"><a href="https://example.edu">Lab</a></li>
      </ul>
    </div>
  </div>

  <div class="col-12 col-md-4 order-0 float-left">
    <h1 class="text-blue my-0">Anders And</h1>
    <span class="h4 d-block mt-0">Professor</span>
    <span class="h4 d-block mt-0">Chair of Iconic Studies</span>
  </div>
  
  <div class="col-12 col-md-8 order-2 float-left">
    <div class="clearfix text-formatted field field--name-field-az-body field--type-text-long field--label-hidden field__item"><p>Enjoyed a lengthy Hollywood career before his current employment at the University of Arizona (joint with the University of Oregon).</p>
    </div>
    <h2 class="h3">Degrees</h2>
    <ul>
      <li>M.A. Communications, The University of Arizona</li>
    </ul>

    <a href="/person-categories/director" class="badge badge-light badge-link">Director</a>
    <a href="/person-categories-secondary/communications" class="badge badge-light badge-link">Communications</a>
  </div>
  
</div>
```

Another solution would be to install and use the EVA module and create an EVA-based view with a "custom text" view field. Fields could be added to the view, hidden, and arranged in the custom text field with field placeholders and HTML. Then on the content type display, fields would be removed from display and the EVA 'field' added, which contains the customizations. This solution I think is less ideal, but it at least puts everything back into the UI space and empowers site builders again.

**Comment by akslay** [comment]
Another possible solution would be to use the "smart title" for the desktop display version (hide on mobile), and then combine the "first name" and "last name" fields as plain text (no markup or using `spans`) in an `h1` that's hidden on desktop (or vise versa).
