### ISSUE TITLE
Add grayscale background colors to paragraphs

### ISSUE THREAD

**Issue by akslay** [az-digital/az_quickstart#1651]
_Originally posted by @akslay in https://github.com/az-digital/az_quickstart/issues/1650#issuecomment-1150357429_

We want the following neutral grays to be added as options to our paragraph items:
- Cards
- Text with Background
- Split Screen

```
        'bg-white' => $this->t('White'),
        'bg-gray-100' => $this->t('Gray 100'),
        'bg-gray-200' => $this->t('Gray 200'),
        'bg-gray-300' => $this->t('Gray 300'),
        'bg-gray-400' => $this->t('Gray 400'),
        'bg-gray-500' => $this->t('Gray 500'),
        'bg-gray-600' => $this->t('Gray 600'),
        'bg-gray-700' => $this->t('Gray 700'),
        'bg-gray-800' => $this->t('Gray 800'),
        'bg-gray-900' => $this->t('Gray 900'),
        'bg-black' => $this->t('Black'),
```

**Comment by tkmccarthy** [comment]
Just adding my comments from the meeting.

Very happy to see more light gray background color options! 

• I definitely think we should add 'gray 100, 200 and 300'.
• any of the medium grays can be fulfilled with Silver, Warm Gray or Cool Gray.
• and any dark grays/black feel a bit too far out of our brand color pallet. Those colors should fulfilled with either AZ Blue or Midnight.
