### ISSUE TITLE
New paragraph type for side-by-side Event and News views

### ISSUE THREAD

**Issue by natebyerley** [az-digital/az_quickstart#1663]
## Motivation
Motivated by azs-campushealth's desire for a side-by-side View (on desktop) of Events and News.  Dana has already done some work on this.

### Describe the solution you'd like
See screenshot examples from eller.arizona.edu and forthcoming site at health.arizona.edu

<img width="1400" alt="Screen Shot 2022-06-10 at 1 49 33 PM" src="https://user-images.githubusercontent.com/97116860/173148196-3d198ec9-bb4e-4589-99f0-941ab57abf13.png">

<img width="1409" alt="Screen Shot 2022-06-10 at 1 49 16 PM" src="https://user-images.githubusercontent.com/97116860/173148201-37dee675-df9f-428f-83e8-8b961aadc217.png">

#### Updated Requirements (July 13, 2023)

- Content editors should be able to add a paragraph type to a page or block that allows them to select two different views to be displayed in columns side-by-side on desktop.
- New views should be added to Quickstart for AZ News and AZ Event that are designed to be placed in the side-by-side view paragraph, with a uniform appearance (for example, with items having gray backgrounds or no background).
- Content editors should be able to choose arguments for the new News and Events views to restrict the display items by taxonomy ID (News Tags and Enterprise Attributes for news, Event Categories for events).
- The new paragraph type should:
  - Remove all buttons
  - Remove all titles
  - Add column title
  - Add optional column button

> #### Outdated Requirements (July 10, 2023)
> - Content editors should be able to add a single "News and Events" view block to a page or another block.
> - News items should be displayed on the left on desktop (first on mobile) using the Medium Media List content type display.
> - Event items should be displayed on the right on desktop (second on mobile) using the Row content type display.
> - Content editors should be able to choose multiple arguments for news and events to restrict the display items by taxonomy ID (News Tags and Enterprise Attributes for news, Event Categories for events).
> - Up to three items should be displayed for both news and events. The maximum number of items is not configurable. (This could be a future improvement.)

**Comment by danahertzberg** [comment]
## Existing views side-by-side
![image](https://github.com/az-digital/az_quickstart/assets/59745109/ccb8b961-144f-49f3-bb84-42f3e0faa548)

## Ideas for new paragraph type
- Remove all buttons
- Remove all titles
- Have uniform display (backgrounds)
- Add column title in paragraph type
- Add optional column button in paragraph type

**Comment by bberndt-uaz** [comment]
Updated the requirements in the issue description.
