### ISSUE TITLE
Improve default view of auto generated pages based on person taxonomy (/person-categories/*)

### ISSUE THREAD

**Issue by natebyerley** [az-digital/az_quickstart#1664]
**Do not disclose security vulnerabilities here, please email us instead: 
az-digital-security@list.arizona.edu**

## Motivation
Default person category page (not something user can change) has a primitive view of people.  For example: 

If you click on a person taxonomy category (grey alert styled words on the bottom of a person page)
> https://uair.arizona.edu/person/eddie-caratachea

You will land on a page that looks like this: 
> https://uair.arizona.edu/person-categories/leadership-team

## Proposed Resolution
Make this page (https://uair.arizona.edu/person-categories/leadership-team) look more like a Grid or Row view (i.e. https://uair.arizona.edu/content/staff-directory)

**Comment by bberndt-uaz** [comment]
@natebyerley Can this issue be closed now with the completion of [Configure how taxonomy term pages should display #2383](https://github.com/az-digital/az_quickstart/issues/2383) in Quickstart 2.7?

**Comment by natebyerley** [comment]
Looks great!
