### ISSUE TITLE
Update card options

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#1672]
## Motivation
Marketing & Brand Management would like to see more modern and updated styles of card.

## Proposed Resolution
- Update clickable card style to have a hover effect
   - If link field is populated
   - Hover styles applied to title and image
- Add card title style option per card
   - Check for media and populated title field

#### Add classes to [card template](https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_card/templates/az-card.html.twig)
- Add `card-title` class to title field on all cards
- Add `shadow` and `mb-4` class to wrapping card div on _clickable_ cards

#### Update card title hover effect on _clickable_ cards
Check if link URL field is populated
```
    .card:hover .card-title {
        text-decoration: underline;
    }
```
#### Add title style options dropdown at the card _deck_ level
Card title style
- Title within card (default)
   - Currently existing style
- Title on image
   - New option requiring new template
   - Example end result (`card-gradient-title` is a new class)
```
<div class="card bg-chili h-100 shadow">
   <div class="card border-0 overflow-hidden">
      <img class="card-img-top img-fluid image-style-az-card-image" src="">
      <div class="card-img-overlay p-0 d-flex flex-column">
         <h3 class="h5 bold mt-auto card-title bg-gradient-black text-white mb-0">Title no button</h3>
      </div>
   </div>
   <div class="card-body d-flex flex-column">
      <div class="card-text">
         <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore magna aliqua.</p>
      </div>
      <div class="mt-auto"><a href="/node" class="btn-block stretched-link"></a></div>
   </div>
</div>
   ```

#### Add new CSS
Check if link URL field and media field is populated
```
    .card:hover img {
        transform: scale(1.03);
        transition: ease .25s;
    }
    .card:hover .card-img-overlay h3 {
        text-decoration: underline;
    }
```

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Content editor

## Additional context
Example end result: https://live-dana-qs2.pantheonsite.io/cards-new-style
Blocked by https://github.com/az-digital/arizona-bootstrap/issues/493

**Comment by joshuasosa** [comment]
In the example where a clickable card's title appears below the image, maybe the title should be underlined to represent that it's a link like the other clickable card with title over the image does.

Title over image gets underlined on hover and shows it's a link:
![image](https://user-images.githubusercontent.com/4400438/173962179-77721e45-c395-4a0a-8241-d91990204984.png)

Title below image doesn't get underlined on hover:
![image](https://user-images.githubusercontent.com/4400438/173962246-d3742b69-efae-4cf3-afc3-6c77528ab539.png)

To me, it looks like it's inconsistent: either underline both titles or don't underline either title.

**Comment by danahertzberg** [comment]
Correct. The live mockup does not have the full styles in place. But the plan is to update card title hover effect on all clickable cards.
