### ISSUE TITLE
Replace all instances of drush command pm:enable with pm:install

### ISSUE THREAD

**Issue by bberndt-uaz** [az-digital/az_quickstart#1695]
Drush 11 renamed "pm:enable" to "pm:install" as described in [drush issue #4588](https://github.com/drush-ops/drush/issues/4588). The previous aliases were preserved, but to keep our code consistent and up-to-date with the latest version of drush, we should replace all instances of:

drush en
drush pm-enable
drush pm:enable

with:

drush install
drush pm-install
drush pm:install
 

## Conditions of satisfaction
- [ ] Should replace all instances of pm:enable commands with the new pm:install commands as indicated above.

**Comment by trackleft** [comment]
https://github.com/az-digital/az_quickstart/search?q=drush+en
https://github.com/az-digital/az_quickstart/search?q=drush+pm%3Aenable
https://github.com/az-digital/az_quickstart/search?q=drush+pm-enable
