### ISSUE TITLE
Update text on media transparent classes

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#1700]
We added `light` `dark` and `transparent` classes to Text on Media which are duplicative of the existing `bg-transparent-*` classes in Bootstrap. These should be updated and removed.

## Conditions of satisfaction
- [ ] Update [Light selection](https://github.com/az-digital/az_quickstart/blob/570872edfbd0a4d3268506cc42ed70a02a879623/modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php#L84) to use `bg-transparent-white` class
- [ ] Update [Dark selection](https://github.com/az-digital/az_quickstart/blob/570872edfbd0a4d3268506cc42ed70a02a879623/modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php#L85) to use `bg-transparent-black` class
- [ ] Update [Transparent selection](https://github.com/az-digital/az_quickstart/blob/570872edfbd0a4d3268506cc42ed70a02a879623/modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php#L86) to use `bg-transparent` class
- [ ] Remove custom CSS for `light` `dark` and `transparent` classes
   - [Remove these lines](https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_paragraphs/css/az_paragraphs_az_text_media.css#:~:text=%7D-,.dark%20%7B,%7D,-.az%2Dvideo)
- [ ] Add db update

**Comment by Jenish-d** [comment]
Hello, Can i work on this issue?
