### ISSUE TITLE
Restore layout of node creation pages to use the full width of the window

### ISSUE THREAD

**Issue by bberndt-uaz** [az-digital/az_quickstart#1716]
## Problem/Motivation
I noticed a change was introduced to the Quickstart repo in the past few weeks which alters the layout of the node creation pages at `/node/add/<content type>`. The new layout sets a maximum width on the main form fields and centers them, such that many users will now see a lot of white space on either side. The new layout also shrinks the width of the secondary region (containing the menu settings, summary fields, etc.).

### Describe the issue
As a result of code merged between 6/10 and 6/24, the HTML of the node creation pages has changed. Nested inside the `<div class="layout-region layout-region--node-main">` element, there is now a `<div class="layout-region__content">` container around the form field elements. This container has a max-width set along with auto left and right margins. The CSS styles applied to the layout-region--node-main element have changed also. The secondary sidebar region (with the menu settings, summary fields, etc.) also includes the layout-region__content container as a child and the sidebar is now more narrow than before.

### Additional context
@trackleft noted that this issue stems from an update to the Claro theme, as discussed in [this related Drupal issue](https://www.drupal.org/project/drupal/issues/3184667).

### To Reproduce

1. Go to the Add Content page at `/node/add`
2. Click on any of the content types
3. Observe the increased margins around the main form and the reduced width of the right sidebar

## Proposed resolution
To be determined

### Expected behavior

The main form fields should make better use of the available width and the sidebar width should not be reduced, given that many site builders may use it to add a node to a menu, enter summary text for the node, and so on.

##  Screenshots

Before:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/74572157/176782278-bd7beb86-4096-41f8-b454-1d41b83b8cc6.png">

After:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/74572157/176782748-a3f603db-b92e-40be-8b29-31e8c2ae0906.png">

**Comment by joeparsons** [comment]
FWIW, we used to include a [Drupal core patch for that d.o. issue](https://www.drupal.org/project/drupal/issues/3184667#comment-13940168) in Quickstart but it was removed as part of #1573 because it looked like the patch had been committed to Drupal core as of 9.4.0.

**Comment by danahertzberg** [comment]
Override this max-width
```
@media screen and (min-width: 61rem)
.layout-region--node-main .layout-region__content, .layout-region--node-footer .layout-region__content {
    max-width: 100%;
    margin-right: auto;
    margin-left: auto;
}
```
