### ISSUE TITLE
2.4.x Documentation

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#1722]
- [x] Add documentation for

- [Intelligence bank](https://github.com/az-digital/az_quickstart/pull/1592)
- [Courses content type](https://github.com/az-digital/az_quickstart/pull/1687)
- [Split screen paragraph type](https://github.com/az-digital/az_quickstart/pull/1650)
- [Unversal Analytics dashboard](https://github.com/az-digital/az_quickstart/issues/1118)

- [x] Update documentation for:

- Cards
- Text on Media

- [x] Content Admin Newsletter announcements for:

- New styles available for Cards and Text on Media
- Intelligence Bank
- Courses
- Split Screen
- Analytics Dashboard

- [ ] Developer newsletter announcements for:

- Apply distro updates
- Drupal 9.4
- Courses content type
- Front end visual changes (clickable cards, text on media bottom)
- Admin interface changes (if there are any. Paragraph buttons?)
     - Quickstart menu

**Comment by camikazegreen** [comment]
Intelligence Bank: https://quickstart.arizona.edu/create-content/images-videos-and-files/digital-asset-manager (also sent to Stephanie Cunningham for additional feedback)
Courses: https://quickstart.arizona.edu/create-content/adding-courses
Split Screen: https://quickstart.arizona.edu/page-elements/split-screen
Universal Analytics Dashboard: https://quickstart.arizona.edu/site-admin/analytics (Also sent to Catherine Gustafson for additional feedback)

Text on Media: https://quickstart.arizona.edu/page-elements/text-media

**Comment by trackleft** [comment]
Pantheon upstream changes:
Example: Quicksilver integration (so distribution updates are applied without having to manually update) https://github.com/az-digital/az-quickstart-pantheon/blob/master/settings-examples/pantheon.example.yml
