### ISSUE TITLE
Course Batched Import Speed

### ISSUE THREAD

**Issue by tadean** [az-digital/az_quickstart#1724]
### Describe the bug

Import of courses via the `Import Courses` button is significantly slower than the equivalent drush command. This seems to be occurring because a multi-url data parser migration does a lot of re-downloading previous URLs to figure out its count during the batch. This creates an exponential slowdown in the migration speed from the import form.

This could probably use some re-engineering but would require some investigation into `migrate_plus` to figure out why the excess downloads are happening.

**Comment by joeparsons** [comment]
Related Migrate Tools module issue:
https://www.drupal.org/project/migrate_tools/issues/3327628
