### ISSUE TITLE
AZ Barrio PHPCS Cleanup

### ISSUE THREAD

**Issue by tadean** [az-digital/az_quickstart#174]
## Conditions of satisfaction
`az_barrio` presently has a few warnings from `phpcs` that are being thrown, though none is severe enough to actually cause an error. It would be good to resolve these existing warnings (the warnings involved are largely use of `==` over `===` and line length warnings)

**Comment by joshuasosa** [comment]
This issue wasn't completely resolved with #19 

These warnings still exist:

> 5FILE: ...les/custom/az_quickstart/themes/custom/az_barrio/az_barrio.theme
6----------------------------------------------------------------------
7FOUND 0 ERRORS AND 3 WARNINGS AFFECTING 1 LINE
8----------------------------------------------------------------------
9 8 | WARNING | Possible RFI detected with dirname on include_once
10 8 | WARNING | Filesystem function dirname() detected with dynamic
11   |         | parameter
12 8 | WARNING | Possible RFI detected with __FILE__ on include_once
13----------------------------------------------------------------------
14
15
16FILE: .../custom/az_quickstart/themes/custom/az_barrio/theme-settings.php
17----------------------------------------------------------------------
18FOUND 0 ERRORS AND 3 WARNINGS AFFECTING 1 LINE
19----------------------------------------------------------------------
20 10 | WARNING | Possible RFI detected with dirname on include_once
21 10 | WARNING | Filesystem function dirname() detected with dynamic
22    |         | parameter
23 10 | WARNING | Possible RFI detected with __FILE__ on include_once
24----------------------------------------------------------------------
25
26
27FILE: ...ckstart/modules/custom/az_core/src/QuickstartConfigInstaller.php
28----------------------------------------------------------------------
29FOUND 0 ERRORS AND 3 WARNINGS AFFECTING 3 LINES
30----------------------------------------------------------------------
31  33 | WARNING | Filesystem function is_dir() detected with dynamic
32     |         | parameter
33 102 | WARNING | Filesystem function file_exists() detected with
34     |         | dynamic parameter
35 104 | WARNING | Filesystem function file_get_contents() detected
36     |         | with dynamic parameter
37----------------------------------------------------------------------

**Comment by davearch** [comment]
Hello can I take a stab at this issue? Also what is the specific command I should use to test everything?

I ran `lando phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md,yml web/profiles/custom/az_quickstart/themes/custom/az_barrio`

It also gives me a bunch of line ending errors but I assume that's because I'm on Windows.

**Comment by tadean** [comment]
`lando phpcs` by itself is the normal command - the defaults come from [this file](https://github.com/az-digital/az-quickstart-scaffolding/blob/master/phpcs.xml.dist) in the scaffolding.

If you get any warnings about markdown files in `node_modules` you may need a more recent copy of that file. We recently merged a [pull request](https://github.com/az-digital/az-quickstart-scaffolding/pull/20) adding an ignore for that directory.
