### ISSUE TITLE
Fix block embeds

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#1743]
Can't embed blocks in a text area

**Comment by camikazegreen** [comment]
Console output when attempting to embed blocks:

<img width="884" alt="Screen Shot 2022-07-12 at 11 44 06 AM" src="https://user-images.githubusercontent.com/1509771/178570927-930f6f98-e191-4a19-9b26-54827fd6c2db.png">

Uncaught TypeError: contentRegion is null
    pushSidebarsDown az_paragraphs_full_width.js:15
    attach az_paragraphs_full_width.js:50
    attachBehaviors drupal.js:27
    attachBehaviors drupal.js:24
    error ajax.js:510
    complete ajax.js:247
    jQuery 5

[az_paragraphs_full_width.js:15:32](https://240-beta2-azs-quickstart.pantheonsite.io/profiles/custom/az_quickstart/modules/custom/az_paragraphs/js/az_paragraphs_full_width.js?v=9.4.2)
Uncaught 
Object { message: "\nAn AJAX HTTP error occurred.\nHTTP Result Code: 500\nDebugging information follows.\nPath: /entity-embed/dialog/az_standard/az_embed_content_block?_wrapper_format=drupal_modal&ajax_form=1\nStatusText: Internal Server Error\nResponseText: The website encountered an unexpected error. Please try again later.", name: "AjaxError", stack: "@https://240-beta2-azs-quickstart.pantheonsite.io/core/misc/ajax.js?v=9.4.2:110:32\n@https://240-beta2-azs-quickstart.pantheonsite.io/core/misc/ajax.js?v=9.4.2:676:3\n" }
[ajax.js:110:32](https://240-beta2-azs-quickstart.pantheonsite.io/core/misc/ajax.js?v=9.4.2)

Uncaught TypeError: $.fn.button.noConflict is not a function
    attach button-no-conflict.js:11
    attachBehaviors drupal.js:27
    attachBehaviors drupal.js:24
    error ajax.js:510
    complete ajax.js:247
    jQuery 5
