### ISSUE TITLE
Unified Web Experience Navigation Questions to research

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#1762]
### Per site
- What is the content editing UX like? What could be improved?
- How do end users interact with the sidebar menu? On mobile?
- How do end users interact with the off-canvas menu on mobile?
- Should header region take up less space on mobile? Do end-users have issues with this?
- Should header region take up less space on desktop/tablet? Do end-users have concerns about this?
- How do end-users interact with non-nav navigational content? Like cards?
- How do end-users interact with breadcrumbs?

### Between sites
- How does each site fit into the overall institutions navigation?
    - Hierarchy of sites/navigation - do we need a visual difference?
- How does the end user navigate between university websites? Is it confusing? Is it recognizable?
- What are the different end-user path experiences based on traffic source/origin? 
    - Should we address SEO?

## Content-editor
- Should card previews be rendered accurately, but interrupt link behavior? Or not be a link at all which will affect accurate rendering?
- How do content editors present navigational content? Like with cards? Rely on navs?
- How do content editors use/view breadcrumbs?
- How should a content-editor use the GA dashboard to inform nav structure?

## Peer research
- How do peer universities display navigational elements?

**Comment by danahertzberg** [comment]
Workshop 7/27/2022
- Narrow scope of this release to the "per-site" section to improve

**Comment by danahertzberg** [comment]
* https://www.uxbooth.com/articles/the-rules-for-modern-navigation/
	* 2017 article
	* People rely on navigation first because it’s easier and faster
	* [ ] Prioritize consistency
	* [ ] Design clear interactions
	* [ ] Avoid deep navigation
	* [X] Design for responsive compatibility
	* [ ] Use location indicators in the menu
* [Stop Using Secondary Navigation Bars… Maybe!](https://boagworld.com/design/secondary-navigation/)
	* 2019 article
	* “As long as people feel they are progressing towards their goal, they are less concerned with the number of clicks it takes to get there.”
	* “It doesn’t matter how many times I have to click, as long as each click is a mindless, unambiguous choice.”


![Image](https://user-images.githubusercontent.com/59745109/181368874-f0095245-77c0-43d2-949d-6f8c29da7907.png)


* [Testing the Three-Click Rule — 			UX Articles by UIE](https://articles.uie.com/three_click_rule/)
	* 3-click rule is a myth
* https://uxdesign.cc/5-navigation-tips-to-improve-ux-of-your-product-service-f64840ef2f4c
	* Making them more visible to the end user
		*  Start Using Breadcrumbs
		* Avoid using tiny menus (or menu icons) on large screens
		* Always try to put menus in familiar locations
		* Make menu links look interactive
		* Ensure that your menus have enough visual weight
		* Use link text colors that contrast with the background color
	* Coordinate Menus with User Tasks
	* Unique Visual Design for Each Level
	* Use Location Indicators
	* Different Navigation for Mobile vs. Desktop

**Comment by akslay** [comment]
https://uiowa.edu/admissions/cost-and-aid

- Used mobile nav on desktop
- Includes secondary nav items in a full-width banner under the page title. Collapses on mobile.
- Includes breadcrumbs
- Sticky header on scroll. Hides on downward scroll and re-appears on upwards scroll. Don't have to scroll all the way back up to return to the main nav.
- Works fell since each page has a visual image to split up the menus, but probably wouldn't work as well for our sites (as they are currently designed) since we don't have that visual aspect to our header and title areas.

https://www.rutgers.edu/academics/explore-undergraduate-programs

- Clean implementation of mega menus

**Comment by cpoff** [comment]
[https://missouri.edu/academics](https://missouri.edu/academics)

- Just one level of menu, with secondary items forced into cards/content on the page.
- Downsize is that there's no way to directly navigate to a sub page via nav. Can get awfully scroll-y.

**Comment by bberndt-uaz** [comment]
Purdue:
 - On the [main site](https://www.purdue.edu/), there are two off-canvas nav menus on mobile
 - Sidebars go below the content on mobile ([primary sidebar example](https://www.purdue.edu/purdue/about/colleges_schools.php), [secondary sidebar example](https://www.admissions.purdue.edu/studentlife/arts.php))
 - Breadcrumbs row has a gray background, but the style changes on different pages ([example 1](https://www.purdue.edu/purdue/about/colleges_schools.php), [example 2](https://www.purdue.edu/learningcommunities/profiles/education/index.html))

Ohio State:
 - On the [main site](https://www.osu.edu/), the top banner row changes from text links to icons on mobile
 - Sidebars go above the content on mobile ([example](http://undergrad.osu.edu/life-on-campus/find-support))
 - Breadcrumbs in different styles ([example 1](http://undergrad.osu.edu/life-on-campus/find-support), [example 2](https://www.osu.edu/alumni/communities/clubs-and-societies/))
 - [Dark mode option in the footer](https://studentlife.osu.edu/)
