### ISSUE TITLE
Color module deprecated in Drupal 9.4, but in use as a dependency of environment indicator module.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1801]
## Problem/Motivation
Why the issue was filed, steps to reproduce the problem, etc.
![image](https://user-images.githubusercontent.com/1023167/182691118-949ef9e1-4779-4acf-9136-b77c8a3ba7a5.png)

### Describe the bug
Not exactly a bug, but we do need to resolve this before upgrading to Drupal 10.

Adding the https://www.drupal.org/project/color module could resolve this issue.

There is also a ticket open on Drupal.org to remove the dependency https://www.drupal.org/project/environment_indicator/issues/3284389

**Comment by joeparsons** [comment]
The latest version of the Environment Indicator module fixes this:
https://www.drupal.org/project/environment_indicator/releases/4.0.7
