### ISSUE TITLE
Update global.arizona.edu to international.arizona.edu  everywhere.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1837]
## Conditions of satisfaction
All instances of global.arizona.edu should be changed to international.arizona.edu 

Possibly a database update should be added to perform a string replacement.

**Comment by trackleft** [comment]
Drush search and replace issue for D8 https://github.com/az-digital/az_quickstart/issues/1837

**Comment by joeparsons** [comment]
We've made similar updates to the Global Footer in Quickstart 1 a couple of times.  These are the DB updates we came up with for those:
https://bitbucket.org/ua_drupal/ua_quickstart/src/c616fc7c214978d466d36e1454c899025ceb3846/modules/custom/uaqs_navigation/uaqs_navigation_global_footer/uaqs_navigation_global_footer.install#lines-83:146
