### ISSUE TITLE
GitHub Actions workflow for updating dev/demonstration server (kitten replacement)

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#184]
## User Story(s)

As an Arizona Digital team member, I'd like to have access to a website that always has the latest dev version of Quickstart deployed to it for reference (i.e. Kitten 2.0)
…

## Conditions of satisfaction
- [ ] Should provide a GitHub Actions workflow for updating a dev site (probably a Pantheon sandbox site) each time code is merged into the master branch

**Comment by danahertzberg** [comment]
Campus Web Services will pay for a paid plan on Pantheon for each of the kitten sites (D7 and D9)
