### ISSUE TITLE
Update default breadcrumb configuration for better user experience

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#1864]
## Motivation
We are working on improving our breadcrumb navigation to be more useful to site visitors.

### Is your feature request related to a problem? Please describe.
The current configuration for breadcrumbs can be confusing. Breadcrumbs only show up on third level pages or deeper. On third level pages there will only be one link present (the parent of the current page), and without any "trail", it isn't obvious that it is a breadcrumb menu and only looks like a floating word out of place.

### Describe the solution you'd like
Have breadcrumbs excluded from the home page. 
Have the breadcrumb trail always include the Home link. 
Include the current page (unclickable)

### Describe alternatives you've considered
Bob Liu from Libraries has additional UX feedback based on what they've done.

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Anonymous user: Should be able to view the breadcrumbs
- Content administrator: Should be able to override the breadcrumb settings.

**Comment by bearwithbob** [comment]
Here's a screenshot of UA Libraries' current Easy Breadcrumbs configuration:

![ua-libraries-easy-breadcrumbs-config](https://user-images.githubusercontent.com/47095448/185692503-58318e4d-5860-481c-b8f1-e55b38411a76.png)

And a screenshot of what the breadcrumbs look like on a page:

<img width="434" alt="Screen Shot 2022-08-19 at 12 26 27 PM" src="https://user-images.githubusercontent.com/47095448/185692712-96d3d611-41fc-4995-afa4-0aa3b7243ccd.png">
