### ISSUE TITLE
Add documentation to quickstart.arizona.edu about Linkit.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1879]
- [ ] Update [Link Text to a PDF page](https://quickstart.arizona.edu/create-content/editor-toolbar/link-text-pdf)
- [ ] Add news article about the change so that we can link to it in the newsletter if appropriate.

**Comment by akslay** [comment]
Looks like the documentation has already been updated here: https://quickstart.arizona.edu/create-content/editor-toolbar/edit-links

I'll go ahead and close this issue.
