### ISSUE TITLE
Audit remaining UA Zen functions for AZ Barrio functionality

### ISSUE THREAD

**Issue by tadean** [az-digital/az_quickstart#188]
## What is the problem that we want to solve?
Analysis of functions that were in UA Zen to determine if there is additional functionality that may need to be ported to AZ Barrio for functionality parity.

Some functionality has already been ported from UA Zen to AZ Barrio; remaining theme functions will fall into one of two categories:

- need to be implemented in a D8 context for AZ Barrio
- other functions that are no longer necessary due to either no longer being desired, or differences in theme structure from D7 to D8

 [Link to analysis spreadsheet](https://docs.google.com/spreadsheets/d/1TsWrHgcirEwNvofCqgu2YbdBGPwTfnTwXhqLXPVy14U/edit?usp=sharing )

## Conditions of satisfaction
- [ ] All UA Zen theme functions are identified as being either necessary or no longer necessary

**Comment by camikazegreen** [comment]
We are going to approach this work similar to how we are managing the D7 Modules to D8/D9 transition: as we approach adding functionality to QS 2.0 we will review how we did it in QS 1.0 and continue to use this analysis spreadsheet as a resource throughout that process.
