### ISSUE TITLE
Add Workbench Access for section editing access control

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1908]
## Motivation
As a site owner, I would like to delegate specific sections of my site to be edited by people that are not me or a member of my trusted staff.

[README for workbench_access ](https://git.drupalcode.org/project/workbench_access/-/blob/2.x/README.md)

### Is your feature request related to a problem? Please describe.
Keeping in mind that user access control can be a challenge at such a fluid institution where people come and go and switch departments, or graduate, it would be nice to be able to do this sort of thing on a limited basis.

It might also be to our benefit to create a rubrik for managing users who have section editing access, and maybe a boilerplate workflow and access request form to hand off to clients that find this useful.

## Proposed Resolution
Add workbench_access module and provide sane defaults, plus mimimal documentation for common use-cases.

### Describe alternatives you've considered
[organic groups](https://www.drupal.org/project/og)
[group](https://www.drupal.org/project/group)
[content access](https://www.drupal.org/project/content_access)
[Taxonomy Access Control Lite](https://www.drupal.org/project/tac_lite)

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- User administrator (Can grant users with the section editor role)
- Section editor (A new role created)
- Content administrator (Determines the sections that are under access control)

**Comment by djcelaya** [comment]
This addition will be much utilized over here at UAHS when we finally get to QS2! Our particular use case is that we have multiple writers in our office that work on different kinds of news content. Each writer or group of writers should only be able to edit and publish certain kinds of news content. Additionally, the supervisor of the writer and/or other stakeholders often have to review and approve the draft before it is published.

**Comment by cpoff** [comment]
Discussion in the [associated PR](https://github.com/az-digital/az_quickstart/pull/1973) now revolves around the default permission settings.

**Comment by cpoff** [comment]
Section Editor role added, and assigned 'Bypass Workbench Access Permissions' as the default.
