### ISSUE TITLE
az_paragraph_full_width_media_row migration has no default set for view mode

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1924]
## Problem/Motivation
Migrating uaqs_full_width_media_row paragraphs from a QS1 site results in an error.

### Describe the bug
 `az_paragraph_full_width_media_row:view_mode_processed: No static mapping found for '''' and no default value provided for destination 'view_mode_processed'.  `

**Comment by joeparsons** [comment]
Is this a duplicate of #1915?

**Comment by joeparsons** [comment]
Duplicate of #1915.
