### ISSUE TITLE
Update AZ Barrio's search box icon to use Material Design

### ISSUE THREAD

**Issue by joshuasosa** [az-digital/az_quickstart#193]
Following #50, @akslay commented that the search box icon should be replaced with a Material Design icon.

## Conditions of satisfaction
- [x] Add a reference to Material Icon's stylesheet in the theme.
- [x] Replace the search box icon with Material Design's [search](https://material.io/resources/icons/?icon=search&style=sharp) icon.
- [ ] Remove search-chili.svg from theme.

**Comment by trackleft** [comment]
This has been completed as of https://github.com/az-digital/az_quickstart/pull/218
