### ISSUE TITLE
Migrate az_standard text format to CKEditor5

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1987]
## Motivation

Drupal 10 removes CKEditor 4 from core

### Describe the solution you'd like
Update config for az_standard to use CKEditor 5 without data loss.

### Describe alternatives you've considered
Use ckeditor contrib module

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Anonymous user
- Authenticated user
- Content editor
- Content administrator
- Administrator

## Additional context

- https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/migration-from-ckeditor-4.html
- https://www.drupal.org/docs/core-modules-and-themes/core-modules/ckeditor-5-module/plugin-and-contrib-module-development

**Comment by joeparsons** [comment]
Created a work-in-progress branch and local development site where I added the latest CKeditor5 patches for the [Embed](https://www.drupal.org/project/embed/issues/3309747) and [Entity Embed](https://www.drupal.org/project/entity_embed/issues/3272732) modules.  After installing the CKeditor 5, I saw these errors in the status report:
<img width="1103" alt="Screenshot 2023-07-18 at 10 45 25 AM" src="https://github.com/az-digital/az_quickstart/assets/471936/16def426-b7b5-4456-8901-5f754e28153f">

I replaced the PNG icons with SVG versions in my branch for our custom buttons but replacing icon for the button provided by the entity_embed module will require a change to this method in the module:
https://git.drupalcode.org/project/entity_embed/-/blob/8.x-1.x/src/Plugin/EmbedType/Entity.php#L284-289

After changing the editor for the standard format from CKEditor to CKEditor5, I saw these messages:
<img width="1114" alt="Screenshot 2023-07-18 at 10 47 04 AM" src="https://github.com/az-digital/az_quickstart/assets/471936/fcf7f12e-0702-4ff7-beb6-c69ae3d21afd">

## Detailed log messages

### Warnings
```
The CKEditor 4 button bs_grid does not have a known upgrade path. If it allowed editing markup, then you can do so now through the Source Editing functionality.
```

```
The bs_grid plugin settings do not have a known upgrade path.
```

### Notices
```
The CKEditor 5 migration enabled the following plugins to support tags that are allowed by the Standard text format: Code (for tags: <code>) Code Block (for tags: <pre>) Bootstrap Grid (for tags: <div>). The text format must be saved to make these changes active.
```

```
The following tags were permitted by the Standard text format's filter configuration, but no plugin was available that supports them. To ensure the tags remain supported by this text format, the following were added to the Source Editing plugin's Manually editable HTML tags: <abbr> <address> <cite> <dl> <dt> <dd>. The text format must be saved to make these changes active.
```

```
As part of migrating to CKEditor 5, it was found that the Standard text format's HTML filters includes plugins that support the following tags, but not some of their attributes. To ensure these attributes remain supported, the following were added to the Source Editing plugin's Manually editable HTML tags: <div name id> <span name id class> <img src alt data-entity-type data-entity-uuid> <footer class> <blockquote class> <ul type class> <ol type class> <li class> <h1 name id class> <h2 name id class> <h3 name id class> <h4 name id class> <h5 name id class> <h6 name id class> <table class> <tbody class> <thead class> <tfoot class> <th scope class> <td class> <tr colspan rowspan class> <hr class> <a target name id title class> <p class> <drupal-media title data-caption> <drupal-entity data-entity-type data-embed-button>. The text format must be saved to make these changes active.
```

I think we may want to open an issue / submit a patch on the CKEditor Bootstrap grid module about adding a `\Drupal\ckeditor5\Annotation\CKEditor4To5Upgrade plugin` that extends `\Drupal\ckeditor5\Plugin\CKEditor4To5UpgradePluginInterface` to resolve some of these issues (see https://www.drupal.org/docs/core-modules-and-themes/core-modules/ckeditor-5-module/upgrading-modules-extending-ckeditor-4-to-support-ckeditor-5)

**Comment by joeparsons** [comment]
We are definitely affected by this issue:
https://www.drupal.org/project/drupal/issues/3332416
