### ISSUE TITLE
Add User Story, Task & Spike templates to github issues

### ISSUE THREAD

**Issue by barrettbaffert** [az-digital/az_quickstart#20]
**Do not disclose security vulnerabilities here, please email us instead: 
az-digital-security@list.arizona.edu**

**Is your feature request related to a problem? Please describe.**
The current issue types of Feature Request and Bug Report aren't suitable for all tasks. 

**Describe the solution you'd like**
Add issue templates for User Story, Task, and Spike to match our workflow from JIRA.

**Comment by trackleft** [comment]
This was merged https://github.com/az-digital/az_quickstart/pull/21
