### ISSUE TITLE
Style utility links using Arizona Bootstrap classes or components

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#201]
## Motivation
The utility links added in #172 & #198 are not yet styled in same way as the utility links menu provided by UA Quickstart/UA Zen.

### Describe the solution you'd like
Attendees of the 2020-05-08 AZ Digital meeting decided that the undocumented utility links CSS styles provided by UA Bootstrap should be adapted into a reusable component or class in Arizona Bootstrap (https://github.com/az-digital/arizona-bootstrap/issues/81).  Once the utility link styling is available in Arizona Bootstrap, AZ Barrio should be updated to apply the necessary Bootstrap classes to the utility links menu.

**Comment by akslay** [comment]
@joeparsons I think this issue can be closed (: These 2 items have been merged:
- https://github.com/az-digital/arizona-bootstrap/issues/81
- https://github.com/az-digital/az_quickstart/issues/228

**Comment by joeparsons** [comment]
Thanks all
