### ISSUE TITLE
Update draggableviews to 2.1.1

### ISSUE THREAD

**Issue by joshuasosa** [az-digital/az_quickstart#2016]
[DraggableViews 2.1.1](https://www.drupal.org/project/draggableviews/releases/2.1.1) was released October 21. The current AZQS version used is 2.0.1 which is marked as "Not supported!" The included AZQS version should be updated to the latest supported version.

**Comment by joeparsons** [comment]
I updated the automatic dependabot PR to remove the existing patch we were using for draggableviews (which is included in the latest release).  Ready for review: #2021
