### ISSUE TITLE
Replicate uaqs_list_assets drush command for Quickstart 2

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#2054]
## Motivation
In an effort to make reporting site metrics easier we would like a way to easily list entity asset counts on sites using Quickstart 2.

## Proposed Resolution
Add a list assets drush command to list QS2 assets.

## Additional context
See https://bitbucket.org/ua_drupal/ua_quickstart/src/3bf9f9b4116144655178dde6c21c572273686411/modules/custom/uaqs_core/uaqs_core.drush.inc#lines-38:73

**Comment by danahertzberg** [comment]
https://github.com/az-digital/az_quickstart/tree/9f27646e012bde7535baef759feb1947e81f0623/modules/custom/az_core/src/Drush/Commands
