### ISSUE TITLE
Create initial design mockups for new mobile nav

### ISSUE THREAD

**Issue by bourgeoy** [az-digital/az_quickstart#207]
## Motivation
current mobile nav impossible to use 

### Is your feature request related to a problem? Please describe.
The mobile navigation needs to be updated/go through a design revision.

## Proposed Resolution
as much as possible add helper classes to AZ Bootstrap 

### Describe the solution you'd like
Improve the mobile navigation look and functionality for D8

## Additional context
Design comps are being reviewed by marketing

**Comment by camikazegreen** [comment]
Mockups have been completed and passed over to Marketing and Communications for User Testing and Review.
