### ISSUE TITLE
Update dropdown menu text to be white instead of red.

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#209]
## Motivation
Current Quickstart 1.0 menus have white text and no underline on the dropdown menus.

### Is your feature request related to a problem? Please describe.
We are trying to match parity of the existing menus.

### Describe the solution you'd like
Normal elements on dropdown menus should have white text and no underline.
Active elements on dropdown menus should be inverted with white backgrounds and Arizona Blue text.

<img width="462" alt="Screen Shot 2020-05-20 at 3 52 42 PM" src="https://user-images.githubusercontent.com/1509771/82505529-d2389080-9ab2-11ea-94a8-6c268a031b31.png">

**Comment by joshuasosa** [comment]
On UA Quickstart, these dropdown menus are styled in UA Bootstrap. In keeping parity, should menu styles be in AZ Bootstrap or in AZ Quickstart? If Bootstrap, then should this issue be moved over to arizona-bootstrap?

**Comment by camikazegreen** [comment]
@joshuasosa We are trying to make sure that all necessary styles or classes are available in Arizona Bootstrap so that it is easier for non-Drupal users to make similar menus. 
I agree that the issue should be moved over to arizona-bootstrap.

**Comment by camikazegreen** [comment]
Issue moved to [az-digital/arizona-bootstrap #86](https://github.com/az-digital/arizona-bootstrap/issues/86) via [**ZenHub**](https://www.zenhub.com/)

**Comment by trackleft** [comment]
I agree with @joshuasosa all of the menu updates we do should be added to arizona-bootstrap first, then to Quickstart.
