### ISSUE TITLE
Add an optional thumbnail image field to AZ News, AZ Event

### ISSUE THREAD

**Issue by bberndt-uaz** [az-digital/az_quickstart#2091]
## Motivation
The AZ News and AZ Event content types in Quickstart 2 should allow site editors to have more control over the image(s) used for these nodes. In Quickstart 2, AZ News has a single "Photo" field and AZ Event has a single "Event Photos" field. In contrast, the current Quickstart 1 [eller.arizona.edu](https://www.eller.arizona.edu) site uses a custom news content type that has two image fields: a "News Photos" field which contains images to be shown on the news page itself and a "Thumbnail Only Photo" field containing an image to be used with teaser displays of the news nodes. This provides site editors with greater flexibility in deciding how these nodes should appear.

The Quickstart 1 [news.arizona.edu](https://news.arizona.edu) site also has two image fields: "Featured Photo" and "Summary photo". When the main "Featured Photo" field is populated and the thumbnail "Summary photo" field is left empty, the "Featured Photo" field is automatically added to the "Summary photo" field. A similar approach could be adopted in Quickstart 2.

### Is your feature request related to a problem? Please describe.
The AZ News and AZ Event content types limit the flexibility of site editors to choose images to be used with different displays.

### Describe the solution you'd like

As a site editor, in order to have more control over images used for news and event nodes, I would like to be able to:
- Choose whether to display a main image (shown towards the top of the full content display) or not
- Choose whether to display a thumbnail image (shown in other displays, such as card and teaser) or not
- Choose two different images for the main image and the thumbnail image
- Easily use the same image file for both the main image field and thumbnail image field

To fulfill these user stories for AZ News and AZ Event, the following changes could be made:
- Add an optional "Thumbnail Image" field to the AZ News and AZ Event content types, placed in the Summary section of the form display
- Add two tokens, one for AZ News and one for AZ Event, which would function similarly to [az_canonical_url](https://github.com/az-digital/az_quickstart/blob/03b7d43eae6182e495777ea6f4eeb1553a3b09c4/modules/custom/az_core/az_core.module#L112-L114). These tokens would be used with displays other than default or full content (such as card displays).
- Add logic to set the token such that it returns the Thumbnail Image field if it is populated and if it is not, it returns the main image (the "Photo" field for AZ News or the first image in "Event Photos" for AZ Event).
- Add documentation of this change within Quickstart and on [quickstart.arizona.edu](https://quickstart.arizona.edu).

### Describe alternatives you've considered

1. Add a new "Thumbnail Image" field without the use of tokens: users would need to explicitly select an image for each field. This change might require database updates for AZ news nodes, since card displays would be updated to use the new Thumbnail Image field instead of the existing Photo field.
2. Use the existing image field on each content type as the thumbnail image for card and teaser displays, but add a checkbox on the form display to allow users to choose whether to include the selected image(s) on default/full content displays as well. This checkbox would be checked by default, to maintain current behavior.

### Updated Requirements (Mar 27, 2023)

- Following a suggestion from @tadean, a hook function can be used to optionally update the Thumbnail Image field after a user edits the node. By checking for any changes made to the main image from the edit page, we can then set the thumbnail image to match the main image in all cases **except** when the user has specifically selected a different image for the thumbnail. This approach does not require a new token or an extra field.
- I think we can assume that users adding images to events would like those images to be displayed in the Full Calendar view at /calendar (and if not, they can remove the thumbnail images from the nodes). However, I think that users may **not** wish to have images displayed in the Grid View for events. The Grid View may be included on pages where site editors would prefer to have a more compact view, without card images showing for the events. For this reason, I think it would be best to create an alternate "Grid View with Images" view which site editors can opt to use if they wish.
- Similarly, I'm a little hesitant about adding thumbnail images to the Grid Sidebar view for events, which would match the thumbnails on the Small Row View for news. If desired, we could add an optional "Grid Sidebar with Images" view. Further discussion with AZ Digital is needed to confirm whether to add the thumbnail images to the sidebar view and if so, which view mode should be used.

### Updated Requirements (May 3, 2023)

After further AZ Digital discussion, we will proceed with the implementation described by the following user story. As a content editor, I want to create an event or news article with:
1. No featured image or thumbnail image
2. A featured image without a thumbnail image
3. A thumbnail image without a featured image
4. A featured image and thumbnail image that are the same
 • (This is the existing behavior for AZ News which we would like to maintain. This will be the default behavior for AZ Event as well.)
5. A featured image and thumbnail image that are different

An additional requirement is that the editor interface should make it clear that selecting completely different thumbnail and featured images is discouraged since it creates a disjointed user experience.

Certain use cases might depend on allowing a thumbnail image with a different featured image or no featured image at all. For example, an editor might like to set a portrait photo of a person as the thumbnail and then include it in a smaller size within the body of the article, rather than having it full-size at the top of the article page, causing significant scrolling. Editors might wish to use a particular image for the thumbnail of a news article while using a more appropriate or eye-catching image as the featured image on the article page itself: again, the thumbnail image could be included in the article body. Events in a particular series might use a logo or icon as the thumbnail image: editors may not have specific photos available to use for the events. Editors may remove the logo image as the featured image since it would appear out-of-place in full-size at the top of the event page.

### Roles and Permissions considerations
No roles or permissions updates would be required for this change.

## Additional context

- This feature would be a blocker for #1605: Add thumbnail image to Row display for AZ Event.
- This feature is related to #1958: Allow users to select view mode for Event Photos field of AZ Event.

### Future work

The options regarding these images might be handled best as part of the media items themselves. For example, the media item for a node might allow editors to specify an alternate source file for the thumbnail image (or no thumbnail image). While it doesn't seem feasible to implement this at this time, we could keep it in mind for the future.

**Comment by joshuasosa** [comment]
Could we instead handle this issue with cropping?

Currently for news, the image shown on the news list page uses the az_card_image image style, which can be cropped. The media list, as seen in the sidebar when viewing a news article, uses the thumbnail image style, which can't be cropped. Perhaps thumbnail could be added as a cropping option.

My concern is that if a different image is used for the thumbnail, that image may not become available to view larger on the actual article. I don't like when news sites draw a viewer in with a small, potentially interesting image and link to the article, only to not have that image on the actual article to be able to see it bigger. Aside from that viewer inconvenience, I also think it is better for articles to present their preview image and article banner image as the same image for consistency in viewer expectations.

As for what's available in Quickstart 1, I installed it from repo and I don't see a Summary Photo field. The "Extra fields" section does have a "News Article Photos" field set, but it doesn't appear to be used on the view modes. It's possible the field referred to in this issue for UAQS1 was a custom-added field.

**Comment by joeparsons** [comment]
Having two separate image fields would also be useful for the Trellis Events integration we're working on.  There is an optional image field in the Trellis Events system that included in the events API that could be imported into one of the Quickstart image fields but it seems likely to me that Quickstart content editors/admins might sometimes want to use a different summary/thumbnail image for imported events than the one imported from Trellis since the quality/content of the imported image may be a little unpredictable.

**Comment by joshuasosa** [comment]
Sounds good!

I think it would still be nice to at least include the thumbnail image (maybe in a larger size) somewhere on the content page if it's different from the content image. That comes out of my own user frustrations with news sites that don't let me see the image from the thumbnail in a bigger way. Sometimes I click an article specifically because of the image, then look through the article page and don't see it anywhere.

**Comment by bberndt-uaz** [comment]
@joshuasosa @joeparsons Thank you both for your input! I'll start working on this issue using the solution with the optional thumbnail image field, but I'm definitely open to more feedback. I agree that adding a thumbnail crop type would be helpful. In the vast majority of cases, I expect users will simply choose a main image and let that be used for the thumbnail image as well.

**Comment by bberndt-uaz** [comment]
To allow users to set a thumbnail image without a feature image (and satisfy all four of the user stories mentioned in the description), I would propose adding a **Match Thumbnail Image to Photo** checkbox above the Thumbnail Image field in the Summary section. This checkbox would be checked by default. Users could uncheck the box to prevent the thumbnail image from being matched to the feature image upon saving. This would also simplify the pre-save matching functionality so it would be easier for users to understand.

The process for creating nodes with each type of arrangement of images would look like the following.

As a content editor, I want to create an event or news article with:
1. **No feature image or thumbnail image:** Save the node without selecting any images.
2. **A feature image without a thumbnail image:** Select a feature image, uncheck the _Match Thumbnail Image to Photo_ checkbox, and save the node.
3. **A thumbnail image without a feature image:** Select a thumbnail image and save the node.
4. **A feature image and thumbnail image that are the same:** Select a feature image and save the node.
  • (This is the existing behavior for AZ News which we would like to maintain. We could also assume this is the default behavior for events, with a matching feature and thumbnail image.)
6. **A feature image and thumbnail image that are different:** Select a feature image, uncheck the _Match Thumbnail Image to Photo_ checkbox, select a thumbnail image, and save the node.

**Comment by joshuasosa** [comment]
For 3 and 5, will the thumbnail image still be made available on the actual page? That's the one thing I mentioned that I don't like: thumbnail images that are not available to view on the page. It creates a disjointed and disappointing user experience.

**Comment by trackleft** [comment]
While I agree that this functionality should not be used 99.99% of the time, I do like that this allows content editors the option to override the default for use-cases we don't necessarily know about yet.

**Comment by joeparsons** [comment]
> For 3 and 5, will the thumbnail image still be made available on the actual page? That's the one thing I mentioned that I don't like: thumbnail images that are not available to view on the page. It creates a disjointed and disappointing user experience.

@bberndt-uaz I think it would at least be worth adding some help text to the new checkbox that states that using totally different images is not recommended.

**Comment by joeparsons** [comment]
We decided in our 2023-05-03 PR meeting to proceed with the implementation outlined by @bberndt-uaz in https://github.com/az-digital/az_quickstart/issues/2091#issuecomment-1489269433.

@bberndt-uaz is going to update his PR to include some help text that discourages using totally different images and also add update his outline above with some additional use cases that were discussed in our meeting today.

**Comment by bberndt-uaz** [comment]
Thank you all for your feedback!

I have added another Updated Requirements section to the issue description above, along with some more context from our discussion today. I'll update the help text in my PR today so that it will be ready for review.
