### ISSUE TITLE
Error upon save when linking to a document in a Card Link URL field

### ISSUE THREAD

**Issue by akslay** [az-digital/az_quickstart#2102]
## Problem/Motivation
When attempting to use the card link field to link to a document (PDF) on the site, you receive an error upon trying to save the page. Document links work fine in the card body, but not in the card link field.
![Screen Shot 2022-12-16 at 11 33 33 AM](https://user-images.githubusercontent.com/52931751/208165620-fecd1783-1f56-4192-a943-9bfb4b6fa72a.png)

**Comment by akslay** [comment]
![screencapture-7b5e2985-cedf-4a13-ab91-3a35916c835d-pr-2077-probo-build-node-add-az-flexible-page-2022-12-16-11_27_16](https://user-images.githubusercontent.com/52931751/208165845-3807bf48-3013-4642-9c55-2a96ae74d674.png)

**Comment by joeparsons** [comment]
@tadean suggested this is probably do to the call to Url::ifValid() in our custom validation handler for the link compoenent of the custom card field:
```
/**
   * Form element validation handler for the 'link_url' field.
   *
   * Disallows saving inaccessible or untrusted URLs.
   */
  public function validateCardLink(&$element, FormStateInterface $form_state, &$complete_form) {

    if (!empty($element['#value'])) {
      // Check to make sure the path can be found.
      if ($url = $this->pathValidator->getUrlIfValid($element['#value'])) {
        // Url is valid, no conversion required.
        return;
      }
      $form_state
        ->setError($element, t('This link does not exist or you do not have permission to link to %path.', [
          '%path' => $element['#value'],
        ]));
    }
  }
```
