### ISSUE TITLE
Custom fields on AZ content types get disabled on form display with any module uninstall

### ISSUE THREAD

**Issue by joshuasosa** [az-digital/az_quickstart#2201]
## Problem/Motivation
A site builder may want to add custom fields to AZ content types with the UI since it is a common and available UI workflow. When any module is uninstalled, those custom fields are removed from the content type form display and placed into the disabled section.

### Describe the bug
Uninstalling modules disables custom AZ content type fields on the form display.

This issue does not occur on non-AZ custom content types.

### To Reproduce

1. Go to Structure > edit People
2. Add any custom field (e.g., Publications using Text formatted, long).
3. Go to Manage form display and observe the new custom field in the 'active' list of fields.
4. Install a module (e.g., masquerade, devel, etc.)
5. Uninstall a module.
6. Return to the People content type's Manage form display and observe the new custom field in the 'disable' section.

### Expected behavior
Uninstalling a module should not disable custom fields on AZ content type form displays.

**Comment by trackleft** [comment]
I was able to narrow down the issue to possibly involving https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php:

Install `az_quickstart` with just `az_person` and its dependencies enabled and the `devel` module
Then add a custom field to the `az_person` content type 
Place the field on the az_person edit form via the field_ui
Then uninstall the devel module
There should be no change to the person edit form
After that, the next steps will be
Reenable the `devel` module
Enable az_seo
See if field is moved at this point
Uninstall the `devel` module, see if field is moved at this point

Using this version of az_quickstart.info during initial installation of az_quickstart

```
name: Arizona Quickstart
type: profile
description: 'The University of Arizona Quickstart Installation Profile'
core_version_requirement: ^9

distribution:
  name: Arizona Quickstart

install:
  # - az_cas
  # - az_paragraphs
  # - az_paragraphs_accordion
  # - az_paragraphs_cards
  # - az_paragraphs_photo_gallery
  # - az_paragraphs_text
  # - az_paragraphs_text_background
  # - az_paragraphs_text_media
  # - az_paragraphs_view
  # - az_core
  # - az_flexible_page
  # - az_flexible_block
  # - az_block_types_quick_links
  # - az_metrics
  # - az_news
  - az_person
  # - az_event
  # - az_security
  # - az_seo
  # - az_google_tag
  # - drupal:node
  # - drupal:history
  # - drupal:block
  # - drupal:breakpoint
  - drupal:ckeditor
  # - drupal:color
  # - drupal:config
  # - drupal:content_moderation
  # - drupal:contextual
  # - drupal:menu_link_content
  # - drupal:datetime
  - drupal:block_content
  # - block_content_permissions:block_content_permissions
  # - drupal:editor
  - drupal:help
  # - drupal:image
  # - drupal:menu_ui
  # - menu_block:menu_block
  # - drupal:options
  # - drupal:path
  # - pathauto:pathauto
  # - easy_breadcrumb:easy_breadcrumb
  # - drupal:page_cache
  # - drupal:dynamic_page_cache
  # - drupal:big_pipe
  # - drupal:taxonomy
  # - drupal:dblog
  # - drupal:search
  # - drupal:shortcut
  # - token:token
  # - drupal:toolbar
  - drupal:field_ui
  # - drupal:file
  - drupal:rdf
  # - drupal:views
  # - drupal:views_ui
  # - drupal:tour
  # - drupal:automated_cron
  # - drupal:google_tag
  # - block_class:block_class
  # - chosen:chosen
  # - ckeditor_bs_grid:ckeditor_bs_grid
  # - coffee:coffee
  # - bootstrap_utilities:bootstrap_utilities
  # - exclude_node_title:exclude_node_title
  # - search_exclude:search_exclude
  # - draggableviews:draggableviews
  # - role_delegation:role_delegation

themes:
  - az_barrio
  - claro
```

**Comment by trackleft** [comment]
Open question, should our `QuickstartConfigProvider` be called on module uninstallation?

**Comment by tadean** [comment]
It seems like this is happening because of the functionality that turns off a module's config overrides if the module is removed. This worked for `az_cas` (the first module to use this functionality, for `cas` overrides, but seems like it has some unintended effects for some of the later modules that have created overrides on form displays as @trackleft mentioned. We should probably consider either removing the uninstall hook, or maybe preferably cause the Config Override trigger to merge with the active configuration rather than overwrite it as it's currently doing so that only the values that are actually changing are updated.

**Comment by trackleft** [comment]
Ahh, thanks for this @tadean , I can test those possible solutions
