### ISSUE TITLE
Upgrade migrate_plus, migrate_tools, migrate_queue_importer for D10 compatibility

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#2213]
## Conditions of satisfaction
- [ ] migrate_plus is version 6.01

Blocked by https://www.drupal.org/project/migrate_tools/issues/3347272

**Comment by joeparsons** [comment]
Needed for #2081

**Comment by joeparsons** [comment]
Migrate tools issue related to Migrate Queue Importer test failures:
https://www.drupal.org/project/migrate_tools/issues/3347272

Migrate Queue importer issue:
https://www.drupal.org/project/migrate_queue_importer/issues/3342928

**Comment by joeparsons** [comment]
We still need to upgrade migrate_tools and migrate_plus

**Comment by joeparsons** [comment]
- [ ] #2450

**Comment by joeparsons** [comment]
Last piece completed with #2354
