### ISSUE TITLE
Define requirements for AZQS Person

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#225]
## What is the problem that we want to solve?
We need to determine what our target is going to be for the AZQS Person content type. 

The default option would be to create a custom content type (azqs_person) with the same fields and styles used in the D7 version of Quickstart.

An alternative approach has been suggested to instead modify the Drupal "User" functionality which would add the benefit of optionally allowing users to edit their own profiles. There are some considerations about site performance and security that might be affected by this approach.

## Conditions of satisfaction
- [ ] The considered options are documented
- [ ] A recommended next step is documented
- [ ] An estimate of time and effort is provided for the recommendation
- [ ] …

**Comment by akslay** [comment]
@camikazegreen @danahertzberg 
Did we decide to go with a standard Person content type for now (matching D7) and re-visit the user functionality in the future/post-mvp?

**Comment by danahertzberg** [comment]
> @camikazegreen @danahertzberg
> Did we decide to go with a standard Person content type for now (matching D7) and re-visit the user functionality in the future/post-mvp?

@akslay That is correct. MVP1 of Person is the same as QS1 with no changes or added functionality. Here is the ticket to work on. https://app.zenhub.com/workspaces/quickstart-20-5e8f25351c5b8596956ebb92/issues/az-digital/az_quickstart/298

I will close this ticket as the requirements have been defined.

**Comment by trackleft** [comment]
It was determined that using the User entity type as content would be less ideal than adding a permission that allows authenticated users to edit their own content.

Related to: #3553
