### ISSUE TITLE
Regression: Critical search block class not applied during config distro update using the merge strategy if that block has been edited.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#2251]
## Problem/Motivation
This merged PR https://github.com/az-digital/az_quickstart/pull/1720 changed how classes are applied to the search form block.
1. Classes are applied to the search form block via block class through config.
2. Classes are removed from the stylesheet.

### Describe the bug
<img width="366" alt="image" src="https://user-images.githubusercontent.com/1023167/220784640-6296fae6-84fe-4934-a1c4-2a49c0757275.png">

Should look like this

<img width="297" alt="image" src="https://user-images.githubusercontent.com/1023167/220784764-ed75ac94-903a-4435-b84c-75ddc97540dc.png">

### To Reproduce

On an existing site (`2.5.x` and older), save this form: `/admin/structure/block/manage/az_barrio_search`
Then apply `2.6.0-rc2` or `2.6.0-rc1` code updates.
Set the config distro strategy to merge
Apply config distro updates.

See broken search form button.
<img width="366" alt="image" src="https://user-images.githubusercontent.com/1023167/220784620-f8f4d6d9-c855-45e2-be3e-801bea68e7ae.png">

## Possible resolutions
1. Revert this commit: https://github.com/az-digital/az_quickstart/commit/ee13d6d398651e4db2498c4c5bd530d87c1b5122
2. Add back the css selectors used before this change themes/custom/az_barrio/css/style.css 
3. Programmatically wrap the block in question with the `az-search-block` class `hook_preprocess_block`
4. Use hook_update to apply precision configuration update adding the class to the block.
5. Add class to the template for the block: https://github.com/az-digital/az_quickstart/blob/main/themes/custom/az_barrio/templates/blocks/block--search-form-block.html.twig

CSS selectors that can be merged <img width="1377" alt="image" src="https://user-images.githubusercontent.com/1023167/220785478-302a0260-e798-4f91-a5d5-de90442e5f1c.png">

**Comment by bberndt-uaz** [comment]
I agree that options 3 and 5 sound best. If there would be any performance benefit from using the hook method, I think I'd prefer that approach. Otherwise, adding the class to the block template seems straightforward.
