### ISSUE TITLE
Missing Smart Title Config

### ISSUE THREAD

**Issue by akslay** [az-digital/az_quickstart#2253]
## Problem/Motivation
Smart Title config is missing for "AZ Page", which prevents display modes from looking the way they should (because title has become non-configurable in the display settings). AZ Page "Card" and "Row" display modes are configured to use Smart Title, but Smart Title hasn't been enabled for the content type.

The problem appears more prominently on migrated sites for some reason, more so than it does fresh builds (like on Probo sites).

![Screenshot 2023-02-23 at 2 25 58 PM](https://user-images.githubusercontent.com/52931751/221033882-7237a499-35ab-4677-ae61-c58c261a274c.png)

### To Reproduce
Use the Card view for AZ Page. Notice that titles are missing and/or display under or above the card.

## Proposed resolution
Enable Smart Title for AZ Page content type
https://github.com/az-digital/az_quickstart/blob/43120a7d3e80ad7ae2e7b9c2ed348dd569b5288e/modules/custom/az_core/config/install/smart_title.settings.yml

**Comment by trackleft** [comment]
Ensure this will work with exclude node title.

**Comment by akslay** [comment]
Smart Title isn't used on the main node display, so it should be fine in that regard. I believe it's only used on the Card and Row display modes.
