### ISSUE TITLE
Add Asset Injector as optional module

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#2268]
## Motivation
Many times sites need custom CSS or JS added to certain pages, etc.  A large number of Quickstart sites add the [Asset Injector](https://www.drupal.org/project/asset_injector) module for this.  Adding this module to Quickstart would give site admins one less module to maintain.

Although there is definitely tremendous potential for modules like Asset Injector to be misused / overused, it is a more robust solution for many valid use cases than what is currently available in Quickstart using custom content blocks with HTML fields.

## Proposed Resolution
Add [Asset Injector module](https://www.drupal.org/project/asset_injector) to Quickstart as an optional module (disabled by default).

Nice to have (could be a follow-up): Document guidelines for appropriate and inappropriate use cases for Asset Injector.

### Describe alternatives you've considered
Many Quickstart sites use custom content blocks with HTML fields to add custom CSS/JS to pages but this approach does not offer the same level of flexibility and configuration (or performance enhancements) that the Asset Injector module provides.

### Roles and Permissions considerations
We should ensure that Asset Injector is usable by the Administrator role only.

**Comment by trackleft** [comment]
As much as I don't like asset injector, I like adding it manually even less lol.
