### ISSUE TITLE
Investigate feasibility of reusable views plugins for exposed filter views

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#2275]
## What is the problem that we want to solve?
Many Quickstart sites contain custom views with exposed filters that utilize the views `exposed_form` plugin provided by the [Better Exposed Filters contrib module](https://www.drupal.org/project/better_exposed_filters) to display options as checkboxes, etc.  These views typically require a decent amount of custom CSS to be added in order to make the exposed filter form elements usable and look acceptable.

#### Quickstart 1
- https://eller.arizona.edu/programs/finder
- https://eller.arizona.edu/departments-research/directory-expertise
- https://capla.arizona.edu/academics/programs
- https://ccass.arizona.edu/expertise/find-expert 
- https://news.arizona.edu/calendar

#### Quickstart 2
- https://housing.arizona.edu/dorms
- https://water.arizona.edu/expert-directory
- https://capla.arizona.edu/academics/programs

#### Similar non-Quickstart examples
- https://www.arizona.edu/degree-search
- https://www.arizona.edu/admissions/student-stories

### Related Bootstrap Barrio issues
Exposed filter vertical alignment for filters with different heights of description and title (title elements that wrap cause vertical alignment issues).

### Related chosen (JS library) problems
Enabling chosen for exposed select elements introduces problems related to z-index when the selected values make the form element taller.   @trackleft suggested we might want to use some of the CSS from this open source Chosen/Bootstrap project to address these issues: https://github.com/haubek/bootstrap4c-chosen/blob/master/dist/css/component-chosen.css

## Proposed Resolution
Investigate the feasibility of adding one or more custom views plugins to Quickstart that make the process of building these kinds of views easier.

The most obvious candidate plugin would be a views `exposed_form` plugin.  One possibility for a Quickstart `exposed_form` plugin would be to extend the [plugin](https://git.drupalcode.org/project/better_exposed_filters/-/blob/6.0.x/src/Plugin/views/exposed_form/BetterExposedFilters.php) provided by the Better Exposed Filters module as a base and then add our additional styles/configuration options, etc.

## Additional context
Example styles added to header of Quickstart 2 view via a `Global Text Area` field:
```
<style>
div.view-housing-dorms > div.view-content {
  margin-top: 0.5rem;
}

div.housing-dorms-row > article > div.node__content {
    margin-top: 0.5rem;
}

div.field__label {
  font-weight:700;
}

div.field__label::after {
  content: ':';
}

div.field__items {
  display:inline;
}

.field--type-list-string div.field__items > div:nth-last-child(n+2)::after {
  content: ',';
}

fieldset.form-item, fieldset.form-item-search, details.form-item {
  width:100%;
  margin-top: 1.25rem;
  margin-bottom: 0;
  padding: 0;
}

#block-dormsidebarmenu {
  margin-top: 1.5rem;
}


@media (max-width: 576px) {
  section.region-sidebar-first div.bef-exposed-form {
    margin-bottom: 0 !important;
  }
  div.housing-dorms-row > article > div.node__content {
    margin-top: 0;
  }
}

div.bef-exposed-form {
  padding-top: 3px;
}

div.bef-exposed-form > div.content {
  padding: 0 1.5rem 0.5rem;
  box-shadow: 0 0 3px #9EABAE;
}

div.bef-exposed-form div.form-row {
  margin: 0;
}

div.bef-exposed-form fieldset.form-type-textfield {
  max-width: 100%;
}

div.bef-exposed-form input.form-text {
  margin-top: 0;
  margin-bottom: 0.25rem;
}

div.bef-exposed-form legend {
  font-size: 1.25rem;
  line-height: 1.5rem;
}

div.bef-exposed-form span.fieldset-legend, 
div.bef-exposed-form summary,
div.bef-exposed-form fieldset.form-type-textfield > label {
  color: #49595e;
  font-weight: 600;
  font-size: 1.25rem;
  line-height: 1.5rem;
  height: 1.5rem;
  margin-bottom: 0.5rem;
}

div.bef-exposed-form div.fieldset-wrapper, 
div.bef-exposed-form div.details-wrapper {
  margin-left: 0.625rem;
}

div.bef-exposed-form div.form-check > label {
  color: #1E5288;
  font-weight: 600;
  margin-bottom: 0.25rem;
  margin-left: 0.25rem;
}

summary::marker {
    content: none;
}

summary::-webkit-details-marker {
    display: none;
}

summary::before {
    content: '\25B8';
    font-weight: 700;
    font-size: 1.5rem;
    display: inline-block;
    width: 1rem;
}

details[open] > summary::before {
    content: '\25BE';
}

div.bef-exposed-form input.form-check-input {
  margin-top: 0.325rem;
}
</style>
```

**Comment by joeparsons** [comment]
Related issue: https://github.com/az-digital/az_quickstart/issues/2183

**Comment by joeparsons** [comment]
## 2022-03-08 AZ Digital workshop findings and ideas:

- For Chosen specifically, we ought to look into contributing to this d.o. issue (and/or using the existing patch) as a way of addressing the Bootstrap classes getting added to Chosen elements by AZ Barrio which are causing problems: https://www.drupal.org/project/chosen/issues/2237539
- We probably ought to start looking into alternatives for Chosen since it is officially deprecated / unmaintained and has some known accessibility issues
  - Potential alternatives:
    - [Choices.js](https://choices-js.github.io/Choices/) - vanilla JS alternative to Select2 / selectize.js
    - [typeahead.js](http://twitter.github.io/typeahead.js/) - Twitter open source autocomplete widget project
- Coming up with a "Quickstart multiselect" `Exposed filter widget` for Better Exposed Filters seems like a worthwhile idea

**Comment by trackleft** [comment]
This module provides a plugin that better exposed filters can use https://git.drupalcode.org/project/bef_select I was thinking that we could use it as a guide.

**Comment by danahertzberg** [comment]
Could add QS features and options in the view

Configureable to class on an element
Select list of styles for each element
Have to hone in configuration form to narrow down options that can be configured
Collapsible groups
Checkbox vs radio
Bold or colored legend
Horizontal or vertical filters
Next steps: Have Chris get examples and verify next steps with the team

https://digital.arizona.edu/arizona-bootstrap/docs/2.0/components/forms/#checkboxes-and-radios-1

**Comment by danahertzberg** [comment]
```
"drupal/viewsexposedfilterblock": {
    "Label (Title) not set for Views block (2720101)": "https://www.drupal.org/files/issues/2018-09-12/2720101-72.patch"
},
```

**Comment by danahertzberg** [comment]
Central marcomm mockups: https://xd.adobe.com/view/223ea53b-daf0-42c7-a500-60c0eda3fddc-776d/screen/794d4a8b-3b85-4224-9024-06a2639be7ce/
