### ISSUE TITLE
Update allowed Smart Date 3.7.x version from 3.7.0 to 3.7.2

### ISSUE THREAD

**Issue by bberndt-uaz** [az-digital/az_quickstart#2286]
## Problem/Motivation
The composer.json requires either version 3.6.1 or version 3.7.0 of the Smart Date contrib module. However, two new versions of Smart Date have been released since 3.7.0.

## Proposed resolution
Update the version constraint to allow version 3.7.2 instead of 3.7.0.

**Comment by joeparsons** [comment]
Sounds like one of the issues that was fixed in 3.6.2 is affecting Quickstart 2.6.x sites so we should probably include this in the next patch release instead of waiting until 2.7.0.

**Comment by bberndt-uaz** [comment]
It looks like this wasn't included in the 2.6.3 release so I have added it to 2.6.5.
