### ISSUE TITLE
Add Very Small media display

### ISSUE THREAD

**Issue by djcelaya** [az-digital/az_quickstart#2301]
## Motivation
UAHS Communications utilizes narrrow, in-line images frequently in News stories. These are typically portraits (which tend to be taller than they are long) of a faculty/staff member related to the story but can also be other supporting images. The existing Square media display almost works but because the width and height are equivalent, source images that are not naturally square-shaped have their top and bottom image areas cropped out.

We are migrating our main, Drupal 7 site and have discovered this feature request in migrating our news story content. In the source (D7), we have inline images that look like this:
<img width="881" alt="Screenshot 2023-03-20 at 9 56 37 AM" src="https://user-images.githubusercontent.com/2702851/226413103-9705ad8d-e6ad-4b98-a11d-f8bfc0da9f00.png">
But the corresponding migrated image looks like this:
<img width="965" alt="Screenshot 2023-03-20 at 9 56 46 AM" src="https://user-images.githubusercontent.com/2702851/226413262-b689849b-81ac-4106-868c-a05db8b49a61.png">

## Proposed Resolution
Add a new new media display called "Very Small (220px)" that functions equivalently to "Square (220X220px)" but does not place a restriction on image height.

### Describe the solution you'd like
A new media display is available when embedding an image in content. The display should function like the existing Square display on larger screens but Small on smaller screens. That is, it should span the available space on smaller screens like the Small media display does...Square doesn't seem to do this?

### Describe alternatives you've considered
Remove the height restriction on "Square (220X220px)" and rename to "Very Small (220px)". I believe this could still work because if site builders wanted a square rather than a rectangle, they could just crop the image to a square or provide a square-shaped source image.

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Anonymous user
- Authenticated user
- Content editor
- Content administrator
- Administrator

Anonymous and authenticated users are unaffected. They will simply see the correctly sized image. Content editor and higher will have a new display option (Very Small) when embedding images in content.

## Additional context
Source:
<img width="873" alt="Screenshot 2023-03-20 at 10 01 51 AM" src="https://user-images.githubusercontent.com/2702851/226414286-69559c54-eda4-4c90-b042-8132ce9307e2.png">
Destination:
<img width="964" alt="Screenshot 2023-03-20 at 10 02 01 AM" src="https://user-images.githubusercontent.com/2702851/226414343-0ea6d6e8-fdab-45be-84a2-c55b8fa08c89.png">

**Comment by trackleft** [comment]
Are you using this plugin while migrating embedded content? https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_migration/src/Plugin/migrate/process/EntityEmbedProcess.php#L33-L44

**Comment by trackleft** [comment]
@djcelaya in news.arizona.edu we use a concept called aspect ratio switcher, which might be useful here as well.

In drupal 7 the module that we used was called [imagecache_actions]( https://www.drupal.org/project/imagecache_actions), but in drupal 8 the module is called [image effects](https://www.drupal.org/project/image_effects)

Specifically this part 
```
Aspect Switcher - lets you perform different actions or use different dimensions based on whether the image is 'landscape' or 'portrait'
```
