### ISSUE TITLE
Add customizable Title field for Link to external news in AZ News

### ISSUE THREAD

**Issue by djcelaya** [az-digital/az_quickstart#2302]
## Motivation
UAHS Communications very frequently posts "In The Media" or "Media Mentions" content. These are instances where an external media/news organization has referenced UAHS in one of their stories. See our [Newsroom > In The Media](https://healthsciences.arizona.edu/newsroom/in-media) or below for some current examples.

Source D7 site:
<img width="1223" alt="Screenshot 2023-03-20 at 12 00 10 PM" src="https://user-images.githubusercontent.com/2702851/226443001-8e7daab1-362b-48fd-8f2b-d31a3dcfc978.png">

Destination QS2 site:
<img width="1151" alt="Screenshot 2023-03-20 at 12 00 22 PM" src="https://user-images.githubusercontent.com/2702851/226443030-a7875f1b-d7bd-45ae-a91a-e8f5c2b32494.png">

In migrating this content from our custom D7 site to QS2, I have taken the approach of mapping the source content into AZ News and am populating the "Summary fields > Link to external news field" with the URL of the external news story. This works great but does not capture the name of the external news organization. For this approach to work, it would be ideal to be able to enter a custom title for this external link rather than relying on the default "Read more" that is currently provided by QS2.

Form display of AZ News:
<img width="441" alt="Screenshot 2023-03-20 at 12 02 08 PM" src="https://user-images.githubusercontent.com/2702851/226440368-de6eb8b0-153e-44d0-a3fd-44b15d16c859.png">

### Describe the solution you'd like
Expose field_az_link_title in AZ News edit form so that content managers can enter a custom link title. Node displays of AZ News will use this title when set, or "Read more" by default (current behavior) when not set.

### Describe alternatives you've considered
Adjust the title of the AZ News node to reflect the organization that published the piece...not ideal. To clarify, our writers would perhaps preprend the organization ahead of the desired title in the existing node title field. This would not be an adjustment to QS2 but to the content creation workflow outside of QS2.

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Anonymous user
- Authenticated user
- Content editor
- Content administrator
- Administrator

Anonymous and authenticated users are unaffected. They will simply see the custom link title instead of the default text "Read more". Content editor and above can enter a custom title field when creating or editing an AZ News item.

**Comment by trackleft** [comment]
Looks like this was added in 2.6.0 https://github.com/az-digital/az_quickstart/pull/1966
