### ISSUE TITLE
Changes to existing News, Events and Person content do not update until after a cache clear.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#2312]
## Problem/Motivation
When I change an image on a news article, I expect to see the result upon save, and not have to clear the site cache.

### Describe the bug
It seems as though there is an issue with page cache when updating media on the news or event content type.

### To Reproduce
Create a news item and add an image
Save
Edit the news item and change the image.
Save
View the news item and see that the image has not changed.

**Comment by bberndt-uaz** [comment]
Thanks for creating this! I just tested with a Pantheon multidev and this appears to be an issue with the Photo field for AZ Person and the Event Photos field for AZ Event. It does NOT affect the Photo field for pages.

**Comment by trackleft** [comment]
I have also tested this by changing a taxonomy term on a field and found that the bug exists in that situation as well.

**Comment by trackleft** [comment]
Strangely enough it appears this is only an issue for logged in users, if I save a node and then view in an incognito browser I see the updated media.

**Comment by trackleft** [comment]
I've updated drupal core to version 9.5.7 and the issue seems to have resolved itself
