### ISSUE TITLE
Empty Sidebar First region rendered on pages not in the menu

### ISSUE THREAD

**Issue by bberndt-uaz** [az-digital/az_quickstart#2315]
## Problem/Motivation
While testing Quickstart 2.6.1 on the [Test environment for the Think Tank site](https://test-azs-thinktank.pantheonsite.io/), we noticed that the sidebar region is appearing on all pages of the test site, whether those pages are in the sidebar menu or not.

### Describe the bug
In this case of the Think Tank site, the sidebar is using a custom menu instead of Main Navigation. For pages which are not in the sidebar menu, the HTML for the sidebar region is included but is empty:

```html
<div class="sidebar_first sidebar col-md-3 order-first" id="sidebar_first">
  <aside class="section" role="complementary">
                  
  </aside>
</div>
```

## Proposed resolution
This problem may be related to this Drupal issue: [Empty blocks get displayed](https://www.drupal.org/project/menu_block/issues/3280764). We could try applying the patch from this issue to fix the problem with the empty Sidebar First region.

However, this patch cannot be applied currently because recently we added a patch from another Drupal issue to Quickstart: [Menu block renders when tree is empty as of 8.x-1.8 [regression]](https://www.drupal.org/project/menu_block/issues/3271218).

@trackleft noted that patch 17 from this issue removes the use statement for AccountInterface:
`-use Drupal\Core\Session\AccountInterface;`

Since the patch from the first linked issue requires the use of AccountInterface for menu blocks, @trackleft suggested removing the other patch from Quickstart so that the "Empty blocks get displayed" patch could be applied.

### Expected behavior

The sidebar region should not appear if the region is empty (no sidebar menu blocks are displayed).

##  Screenshots
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/74572157/228916462-6142eabe-45e1-437b-8f82-a768e738ecab.png">

**Comment by bberndt-uaz** [comment]
We tried simply removing the existing Menu Block patch in Quickstart but this did not resolve the issue. Removing the existing patch and adding the new patch did resolve the issue and we did not find any issues whether logged in to the site or logged out.

**Comment by joeparsons** [comment]
### Updates from 2022-03-31

- We found that the patch from this drupal.org issue works on sites using PHP 8.1 (e.g. on Probo/Lando) but not on sites using PHP <=8.0: https://www.drupal.org/project/menu_block/issues/3280764
- We tried updating the existing `hook_block_access()` implementation in `az_core` to apply to all menu blocks in @bberndt-uaz's draft PR as an alternative to using the Menu block module patches from drupal.org but this did not seem to work
