### ISSUE TITLE
Token module deprecation error

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#233]
## Problem/Motivation
All of our builds are currently failing the drupal-check ("Check for deprecated code") step in ProboCI due to the following deprecation error reported in the token module (which was added in #217).

### Describe the bug
Deprecation error reported by drupal-check:
```
------ --------------------------------------------------------------------- 
 Line   modules/contrib/token/tests/src/Kernel/KernelTestBase.php            
------ --------------------------------------------------------------------- 
        Reflection error: Drupal\core\Language\LanguageInterface not found.  
------ --------------------------------------------------------------------- 

[ERROR] Found 1 error
```

### To Reproduce

1. Clone az_quickstart repo
2. Run `composer install`
3. Run `drupal-check`
4. See error.

## Proposed resolution
Patch the token module to resolve deprecation error.

### Expected behavior
Deprecation-free builds of fresh AZ Quickstart installs.

**Comment by joeparsons** [comment]
Curiously, I see this error on ProboCI but _not_ locally when running `lando drupal-check` on a fresh clone/install of Quickstart.  Not really sure what's going on there...

**Comment by danahertzberg** [comment]
Decided to not track deprecations. Complexity of D8/9 transition deemed it too cumbersome to track many deprecations.
