### ISSUE TITLE
Change the azdigital-general channel name in slack to azdigital-support

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#2331]
Because azdigital-general is being used as the defacto support channel, which I 100% agree with, we should just go along with this and change the channel name  to azdigital-support so people can feel more encouraged to ask for support in that channel.

What to consider when changing a channel name.

How does this affect external links to this channel
How do people looking for the friday meetings channel find it if the name changes
How do we announce this change

**Comment by bberndt-uaz** [comment]
[This page in the Arizona Bootstrap documentation](https://digital.arizona.edu/arizona-bootstrap/docs/2.0/about/get-involved/#connect-with-us-on-slack) would need to be updated.

**Comment by trackleft** [comment]
https://slack.com/help/articles/201654073-Rename-a-channel

**Comment by trackleft** [comment]
Also need to update https://github.com/az-digital/az_quickstart/blob/main/CONTRIBUTING.md?plain=1#L17
