### ISSUE TITLE
Update Drupal core to 9.4.14 for SA-CORE-2023-005 (2.5.x)

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#2350]
## Problem/Motivation
https://www.drupal.org/sa-core-2023-005

## Proposed resolution
https://www.drupal.org/project/drupal/releases/9.4.14
https://www.drupal.org/project/drupal/releases/9.4.13

**Comment by trackleft** [comment]
Closed by https://github.com/az-digital/az_quickstart/pull/2351
