### ISSUE TITLE
Add better metatag defaults for quickstart.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#2357]
## Motivation
Since the AZ SEO module was launched a lot of improvements to Quickstart have occurred without updating az_seo with new defaults that take advantage of those improvements.

### Is your feature request related to a problem? Please describe.
My site's metatags are incomplete when first installing quickstart.

## Proposed Resolution

Suggestions should be added as comments on this issue.

## Disclaimer

Since Quickstart already includes an incomplete default setting file for this config Arizona Digital owns the config until it is changed on an individual site, at which time, that site owns that configuration.

## More context

At the moment the defaults are managed in this [file](https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_seo/config/quickstart/metatag.metatag_defaults.node.yml) and only contains three tags

```
  description: '[node:field_az_summary]'
  canonical_url: '[node:field_az_link:uri]'
  title: '[node:title] | [site:name]'
```

The Quckstart 1 implementation https://bitbucket.org/ua_drupal/ua_quickstart/src/7.x-1.x/modules/custom/uaqs_seo/

Historically, tokens were used in Quickstart 1 for defaults.  [Quickstart 2 also includes the token module](https://github.com/az-digital/az_quickstart/blob/main/composer.json#L108), and can be leveraged here.

## Current default permissions for metatags
<img width="1656" alt="Screenshot 2023-04-20 at 12 18 54 PM" src="https://user-images.githubusercontent.com/1023167/233469735-a670fbcb-7fa5-4147-b819-2baf4df53b7b.png">

**Comment by trackleft** [comment]
## Current default permissions for metatags
<img width="1656" alt="Screenshot 2023-04-20 at 12 18 54 PM" src="https://user-images.githubusercontent.com/1023167/233469735-a670fbcb-7fa5-4147-b819-2baf4df53b7b.png">

**Comment by trackleft** [comment]
`url-canonical`  ->  custom token [az-canonical-url](https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_core/az_core.module#L186-L201)
`rights` ->  `© [current-date:custom:Y] The Arizona Board of Regents on behalf of <a href="https://www.arizona.edu" target="_blank">The University of Arizona</a>.'`
`generator`  -> Arizona Quickstart (https://quickstart.arizona.edu)

**Comment by trackleft** [comment]
We do need to be able to automatically change the robots tag if there is an external link value in the summary link field to 
```
    index: 0
    follow: 0
    noindex: true
    nofollow: true
```

**Comment by bberndt-uaz** [comment]
Resources related to social media previews:

- https://css-tricks.com/essential-meta-tags-social-media/
- https://dev.to/shadowfaxrodeo/i-tested-every-link-preview-meta-tag-on-every-social-media-and-messaging-app-so-you-dont-have-to-it-was-super-boring-39c0
- For testing: https://metatags.io/
- https://developers.facebook.com/docs/sharing/webmasters
- https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image
