### ISSUE TITLE
Allow displaying images as linked images

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#2366]
## Motivation
Sometimes I just want to use an image as a link, (especially using the natural size display mode)

According to the W3C there are accessibility concerns with using images as links, however there is a definite allowable use-case with the[ functional image sub-category](https://www.w3.org/WAI/tutorials/images/functional/#logo-image-within-link-text). 

### Is your feature request related to a problem? Please describe.
I can't create sponsor logos that link to my sponsors.

## Proposed Resolution

Add an option to CKEditor for wrapping non interactable media with a link

Possible solution https://www.drupal.org/project/drupal/issues/3075527

### Describe the solution you'd like

Use built-in ckeditor link button to wrap media(non-interactable) that I embed in a link.
Not good for iframes, embeds, content, blocks etc, but should be allowed for images.

### Describe alternatives you've considered
Alternatively, we could just allow embedding images styles OR media display mode when choosing how to display images, bypassing this whole problem.

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Anonymous user (view embedded images)
- Authenticated user (view embedded images)
- Content editor (embed images by style rather than display mode)
- Content administrator (embed images by style rather than display mode)
- Administrator (Not sure how this affects images that are replaced after initial upload.)

## Additional context
Fairly good guide on how to use linked images https://sc.edu/about/offices_and_divisions/digital-accessibility/guides_tutorials/alternative_text/linked-images/index.php

**Comment by joeparsons** [comment]
Potential related concern: Manually added inline images in text fields are not necessarily tracked by Drupal (file usage).
