### ISSUE TITLE
Redirect migration redirects the wrong node if using the `/node/*` path instead of the aliased path

### ISSUE THREAD

**Issue by akslay** [az-digital/az_quickstart#2371]
## Problem/Motivation
For migrated redirects, the incorrect node ends up getting redirected if that redirect is using the `/node/*` path instead of the aliased path. 

For example, a redirect source of `/node/46` on the source site ends up redirecting the incorrect node on the migrated site, due to changes in node ID's during the migration process.

## Proposed resolution
Is there a way in the migration table to take the source node ID from the redirect, and then update that redirect on the migrated site to be the proper (new) node ID? 

### Expected behavior

Redirects using `/node/*` as the source path should still function correctly on the migrated site, instead of redirecting the incorrect page that now has the same node ID.

**Comment by joeparsons** [comment]
Looks like our `az_redirects` migration currently transforms node/term IDs in the `redirect` (destination) value and not the `source` value of the redirects imported from the source site.  It should probably be doing both (?)
