### ISSUE TITLE
Add Flag module to Quickstart

### ISSUE THREAD

**Issue by mrbeiley** [az-digital/az_quickstart#2375]
## Motivation
I wanna be able to flag content to be included/excluded in specific views.

### Is your feature request related to a problem? Please describe.
No.

## Proposed Resolution
Add Flag module to at least the composer file.

### Describe the solution you'd like
Enable Flag module by default.

### Describe alternatives you've considered
Promoted checkbox on content, sticky checkbox on content.

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Anonymous user
- Authenticated user
- Content editor: has the ability to flag
- Content administrator: has the ability to administer flags
- Administrator

## Additional context
For news.arizona.edu redesign.

**Comment by joshuasosa** [comment]
I see that 'promoted' and 'sticky' were considered alternatives. What is the reason for choosing Flag instead of one of those built-in options?

**Comment by joshuasosa** [comment]
It sounds like a UI convenience tool: not required to meet the desired functionality (marking stories as featured), but a nicety for content administration. Thanks for the context!
