### ISSUE TITLE
Configure how taxonomy term pages should display 

### ISSUE THREAD

**Issue by Krystation** [az-digital/az_quickstart#2383]
View: category pages
The categories for each article is selected when editing the page: https://www.screencast.com/t/Lu39IC4Az3
Screenshot: https://www.screencast.com/t/MYpq1dPYnxU
Example location: https://news.arizona.edu/arts

This open issue should provide this view: https://github.com/az-digital/az_quickstart/issues/735
Adding the needs of Comms to this ticket will be helpful.
- Cameron

Link to full News & UA@Work Content Types audit: https://docs.google.com/presentation/d/1hdlMg5gv_h09DvoCiErIOMu-mtc3M402GFAMcnGz4Ko/edit?usp=sharing

**Comment by trackleft** [comment]
Will help with #2129

**Comment by joeparsons** [comment]
This basically duplicates #735 but since this issue already has an in-progress PR, we'll close the old issue and keep this one.

**Comment by joeparsons** [comment]
(Closed by mistake)
