### ISSUE TITLE
View: External Story Feed

### ISSUE THREAD

**Issue by ewlyman** [az-digital/az_quickstart#2407]
Content type: External Story
View: external story feed
Screenshot: https://www.screencast.com/t/hDDo7ozkX
Location: https://news.arizona.edu/news/ua-in-the-news

Link to full News & UA@Work Content Types audit: https://docs.google.com/presentation/d/1hdlMg5gv_h09DvoCiErIOMu-mtc3M402GFAMcnGz4Ko/edit?usp=sharing

Module for this view already exists --integrating with az_quickstart issues queue

**Comment by trackleft** [comment]
Any content with a value in field_az_link could possibly be considered an external story.

**Comment by joeparsons** [comment]
We're going to close this per discussion in 2023-05-24 AZ Digital workshop.  It seems this doesn't need to be added to Quickstart but can instead be a custom view on the news.arizona.edu site.
