### ISSUE TITLE
AJAX error preventing removal of event instances

### ISSUE THREAD

**Issue by akslay** [az-digital/az_quickstart#2412]
## Problem
![Screenshot 2023-05-17 at 10 51 16 AM](https://github.com/az-digital/az_quickstart/assets/52931751/84869c21-15ce-491a-bb1b-5b0475665830)

When attempting to remove an individual instance of a repeating event, an AJAX error prevents you from proceeding. Unable to get past "remove instance" screen. This is present in 2.6.3 and also prior versions of QS.

An error is also logged in the Drupal site logs:
```ArgumentCountError: Too few arguments to function Drupal\smart_date_recur\Controller\Instances::__construct(), 0 passed in /code/web/modules/contrib/smart_date/modules/smart_date_recur/src/Form/SmartDateRemoveInstanceForm.php on line 143 and exactly 2 expected in Drupal\smart_date_recur\Controller\Instances->__construct() (line 73 of /code/web/modules/contrib/smart_date/modules/smart_date_recur/src/Controller/Instances.php)```

**Comment by bberndt-uaz** [comment]
The sites affected show that the Smart Date version installed is 3.7.0. [Smart Date version 3.7.2](https://www.drupal.org/project/smart_date/releases/3.7.2) should fix this issue. This version will be enabled in Quickstart with the release of Quickstart 2.6.5, which will include the PR for issue #2286.

**Comment by joeparsons** [comment]
Fixed by #2287
