### ISSUE TITLE
Implement az_badge view mode for all taxonomy vocabularies that are enabled by default.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#2424]
It would make sense to implement an `az_badge` display for each taxonomy that is enabled by default.

So far we only have an implementation for [az_person_categories](https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_person/config/install/core.entity_view_display.taxonomy_term.az_person_categories.az_badge.yml) and `az_person_categories_secondary`

IMHO, we can just make 3 copies of the linked file.
```
core.entity_view_display.taxonomy_term.az_news_tags.az_badge.yml
core.entity_view_display.taxonomy_term.az_event_categories.az_badge.yml
core.entity_view_display.taxonomy_term.az_page_categories.az_badge.yml
```

Extra credit, create the same display for additional vocabularies that are off by default.

**Comment by trackleft** [comment]
See PR Here: https://github.com/az-digital/az_quickstart/pull/2425

**Comment by joeparsons** [comment]
Will help with #2129
