### ISSUE TITLE
Content administrators should be allowed to manage URL aliases

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#2431]
## Problem/Motivation
It came to my attention that content administrators were not able to mange their own URL aliases.

### Describe the bug
Content administrators do not have the appropriate permissions.

### To Reproduce
Log in as content administrator
Navigate to `/admin/config/search/path/add`
See access denied.

## Proposed resolution
Check the appropriate checkbox for the permission.
![image](https://github.com/az-digital/az_quickstart/assets/1023167/10151120-5b68-40a2-bf92-7b9422295774)

### Expected behavior

As a content administrator I expect to be able to manage my own url aliases.

**Comment by bberndt-uaz** [comment]
For documentation on quickstart.arizona.edu, we could consider adding content to the [Redirects](https://quickstart.arizona.edu/site-organization/redirects) page (and possibly renaming it) or creating a new page in the Site Admin section about managing aliases.
