### ISSUE TITLE
Layout Builder full-width elements conflict with theme's sidebar

### ISSUE THREAD

**Issue by akslay** [az-digital/az_quickstart#244]
## Problem/Motivation
When using a full-width element on a Flexible Page in addition to a sidebar, the full-width element is no longer against the left-most edge of the screen. Instead, the element is pushed slightly over to the right, causing the full-width element to stick out past the natural width of the screen.

### To Reproduce
Add a full-width element to a Flexible Page, and include a sidebar on that page.

## Proposed resolution
Uncertain of solution yet; need to debug the issue.

### Expected behavior
Full-width elements should remain against the left-most edge of the screen with or without the presence of a sidebar.

##  Screenshots
![fullwidth_content_sidebar_issue](https://user-images.githubusercontent.com/52931751/86979233-a3937980-c135-11ea-9f11-eab334018118.png)

**Comment by danahertzberg** [comment]
No longer using layout builder
