### ISSUE TITLE
Now that the Digital Asset Library integration is stable, we should enable it by default.

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#2483]
## Motivation
The university has invested a significant amount of time and money to implement this Digital Asset Library. We should make it as easy to use as we can.

### Describe the solution you'd like
I would like the Digital Asset Library integration to be enabled by default. 

### Describe alternatives you've considered
We may also want to consider a database update to enable it on existing sites, but that might be too far.

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Anonymous user
- Authenticated user
- Content editor
- Content administrator
- Administrator (will no longer be required to enable this module on new site installs)

**Comment by joeparsons** [comment]
Merged.
