### ISSUE TITLE
Menu blocks appearing on pages that they should not appear on.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#2495]
## Problem/Motivation
See https://demo.quickstart.arizona.edu/news

<img width="1221" alt="image" src="https://github.com/az-digital/az_quickstart/assets/74572157/945bfd03-b064-4eb1-bf2c-c7b4a95e10b8">

**Comment by bberndt-uaz** [comment]
When testing locally, I was able to resolve the issue with the News page by updating [block--az-barrio-sidebar-menu.html.twig](https://github.com/az-digital/az_quickstart/blob/5d374b34186bbda39a8a60e4e6bda1d650199d89/themes/custom/az_barrio/templates/blocks/block--az-barrio-sidebar-menu.html.twig#L48-L50) to check if the menu has any items.

Before:
```twig
  {{ title_prefix }}
  <h2{{ title_attributes.setAttribute('id', heading_id).addClass('h4').addClass('mt-md-5') }}>{{ configuration.label }}</h2>
  {{ title_suffix }}
```

After:
```twig
  {% if content['#items'] %}
    {{ title_prefix }}
    <h2{{ title_attributes.setAttribute('id', heading_id).addClass('h4').addClass('mt-md-5') }}>{{ configuration.label }}</h2>
    {{ title_suffix }}
  {% endif %}
```

Would this be an acceptable solution?

**Comment by trackleft** [comment]
That could work, does it mess with the main nav?
