### ISSUE TITLE
Reorder people row weight input boxes don't show values

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#2497]
### Describe the bug
When reordering people by row weight, the text field is not large enough to show the inputted value.
[Screen recording of the bug](https://arizona.box.com/s/od1z8x59d6aft0lpu9pgfmxxnw7zicub)

### To Reproduce

1. Add people content
2. Navigate to /admin/az-person/reorder-people
3. Click Show row weights
4. Attempt to input a value into the row weight field

## Proposed resolution
Need to investigate solution

### Expected behavior
Row weight fields should show values and allow for inputs to be seen.

**Comment by HenryzGreenberg** [comment]
The field is now readable when a value is entered. done
