### ISSUE TITLE
Update Trellis Event Importer to use Trellis Event Search API

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#2572]
## Motivation
I want to be able to search/filter for the event I made in Trellis so I can select it to show up on my website.

### Requirements
- Update Quickstart event search to use Enterprise Attributes from Trellis
- Master calendar vs Quickstart calendar feature gap review
- Provide detail page or modal for Master calendar?

### Describe the solution you'd like
Add filters on top of current ID paste box to be able to search and filter events coming in from the feed.

## Additional context
Jira ticket: https://jira.arizona.edu/browse/WEBTEAM-15700

Filters to be added to new content page.
![image](https://github.com/az-digital/az_quickstart/assets/59745109/a8f8f940-4503-4ee7-9a0a-6504fc6b8e78)

**Comment by camikazegreen** [comment]
Can we also keep the Event ID as one of the search options, or as an alternative? It's always nice to have the "I want exactly this event" option as both a sanity check (Is the importer even pulling in my event...?) and also in the case when I have it handy, and don't want to sort through all the events returned with the filters to find it.

**Comment by camikazegreen** [comment]
We should also consider what it would take to allow a "set it and forget it" option for importing events automatically that meet their set filter requirements.
