### ISSUE TITLE
Update the Zoom room for Arizona Digital meetings

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#2591]
## Conditions of satisfaction
- [x] Should use an alias such as https://arizona.zoom.us/my/azdigital
- [x] Should be set to use the "No Fixed Time" option
- [x] Should have security settings so that authentication is required for joining

## Follow up tasks
- [ ] All known references to our Zoom room should be updated to reflect the new meeting

**Comment by joeparsons** [comment]
This has been completed.
