### ISSUE TITLE
Add context aware behavior for opening external links in a new tab.

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#2624]
### Is your feature request related to a problem? Please describe.
When looking at a calendar of events, users might be browsing events rather than looking for a specific event. In the current iteration, if someone clicks on a Trellis Event they are taken to a new website kind of unexpectedly and lose the context of the other events on the calendar.

This is a request from Pila as a requirement for the University Calendar.

### Describe the solution you'd like
If an Event is going to take you to a new website (like an imported Trellis Event), then it should open in a new tab, so that people don't lose their place on the calendar.

### Describe alternatives you've considered
An alternative approach would be to stay on the site and display the Event node of the imported event, with an option to click out to events with additional Registration or Session information.

**Comment by bberndt-uaz** [comment]
Context regarding opening links in new tabs/windows:

- https://www.w3.org/TR/WCAG20-TECHS/G200.html
- https://www.nngroup.com/articles/new-browser-windows-and-tabs/
- https://webaim.org/techniques/hypertext/hypertext_links#new_window

**Comment by danahertzberg** [comment]
Consider a whitelist of domains that open in a new tab/window
- Trellis events
- Wildcard for PDFs on the site
- Box links
- Google doc links
- Dropbox
- OneDrive

Add link text
- Link opens in new window

**Comment by danahertzberg** [comment]
Follow up ticket:
- Have admin edit whitelist in site-specific settings (with sensible defaults)

**Comment by trackleft** [comment]
When not in the calendar context, should external links also open in a new tab? For example the front page of a site.

**Comment by trackleft** [comment]
All the use cases that I know of
- links to imported events within the calendar context
- links to documents like PDF or word docs
- external links to sites that require login and are not covered by the University’s privacy policy.
- Links to content where you need to ensure the current page isn’t lost (like reference to instructions or another reference site to complete a form)

**Comment by danahertzberg** [comment]
> When not in the calendar context, should external links also open in a new tab? For example the front page of a site.

I would say no here. External links should override the existing URL except in the case of needing the current site to remain open.
