### ISSUE TITLE
Create testable prototype of Layout Builder flexible page.

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#263]
## Conditions of satisfaction
- [ ] Should be ready for Shoshana to use in User Testing
- [ ] Should be in a stable environment (Not Probo)
- [ ] The page should have similar page elements as the front page of kitten: https://kitten.ltrr.arizona.edu/
- [ ] Should have enough page elements to be able to User Test the reordering functionality.

**Comment by joeparsons** [comment]
Changes that were needed to sandbox Quickstart site on Pantheon to fix various layout builder styling issues (we need to make these improvements in Quickstart):

- Additional CSS styles copied from @akslay's D8 Registrar's Office sandbox site (added via Asset Injector module for now)
- Changed the display settings for the background image block type so it’s targeting “background_image” and not “background_wrapper”
- Fixed the layout builder style for the “card” class (removed “az” from the class)
