### ISSUE TITLE
Marketing cloud integration: Add additional displays for events or disable the link to irrelevant displays for news and events in admin view.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#2671]
## Motivation
I would like to not see an error page when choosing my layout.

<img width="1681" alt="image" src="https://github.com/az-digital/az_quickstart/assets/1023167/5844b549-6b21-46b0-9caa-f12362b98030">

Clicking on any of the abobove links takes me to a page like this
<img width="400" alt="image" src="https://github.com/az-digital/az_quickstart/assets/1023167/14aecf60-9f8a-40ab-9572-e42d39ba2396">

The inverse is also an issue for news, if I click on Event Layout.

**Comment by danahertzberg** [comment]
[trackleft](https://github.com/trackleft) commented [last week](https://github.com/az-digital/az_quickstart/pull/2722#issuecomment-1737761882) • 
FYI, to remove links that don't exist, and add click to copy functionality, you could probably extend or copy this plugin https://git.drupalcode.org/project/drupal/-/blob/11.x/core/modules/views/src/Plugin/views/field/EntityLink.php

**Comment by trackleft** [comment]
I think that this whole feature should be customize-able, so with that, we need to find a way to add or remove enabled displays with a click.

To me, this means either adding some identifier to the display mode denoting that it is an email display mode type, or add config for this module where we can set display modes as email display mode types.

<img width="1703" alt="image" src="https://github.com/az-digital/az_quickstart/assets/1023167/20a2e969-7137-4e80-895e-0d02a10baa02">

**Comment by trackleft** [comment]
If we could make the setting page look like this
<img width="1705" alt="image" src="https://github.com/az-digital/az_quickstart/assets/1023167/51fe8e9e-4356-42a2-8668-ba83b7e69331">

We could then get that config when building the view and setting the links.

All of this makes me think we should have an additional "mode" type, in addition to form mode, and display mode, possibly email mode.

**Comment by trackleft** [comment]
Or we could copy how Smart Title does this with a settings form to select the entity type/bundle
<img width="898" alt="image" src="https://github.com/az-digital/az_quickstart/assets/1023167/d9f362cd-1cbd-4d75-9e00-25cc3cce7441">

Then on each display mode a setting:

<img width="1700" alt="image" src="https://github.com/az-digital/az_quickstart/assets/1023167/be10150c-8a65-4cfd-894e-a752c29a4294">

**Comment by danahertzberg** [comment]
I got lost a bit on the smart title-esque solution. I'm not sure we need to go that far.. 🤔
