### ISSUE TITLE
2023-09-8 Patch Releases Plan 2.7.4

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#2707]
## Quickstart 2.7.4
- #2549
- #2683
- #2645
- #2680
- #1152
- #2703
- #2686
- #2688 
- #2699
- https://github.com/az-digital/arizona-bootstrap/issues/887
- #2705 
- #2646
- #2712

**Comment by trackleft** [comment]
### Pick list

```
git cherry-pick 
```

### Release notes snippet

`git log 2.7.3..HEAD --pretty='format:- %s'`

```
```

**Comment by joeparsons** [comment]
I think we missed this one: https://github.com/az-digital/az_quickstart/pull/2700

**Comment by trackleft** [comment]
Ok, I've updated all the things now

**Comment by trackleft** [comment]
https://github.com/az-digital/az_quickstart/releases/tag/2.7.4 Released
