### ISSUE TITLE
Clickable card styling bug, white space showing underneath card image

### ISSUE THREAD

**Issue by CGustafson747** [az-digital/az_quickstart#2736]
Copied over from slack conversation:

Hello, our team had a question on the styling of [cards with the title on the image](https://digital.arizona.edu/arizona-bootstrap/docs/2.0/components/card/#title-on-image) - is it possible to use a card deck with the title on the image, without any body text, that won't show the empty "body text" white space in the card? Here is an example where the extra white space is showing: https://app.screencast.com/TWIVApMhNiXbf 

Catherine Gustafson
this screenshot is from the MarCom dev site (https://dev-marcom-redesign.pantheonsite.io/), whereas the end goal would be to not have any white space (here is 
Tom’s mockup of the same page: https://xd.adobe.com/view/ffca6272-e574-4522-bbf1-bdfa881b037c-aa99/

Cameron Green
I believe the mockup is how it is supposed to behave.

Chris Green
Looks like this empty check no longer works.
https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_card/templates/az-card.html.twig#L31
[az-card.html.twig](https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_card/templates/az-card.html.twig)
  {% if title_style == 'default' or (title_style == 'title-on-image' and (body or link)) %}
<https://github.com/[az-digital/az_quickstart](https://github.com/az-digital/az_quickstart)|az-digital/az_quickstart>az-digital/az_quickstart | Added by [GitHub](https://uarizona.slack.com/services/B01V5LL7L3A)

Chris Green
Or rather, the or link part adds the extra markup.

-----------------------------------------

Let me know if any more examples/screen shots are needed.

Thank you!
Catherine

**Comment by mrbeiley** [comment]
Hello,

After reading through this issue, I'm not sure what to do. 

Can I remove the 'or link' condition? It seems like it's still in use, so I don't think so.

I haven't done much work with .twig files and I'm not totally sure how to change the code or test it. Some beginner's guidance would be much appreciated.

Thanks,
Michael

**Comment by joshuasosa** [comment]
I think `(body or link)` should be `(body|render or link|render)`. Fixes it in my testing.

I'd actually like it to go further and hide body if there's no body no link _title_. Then I could get rid of those empty body boxes on our [solar system site](https://www.lpl.arizona.edu/solarsystem/).

**Comment by mrbeiley** [comment]
> 2547559

I replaced (body or link) with (body|render or link|render), and it's partly working. On XS and SM, the whitespace disappears, but on MD/LG/XL it is still there.

<img width="1148" alt="Screenshot 2023-11-09 at 11 53 59 AM" src="https://github.com/az-digital/az_quickstart/assets/20604868/bffd95ca-9ce1-45c4-ba2d-07d47b712a13">

<img width="1148" alt="Screenshot 2023-11-09 at 11 53 34 AM" src="https://github.com/az-digital/az_quickstart/assets/20604868/30fdc9c8-0014-4aa8-a7a8-8c185045254e">

**Comment by joshuasosa** [comment]
It's actually not there if you look at the HTML. But the card becomes the same height as sibling cards. If you make all 3 cards similar, as in no body nor links, it will display as expected at all breakpoints.
