### ISSUE TITLE
How do we update existing pages using Gutenburg

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#274]
## What is the problem that we want to solve?
Since Gutenburg renders blocks client side and then stores the rendered blocks, how can we make changes to markup without re-editing every page that contains those blocks?

## Conditions of satisfaction
- [ ] The considered options are documented
- [ ] A recommended next step is documented
- [ ] An estimate of time and effort is provided for the recommendation
- [ ] …

**Comment by mschmeling14** [comment]
Closed. Work not performed. Decided to go a different direction.
