### ISSUE TITLE
Error loading CSS library prevents adding paragraphs on node edit form

### ISSUE THREAD

**Issue by bberndt-uaz** [az-digital/az_quickstart#2772]
## Problem/Motivation
On the node edit form, an AJAX error causes inconsistent behavior when trying to add new paragraphs using the Add buttons below the Page Elements.

### Describe the bug
This error occurs on a local build from main as well as various Probo builds. When trying to add a new paragraph, especially to add a second paragraph to a page, no paragraph is added and the following errors are logged in the console (in Chrome):

> Refused to execute script from 'https://fonts.googleapis.com/css?family=Material+Icons+Sharp' because its MIME type ('text/css') is not executable, and strict MIME type checking is enabled. @ loadjs.min.js?v=4.2.0:1
> 
> An error occurred during the execution of the Ajax response: The following files could not be loaded: https://fonts.googleapis.com/css?family=Material+Icons+Sharp20  @ ajax.js?v=10.1.4:1118

It seems the CSS library is somehow being treated as a JS library instead. We are working to identify the cause of this issue. Disabling CSS and JS aggregation does NOT resolve this issue.

### To Reproduce

1. Go to Content and click the button to Add content
2. Click on the Page content type
3. Click on any Add button to add a paragraph (such as a Text paragraph)
4. Click on any Add button again
5. Observe that the additional page element is not loaded and an error is logged in the console

## Proposed resolution
TBD

### Expected behavior
Users should be able to add paragraphs without triggering any console errors.

**Comment by tadean** [comment]
We have isolated this to a regular expression of `/(^css!|\.css$)/` in `loadjs`, an async loader library that @joeparsons noticed has been in Drupal for a while, but is newly being used in 10.1 for loading arrays of css files on ajax requests.

https://www.drupal.org/project/drupal/issues/3110517

In the case of the Material Icons, the library doesn't recognize the url as being a css file, so it includes it as a script instead.

**Comment by tadean** [comment]
Here is what the `loadjs` loader places in the DOM upon processing the library:
```
<script src="https://fonts.googleapis.com/css?family=Material+Icons+Sharp" async="" rel="stylesheet" media="all" href="https://fonts.googleapis.com/css?family=Material+Icons+Sharp"></script>
```
Note the inclusion of it as a script, rather than a CSS link.
