### ISSUE TITLE
Update Global Footer with new Twitter Icon

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#2800]
Twitter updated their icon, https://github.com/az-digital/az-icons/pull/38

Need to update demo content with new icon class .`az-icon-x-twitter`

https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_global_footer/data/az_global_footer.json#L393-L406

Create a database update to change the class for existing sites similar to this one 
https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_global_footer/az_global_footer.install#L48-L79

Shouldn't need to update the library, since it is using the CDN and is using the main branch.
https://github.com/az-digital/az_quickstart/blob/main/themes/custom/az_barrio/includes/common.inc#L11

**Comment by mrbeiley** [comment]
After updating the demo content and updating the database, how do I test?

https://github.com/az-digital/az_quickstart/tree/issues/2800-x-twitter-updates

**Comment by akslay** [comment]
After creating a pull request, a test build will be automatically created for you on Probo. You should be able to just use that build to visually check that the footer is using your updated icon.

**Comment by trackleft** [comment]
This is blocked by a release v1.0.1 of https://github.com/az-digital/az-icons  or https://github.com/az-digital/az-icons/pull/22
