### ISSUE TITLE
Standard text format settings page produces a console error related to CKEditor 5

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#2827]
## Problem/Motivation
During our testing on https://28-beta1-azs-quickstart.pantheonsite.io the Embed Content and Embed Blocks were both missing from the CK Editor in the Standard text formatter. 

The [Standard text format settings page](https://28-beta1-azs-quickstart.pantheonsite.io/admin/config/content/formats/manage/az_standard?destination=/admin/config/content/formats) produces a console error related to CKEditor 5:
```
drupal.js?v=10.1.5:64 Uncaught TypeError: Cannot read properties of undefined (reading ‘id’)
    at ckeditor5.admin.js?s2c3nt:568:15
    at Array.map (<anonymous>)
    at ckeditor5.admin.js?s2c3nt:565:50
    at Array.forEach (<anonymous>)
    at Object.attach (ckeditor5.admin.js?s2c3nt:537:9)
    at drupal.js?v=10.1.5:166:24
    at Array.forEach (<anonymous>)
    at Drupal.attachBehaviors (drupal.js?v=10.1.5:162:34)
    at drupal.init.js?v=10.1.5:32:12
    at HTMLDocument.listener (drupal.init.js?v=10.1.5:20:7)
```

### To Reproduce
We aren't sure what caused this problem on this site, since it seems to be working correctly on most of the other sites that we are testing on.

### Expected behavior
Installation of the 2.8 release should not remove the embedding options from the CK Editor on _any_ sites.

##  Screenshots
[Expected Toolbar](https://quickstart.arizona.edu/sites/default/files/styles/az_large/public/2022-04/wysiwyg.png?itok=N84d6Db3) Follow link and see section 9.
![wysiwyg](https://github.com/az-digital/az_quickstart/assets/471936/174b72fc-8c89-4483-b9b6-dde30cd827f6)

Actual Toolbar
![Editor Toolbar Labled](https://github.com/az-digital/az_quickstart/assets/1509771/6da3c3f2-80e1-4157-9247-7dc450a07170)

**Comment by trackleft** [comment]
<img width="635" alt="image" src="https://github.com/az-digital/az_quickstart/assets/1023167/1edc9ef2-9117-4779-8ffe-6f3111e37015">

**Comment by trackleft** [comment]
I was able to fix this locally, however, I'm not sure which step actually resolved it.

1. `composer reinstall drupal/embed` 
<img width="783" alt="image" src="https://github.com/az-digital/az_quickstart/assets/1023167/66b17dbc-8e34-4685-a7b9-20984baead24">
2. `composer reinstall drupal/entity_embed`
<img width="855" alt="image" src="https://github.com/az-digital/az_quickstart/assets/1023167/9ae583b7-bf40-4956-badf-4c877d276e5a">
(So far still receiving the error)
3. `lando en -y config_import_single`
4.` lando drush cis web/profiles/custom/az_quickstart/modules/custom/az_paragraphs/config/optional/embed.button.az_embed_content.yml`
I then see this error
<img width="1384" alt="image" src="https://github.com/az-digital/az_quickstart/assets/1023167/fe153d43-15e1-4843-ad53-4dfdba89ae69">
5. then run this command ```lando drush en -y views_remote_data```

6. this ` lando drush cis web/profiles/custom/az_quickstart/modules/custom/az_paragraphs/config/optional/embed.button.az_embed_content.yml` then is run and resolves the issue.

**Comment by trackleft** [comment]
Possibly related to  issue #2825

**Comment by joeparsons** [comment]
This issue is still affecting some sites we're testing beta2 on.
