### ISSUE TITLE
All external links opening in new tab instead of only intended external links

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#2829]
## Problem/Motivation
The 2.8 release includes functionality to open certain kinds of external links, such as documents and Trellis Events in a new tab by default. This is working, but it is also causing all other external links to open in a new tab, which is not supposed to happen.

**Example test links**

- [Trellis event link](https://events.trellis.arizona.edu/f44lNu67/5a3U3nIwLYK?_gl=1*1ncy4ls*_ga*OTMyMDU0ODAzLjE2OTE0MjM0NjM.*_ga_7PV3540XS3*MTY5NTY3MDQ4NC4zNS4xLjE2OTU2NzA0OTUuNDkuMC4w)
- [Google doc](https://docs.google.com/document/d/1hYZIm553E7gO_bCxr1K7l0NN_v137k6jNlkUyyzCroY/edit?usp=sharing)
- [Box link](https://arizona.box.com/s/wasg24vebx58n5sv13n9zg68aox59bh0)
- [OneDrive link](https://emailarizona-my.sharepoint.com/:x:/g/personal/danahertzberg_arizona_edu/EcyTb-u8uGpHnmeogdAYRqUBnVZjOPKMxX5v5OB6XuA6Sw?e=KTFRGx)
- [Dropbox](https://www.dropbox.com/scl/fi/8wcc4shset2qkbt3qc6wh/21-UArizona-Dynamic-Template.pptx?rlkey=ms6028rbz9m2nrje7n907o9fg&dl=0)
- [Sample Document.pdf](https://github.com/az-digital/az_quickstart/files/12894683/Sample.Document.pdf)

**Here’s an updated list of all the beta testing sites with links to their multidevs:**

- :white_check_mark: azs-quickstart: [qs-2825-azs-quickstart.pantheonsite.io/dana](http://qs-2825-azs-quickstart.pantheonsite.io/dana)
   - All external links open in new tab
- :white_check_mark: azs-capla: [azqs28-azs-capla.pantheonsite.io/dana](http://azqs28-azs-capla.pantheonsite.io/dana)
   - All external links open in new tab
- :white_check_mark: sasg-rec: https://pre-release-sasg-rec.pantheonsite.io/dana
   - All external links open in new tab
- :white_check_mark: azs-law: https://azqs28-azs-law.pantheonsite.io/dana
   - All external links open in a new tab
   - Messing with extlink settings on this site
- :white_check_mark: azs-eller: [pre-release-azs-eller.pantheonsite.io](http://pre-release-azs-eller.pantheonsite.io/)
- :white_check_mark: sasg-financialaid: [pre-release-sasg-financialaid.pantheonsite.io](http://pre-release-sasg-financialaid.pantheonsite.io/)
- :white_check_mark: azs-thinktank: [pre-release-azs-thinktank.pantheonsite.io](http://pre-release-azs-thinktank.pantheonsite.io/)
- :white_check_mark: sasg-registrar: [azqs28-sasg-registrar.pantheonsite.io/](http://azqs28-sasg-registrar.pantheonsite.io/)
- :white_check_mark: azs-cert: [pre-release-azs-cert.pantheonsite.io/](http://pre-release-azs-cert.pantheonsite.io/)
- :white_check_mark: azs-crm: [28-beta1-azs-crm.pantheonsite.io](http://28-beta1-azs-crm.pantheonsite.io/)

**Comment by camikazegreen** [comment]
I have turned on the External Links icon to make it easier to identify which links are being identified as External by the module.

**Comment by camikazegreen** [comment]
This is actually working exactly opposite from what is intended. Any links that are matched by the whitelist are treated as internal links and open in the same tab, while all other links are opened in a new tab.

(The PDF functionality is working perfectly since it is defined in a separate field titled "Include fields that match the pattern". Maybe we should put all of our patterns in this field?)

**Comment by danahertzberg** [comment]
Other sites to check
- https://pre-release-azs-eller.pantheonsite.io/
- https://pre-release-azs-thinktank.pantheonsite.io/

**Comment by danahertzberg** [comment]
Example test links

- [Trellis event link](https://events.trellis.arizona.edu/f44lNu67/5a3U3nIwLYK?_gl=1*1ncy4ls*_ga*OTMyMDU0ODAzLjE2OTE0MjM0NjM.*_ga_7PV3540XS3*MTY5NTY3MDQ4NC4zNS4xLjE2OTU2NzA0OTUuNDkuMC4w)
- [Sample Document.pdf](https://17dd72e3-b662-468c-acaf-1d4a01bea572.probo.build/sites/default/files/2023-09/Sample%20Document.pdf)
- [Google doc](https://docs.google.com/document/d/1hYZIm553E7gO_bCxr1K7l0NN_v137k6jNlkUyyzCroY/edit?usp=sharing)
- [Box link](https://arizona.box.com/s/wasg24vebx58n5sv13n9zg68aox59bh0)
- [OneDrive link](https://emailarizona-my.sharepoint.com/:x:/g/personal/danahertzberg_arizona_edu/EcyTb-u8uGpHnmeogdAYRqUBnVZjOPKMxX5v5OB6XuA6Sw?e=KTFRGx)
- [Dropbox](https://www.dropbox.com/scl/fi/8wcc4shset2qkbt3qc6wh/21-UArizona-Dynamic-Template.pptx?rlkey=ms6028rbz9m2nrje7n907o9fg&dl=0)

**Comment by danahertzberg** [comment]
Seems like this module is not working as expected with the settings provided. We likely need some custom work to make it work.

**Comment by danahertzberg** [comment]
Next steps:
1. Revert to this PR https://github.com/az-digital/az_quickstart/pull/2762 @joeparsons 
2. Develop custom module to achieve desired results

**Comment by joeparsons** [comment]
> Next steps:
> 
> 1. Revert to this PR [Closes #2624: Open specific external links in new tab  #2762](https://github.com/az-digital/az_quickstart/pull/2762) @joeparsons
> 2. Develop custom module to achieve desired results

@bberndt-uaz Is going to create a PR that utilizes the pattern matching settings provided by the module instead.
