### ISSUE TITLE
Duplicate Blocks tabs on the Admin Content page

### ISSUE THREAD

**Issue by bberndt-uaz** [az-digital/az_quickstart#2845]
## Problem/Motivation
There are two Blocks tabs on the Admin Content page at /admin/content. The first Blocks tab links to /admin/content/block and displays a view without any sorting or filtering functionality. The second Blocks tab links to /admin/content/blocks and includes sorting and filtering.

### To Reproduce
Visit the page at /admin/content and observe the duplicate tabs.

## Proposed resolution
Joe found that the Drupal core block content view **does** include the sorting and filtering functionality. There may be an issue with the custom block content view that we installed in this pull request:

- [Include a blocks tab within content admin page options](https://github.com/az-digital/az_quickstart/pull/645)

With the update to Drupal 10.1, we removed the custom block content view that we had previously added:

- [Upgrade Drupal core to 10.1.x](https://github.com/az-digital/az_quickstart/pull/2587)

However, there is some additional cleanup we can do to complete the removal of our custom view.

### Expected behavior

Only one Blocks tab should be displayed on the Admin Content page. The tab should link to a page that allows users to sort and filter custom blocks.

#### First Blocks tab at /admin/content/block
<img width="1638" alt="image" src="https://github.com/az-digital/az_quickstart/assets/74572157/b05ed6a9-a390-44f6-8f96-ff3bd602a104">

#### Second Blocks tab at /admin/content/blocks
<img width="1643" alt="image" src="https://github.com/az-digital/az_quickstart/assets/74572157/5bb2f3ee-9633-4962-a479-925d98086a75">

#### Example of a site with additional tabs
<img width="828" alt="image" src="https://github.com/az-digital/az_quickstart/assets/74572157/0cc8be8e-1050-4be3-bde6-890852230010">

## Additional context

- [Block content view in the Drupal core block_content module](https://git.drupalcode.org/project/drupal/-/blob/10.1.x/core/modules/block_content/config/optional/views.view.block_content.yml)
- [Post update functions for the Drupal core block_content module](https://git.drupalcode.org/project/drupal/-/blob/10.1.x/core/modules/block_content/block_content.post_update.php)

**Comment by joeparsons** [comment]
This warnings that showed up when applying DB updates on existing sites in conjunction with testing beta2 may be related:
```
Warning: ] Undefined array key "_core" ConfigMerger.php:144
Warning: ] Undefined array key "_core" ConfigMerger.php:144
Warning: ] Undefined array key "page_1" ConfigMerger.php:144
```
