### ISSUE TITLE
Create Accordions paragraph

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#285]
**Name:** Accordions
**Description:** Add expandable/collapsable groups of content

**Requirements:** 
- Ability to add accordions one at a time
- Ability to show accordion expanded or collapsed by default
- Accordion title
- Accordion body (same requirements as Text)

**Notes:**
Requirements are for MVP 1. It would be nice to have the ability to link to a specific accordion pre-expanded in MVP 2.

Bootstrap panels are now cards.

_**Approved by AZ Digital on 9/9/2020**_

**Comment by trackleft** [comment]
For the requirements, can we add HTML structure? For example 
`<div class="accordion" id="ex2_accordionExample">
  <div class="card">
    <div class="card-header" id="ex2_headingOne">
      <h3 class="my-0">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#ex2_collapseOne" aria-expanded="true" aria-controls="ex2_collapseOne">
          Collapsible Group Item #1
        </button>
      </h3>
    </div>
    <div id="ex2_collapseOne" class="collapse show" aria-labelledby="ex2_headingOne" data-parent="#ex2_accordionExample">
      <div class="card-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="ex2_headingTwo">
      <h3 class="my-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#ex2_collapseTwo" aria-expanded="false" aria-controls="ex2_collapseTwo">
          Collapsible Group Item #2
        </button>
      </h3>
    </div>
    <div id="ex2_collapseTwo" class="collapse" aria-labelledby="ex2_headingTwo" data-parent="#ex2_accordionExample">
      <div class="card-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="ex2_headingThree">
      <h3 class="my-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#ex2_collapseThree" aria-expanded="false" aria-controls="ex2_collapseThree">
          Collapsible Group Item #3
        </button>
      </h3>
    </div>
    <div id="ex2_collapseThree" class="collapse" aria-labelledby="ex2_headingThree" data-parent="#ex2_accordionExample">
      <div class="card-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
</div>
`

**Comment by danahertzberg** [comment]
I like including the structure in the requirements. 

Would the card header IDs be the heading words? Or just an auto-generated ID number/value?

Is there a big difference in development for adding the ability to link to a specific pre-expanded accordion versus not adding this? If so, we should save it for MVP 2.

**Comment by trackleft** [comment]
@danahertzberg we should have access to all of the properties of the "entity" or the paragraph item, so as long as we can guarantee that the ID is unique to the page, or more preferable from a development standpoint, to the site, the sky is the limit.

**Comment by trackleft** [comment]
FYI, properties include fields and things like ID and UUID

**Comment by danahertzberg** [comment]
@trackleft Sounds great! Only remaining discussion topic would be around the ability to open multiple accordions vs one at a time. If I recall correctly, we (developers, not me lol) could implement functionality where if one accordion is open, it appends the ID to the URL. And if multiple accordions were open, no ID would be added. If this is the case and/or further discussion is needed, I would still advocate for including this in MVP 2. Keep MVP 1 with the functionality we have now.

**Comment by trackleft** [comment]
@danahertzberg, I believe for the second question, we can have an additional ticket with requirements, like adding configuration for each panel, or panel group, and/or adding ability to link from the panel.

The front end execution for this could be added in fairly easily in MVP 1 as long as we are certain we won't break the thing in  the future with an update.

For example when you link to the collapse panel, you have to link to a visible part of the page, while the click event for collapsing is tied to a button that does not have an ID.

**Comment by trackleft** [comment]
Go here:
https://review.digital.arizona.edu/arizona-bootstrap/feature/93-chris/docs/0.0/components/collapse/#ex2_headingTwo

Add to console
```
if (location.hash === '#ex2_headingTwo') {
var target = $(location.hash).find( '[data-toggle="collapse"]' ).attr('data-target');
$(target).collapse('show');
}
```

**Comment by danahertzberg** [comment]
That all makes sense. I will make another ticket for MVP 2 to add the functionality. I think it makes sense to include the panel IDs in the MVP 1 architecture.
