### ISSUE TITLE
"This link has no URL" error when successfully adding internal link to new text

### ISSUE THREAD

**Issue by natebyerley** [az-digital/az_quickstart#2869]
## Problem/Motivation
Discovered in 2.8 RC1 Testing

### Describe the bug

"This link has no URL" error appears when successfully adding internal link to new text
Note, this does **not** occur when adding an external link

### To Reproduce

1. Add a Text Box paragraph to a page
2. Type some text
3. Add an internal link
4. Approve link by clicking green checkmark
5. Error message appears until text is added after link (error will not appear if text you are adding link to is in the middle of a pagagraph - i.e. has text after it

![Screenshot 2023-10-26 at 12 35 47 PM](https://github.com/az-digital/az_quickstart/assets/97116860/1e024434-2d83-4ef8-914b-5f754b23e97a)

Demo on this page: [https://28rc1-joe-azs-quickstart.pantheonsite.io/node/291/edit](https://28rc1-joe-azs-quickstart.pantheonsite.io/node/291/edit)

## Related Drupal.org Issue with Module ##

Very similar to this Drupal.org issue, but I'm not able to reproduce this in Quickstart 2 exactly: [https://www.drupal.org/project/linkit/issues/3364963](https://www.drupal.org/project/linkit/issues/3364963)

### Expected behavior

Internal link behavior should work like external link behavior currently does in CKE5

### Desktop (please complete the following information):
 - OS: Mac OS 13.5.1
 - Browser Firefox & Safari

**Comment by joeparsons** [comment]
Worth noting: there is a Drupal core issue where the possibility of adding a lot of the functionality provided by the LInkIt module to core is being discussed/considered:
https://www.drupal.org/project/drupal/issues/3317769
