### ISSUE TITLE
Create HTML paragraph

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#287]
**Name:** HTML
**Description:** Add full HTML

**Requirements:** 
- Preview/view source code
- Use HTML text format

**Notes:**
Should this just be a plain field that allows for full HTML without any text editing buttons? Having all the same Text paragraph type buttons could be confusing

_**Approved by AZ Digital on 9/15/2020**_

**Comment by smayden** [comment]
Not sure about other editors (or the exact use cases this would be used for), but making it just HTML with no text editing buttons would make things much harder for me. Sometimes I need to be able to tweak the HTML but much prefer to use the text edit buttons for most things (I'm slow at HTML).

**Comment by danahertzberg** [comment]
Primary uses:
- iFrames
- Script tags
- Change full-width background wrapper padding 
- Previous need for tables/grids

**Comment by danahertzberg** [comment]
Permissions questions:
- Edit HTML text format field?
- Change Standard text format to HTML format?

In favor of adding text format and HTML paragraph

Admins only should have ability to change the format (for marquees, background wrappers, etc)

**Comment by trackleft** [comment]
Consider using https://ace.c9.io/
