### ISSUE TITLE
CKEditor 5 strips classes from div elements

### ISSUE THREAD

**Issue by bberndt-uaz** [az-digital/az_quickstart#2872]
### Describe the bug
Classes cannot be added to div elements in CKEditor 5 since they are stripped by the editor.

### To Reproduce

1. Switch to source mode in the editor
2. Add `<div class="bg-dark">Test</div>` (or any other classes you like)
3. Switch back to normal mode and observe that the text is not styled
4. Switch to source mode and observe that the class attribute has been removed

## Proposed resolution
Update the list of allowed tags for the az_standard text format.

### Expected behavior

Classes should remain as entered for div elements.

**Comment by camikazegreen** [comment]
Is this different than the current behavior in CK Editor 4?

**Comment by bberndt-uaz** [comment]
Yes, in Quickstart 2.7 the class attribute is allowed on div elements.

Source mode:
<img width="311" alt="image" src="https://github.com/az-digital/az_quickstart/assets/74572157/f9d23adc-bed0-4181-b2ff-f38b76da36df">

Normal mode:
<img width="186" alt="image" src="https://github.com/az-digital/az_quickstart/assets/74572157/1b4aa596-0940-4d71-9265-573051bce503">
