### ISSUE TITLE
Different tags allowed in CKEditor settings and Standard text format settings

### ISSUE THREAD

**Issue by bberndt-uaz** [az-digital/az_quickstart#2875]
## Problem/Motivation
After we noticed an [issue with class attributes on div elements in CKEditor 5](https://github.com/az-digital/az_quickstart/issues/2872), @joeparsons suggested that we audit the allowed HTML in the [CKEditor 5 allowed tags for source editing](https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml) to ensure that it lines up with the [allowed HTML for the az_standard text format](https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_media/config/install/filter.format.az_standard.yml#L31).

The CKEditor source editing list will contain fewer tags, as indicated by this help text for that setting:

> A list of HTML tags that can be used while editing source. It is only necessary to add tags that are not already supported by other enabled plugins. For example, if "Bold" is enabled, it is not necessary to add the `<strong>` tag, but it may be necessary to add `<dl><dt><dd>` in a format that does not have a definition list plugin, but requires definition list markup.

Below is a list of differences between the allowed HTML in the two files. The list includes the `<div>` difference to be resolved with issue #2872.
| [editor.editor.az_standard.yml](https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml) | [filter.format.az_standard.yml](https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_media/config/install/filter.format.az_standard.yml) |
| --------- | ----------- |
| `<a class target name id title>` | `<a class target name id title href data-entity-type data-entity-uuid data-entity-substitution>` |
| - | `<br>` |
| - | `<caption>` |
| - | `<code class="language-*">` |
| `<div name id>` | `<div name id class data-*>` |
| `<drupal-media title>` | `<drupal-media title data-entity-type data-entity-uuid alt data-view-mode data-align>` |
| - | `<em>` |
| `<ol type class>` | `<ol type class start>` |
| - | `<pre class="text-align-left text-align-center text-align-right text-align-justify">` |
| - | `<s>` |
| - | `<strong>` |
| - | `<sub>` |
| - | `<sup>` |
| `<td class>` | `<td class rowspan colspan>` |
| `<th class scope>` | `<th class scope rowspan colspan>` |

## Proposed resolution
Determine which differences are relevant and make any necessary updates to the editor config and/or the text format.

### Expected behavior

The allowed HTML for the editor and the text format should function in the same way.

**Comment by bberndt-uaz** [comment]
I tested the elements in the table from the description to see if CKEditor in the latest Quickstart version would strip out any of the elements, attributes, or classes specified in the [az_standard text format](https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_media/config/install/filter.format.az_standard.yml) (the right column above).

| Element | Test Result |
| --------- | ----------- |
| `<a>` | All attributes allowed. |
| `<br>` | Element allowed. |
| `<caption>` | Element allowed (within `<table>`) |
| `<code>` | Element allowed but the class attribute is removed. |
| `<drupal-media>` | All attributes allowed. |
|`<em>` | Element allowed. |
| `<ol>` | All attributes allowed. |
| `<pre>` | Element allowed with all 4 classes. |
| `<s>` | Element allowed. |
| `<strong>` | Element allowed. |
| `<sub>` | Element allowed. |
| `<sup>` | Element allowed. |
| `<td>` | All attributes allowed. |
| `<th>` | All attributes allowed. |

Based on this testing, the only thing specified in the text format that the editor strips out is the class attribute for the `<code>` element. Such classes are not supported in [Arizona Bootstrap](https://digital.arizona.edu/arizona-bootstrap/docs/2.0/content/code/) or [Bootstrap 5](https://getbootstrap.com/docs/5.3/content/reboot/#inline-code), so I think this is not an issue.

**Comment by joeparsons** [comment]
Thanks @bberndt-uaz for looking into this.  Sounds like we're OK for now.  Closing this.
