### ISSUE TITLE
Digital Assets Library browser window is 'mobile sized' on any display

### ISSUE THREAD

**Issue by natebyerley** [az-digital/az_quickstart#2876]
## Problem/Motivation
Discovered in 2.8 RC 1 Testing.  However this issue was not introduced in 2.8.  It is evident on sites with 2.7.5

### Describe the bug
Once logged into the Digital Assets Library, the browser window for media is narrow - almost 'mobile sized' even on desktop.  Will make browsing more difficult.

![Screenshot 2023-10-26 at 6 17 59 PM](https://github.com/az-digital/az_quickstart/assets/97116860/77d837e7-6fc5-47bb-9e41-370d88e8a174)

### To Reproduce

Add an image on this site: https://qs28rc1-azs-capla.pantheonsite.io

## Proposed resolution

Expand browser window for searching the Digital Asset Library

**Comment by trackleft** [comment]
This appears to only be an issue when clicking on embed media within the CKEditor.

Clicking on Add Media in the summary fields section brings up the correctly sized modal.
