### ISSUE TITLE
Create Cards paragraph

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#289]
**Name:** Cards
**Description:** Add text with background settings.

**Requirements:** 
- Fix illegal HTML formatting from QS 1.0

At the paragraph level:
- Ability to add cards one by one (like accordions)
- Select how many columns (pre-defined - see notes, default to 3 columns on large)
-- Phone/Tablet/Desktop
-- Select Desktop size (tablet and phone automatically set)
-- Tablet and phone column settings available in advance settings
- Show/hide card border (show by default)
- Cards should all be same height (using d-flex classes)
- Buttons should align to bottom of cards (using d-flex classes)

At the card level:
- Card media (use default aspect ratio or pre-determined)
- Card title
- Card body (same as Text paragraph)
- Card link (default to red button block, have styling selection, link entire card)
- Background color (pre-determined options, white default)

When saving the page:
- Check for links in body and link field of each card
- If links are in both, don't save and display warning/highlight of problem card

**Design:**
https://review.digital.arizona.edu/arizona-bootstrap/master/docs/0.0/components/card/
One style of card

**Notes:**
Show/hide card border would apply to all cards. Bordered/borderless cards in QS 1.0 would map to these options. Landing grid (deprecated in QS 1.0) would map to this card, with borders applied, link in the Card link field which links the entire card.

**How should the pre-defined column selection appear?**

~ One selection (default to Large: 3 columns, Medium: 3 columns, Small: 1 column):~
 - ~~Large: 3 columns, Medium: 2 columns, Small: 1 column~~
 - ~~Large: 3 columns, Medium: 1 column, Small: 1 column~~
 - ~~Large: 2 columns, Medium: 2 columns, Small: 1 column~~
 - ~~Large: 2 columns, Medium: 1 column, Small: 1 column~~

~Select per screen size (default to 3 large, 3 medium, 1 small):~
- ~~Large: 4/3/2/1 columns~~
- ~~Medium: 4/3/2/1 columns~~
- ~~Small: 4/3/2/1 columns~~

Select large screen size that has default for medium and small sizes (Medium and small sizes should be overrideable in advanced settings)
- Large: 4 (medium 2, small 1)
- Large: 3 (medium 3, small 1)
- Large: 2 (medium 2, small 1)
- Large: 1 (medium 1, small 1)

Dana will include html markup example for display flex on cards

**MVP 2 upgrades could include:**
- Automatically change text color based on background color selection

_**Approved by AZ Digital on 9/9/2020**_

**Comment by danahertzberg** [comment]
Card has a border by default `border: 1px solid rgba(0, 0, 0, 0.125);`

If the border option is turned off, change to `border: 1px solid rgba(0, 0, 0, 0);`

**Comment by danahertzberg** [comment]
@trackleft I think this achieves everything we need for adding cards that wrap while taking into account specified column sizings. 

Note: The `col-xs-#` class is required to be set so display flex works as expected.

```
- card.column-class: Sets the column classes for xs (required), md, and lg.
- card.background-class: Sets the background color.
- card.border-class: Removes the border as needed.
- card.media: The media field of a card.
- card.title: The title field of a card.
- card.body: The body field of a card.
- card.link: The link field on a card.

<div class="row d-flex flex-wrap">
    <div class="{{card.column-class}}">
        <div class="content height-100 pb-4">
            <div class="h-100 d-flex flex-column card {{card.border-class}} {{card.background-class}}">
                {{card.media}}
                <div class="card-body">
                    <h3 class="h5 bold mt-0">{{card.title}}</h3>
                    <div class="card-text">{{card.body}}</div>
                    <div class="mt-auto">{{card.link}}</div>
                </div>
            </div>
        </div>
    </div>
</div>

**Comment by tadean** [comment]
Automation moved this to done on accident.

**Comment by tadean** [comment]
Additional setting specification suggested by @danahertzberg :
Paragraph settings
Cards per row on desktop (1, 2, 3, 4)
— Change options to use numbers instead of words
— Had default pre-selected
— Help text: Choose how many cards appear per row. Additional cards will wrap to a new row. This selection sets the cards per row on desktops with automatic defaults set for tablet and phone. Override cards per row on tablet and phone in Additional options.
Card style (Bordered cards, Borderless cards)
Additional options
Cards per row on tablet (1, 2, 3, 4)
— Has default pre-selected
— Help text: Choose how many cards appear per row. Additional cards will wrap to a new row. This selection sets the cards per row on tablets.
Cards per row on phone (1, 2, 3, 4)
— Has default pre-selected
— Help text: Choose how many cards appear per row. Additional cards will wrap to a new row. This selection sets the cards per row on phones.
Bottom spacing
