### ISSUE TITLE
Update paragraphs_admin for SA-CONTRIB-2023-049

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#2890]
## Problem/Motivation
https://www.drupal.org/sa-contrib-2023-049

## Proposed resolution
Update paragraphs_admin to 8.x-1.5

**Comment by trackleft** [comment]
See https://git.drupalcode.org/project/paragraphs_admin/-/commit/69f58b1b01bd0b35966ed08430735540987e4752
