### ISSUE TITLE
Create Text with Background paragraph

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#290]
**Name:** Text with Background
**Description:** Add text on top of a colored/patterned background

**Requirements:** 
- Background color (pre-defined brand colors) (Select List)
- Background pattern (triangles left/center/right or trilines) (Select List)
- Full-width check box (checked is full-width, unchecked is content-width -- default)(Checkbox)
- Text (Standard Text field formatter CKEditor)

**Notes:**
It was decided that this should continue to be it's own paragraph item for two reasons:
1. It will promote users being more intentional about where they choose to add background elements.
2. It will be less intimidating to users to have more specific options.

MVP 2 could contain padding settings and admin view modes.

_**Approved by AZ Digital on 9/15/2020**_

**Comment by smayden** [comment]
To the question in the notes: I would expect the text editor to have all the same options as what we discussed for text paragraph. Media embed feels important. I frequently used media embeds and grids in our current full-width background wrappers.

**Comment by danahertzberg** [comment]
@smayden Agreed. I updated the description.

**Comment by jwmoore1** [comment]
Is there any thought to making the background options available on the "normal" Text paragraph item, rather than have a copy of that with background options?

**Comment by camikazegreen** [comment]
@jwmoore1 We discussed that option at the earlier workshop and decided against it. I'm having a hard time now remembering why...

**Comment by jwmoore1** [comment]
I must've missed the discussion. Is the default setting of this any different functionally than a normal text paragraph item?

**Comment by danahertzberg** [comment]
I think it makes sense to just add background settings to the Text paragraph. That would help provide consistent visual rhythm and reduce duplicate paragraphs. 

Adding padding/margin settings in MVP 2 would also be more straightforward with 1 paragraph type. We could also add background settings to Cards and Accordions in MVP 2.

**Comment by danahertzberg** [comment]
**Notes about combining with text:**
- Too many options can be overwhelming. Too few options can be confusing.
- Separating out Text with Background and Text requires intention (in a good way)
- Trilines pattern may be broken if not full width

**Comment by danahertzberg** [comment]
Here is the template/layout information with a few items to note.

- I included some needed CSS at the beginning - feel free to modify class names as needed to align with AZ Digital standards.
- I tried to define the variables and what each UI selection would mean. The content editor would select the X option, which would apply Y directions. (X: Y)
- Samples of various layouts for content/full width styles are provided at https://codepen.io/danahertzberg/full/qBadjPo 

Let me know if there are any questions!

```
<style>
    .text-with-background {
        padding: 3em 0;
    }
    .bg-triangles-right {
        background-image: url(https://cdn.uadigital.arizona.edu/lib/ua-bootstrap/v1.0.0-beta.29/img/triangles-top-right.svg);
        background-repeat: no-repeat;
        background-size: auto;
        background-blend-mode: multiply;
        background-position: top right;
    }
    .bg-triangles-left {
        background-image: url(https://cdn.uadigital.arizona.edu/lib/ua-bootstrap/v1.0.0-beta.29/img/triangles-top-left.svg);
        background-repeat: no-repeat;
        background-size: auto;
        background-blend-mode: multiply;
        background-position: 0 0;
    }
    .bg-triangles-centered {
        background-image: url(https://cdn.uadigital.arizona.edu/lib/ua-bootstrap/v1.0.0-beta.29/img/triangles-centered.svg);
        background-repeat: no-repeat;
        background-size: auto;
        background-blend-mode: multiply;
        background-position: center bottom;
    }
    .bg-trilines {
        background-image: url(https://cdn.uadigital.arizona.edu/lib/ua-bootstrap/v1.0.0-beta.29/img/trilines.svg);
        background-size: auto 305px;
        background-position: top right;
        background-position: top 0 right -1em;
        background-repeat: no-repeat;
    }
</style>

- text-with-background.title: Defines the title.
- text-with-background.center-title: Center the title if checked.
    - Unchecked: Do not apply any class.
    - Checked: Apply 'text-center' class.
- text-with-background.body: Defines the body.
- text-on-media.background-color: The color of the text background.
    - Arizona Red: Apply 'bg-red' class.
    - Arizona Blue: Apply 'bg-blue' class.
    - Sky: Apply 'bg-sky' class.
    - Oasis: Apply 'bg-oasis' class.
    - Azurite: Apply 'bg-azurite' class.
    - Midnight: Apply 'bg-midnight' class.
    - Bloom: Apply 'bg-bloom' class.
    - Chili: Apply 'bg-chili' class.
    - Cool Gray: Apply 'bg-cool-gray' class.
    - Warm Gray: Apply 'bg-warm-gray' class.
    - Leaf: Apply 'bg-leaf' class.
    - River: Apply 'bg-river' class.
    - Silver: Apply 'bg-silver' class.
    - Ash: Apply 'bg-ash' class.
- text-with-background.background-pattern: The pattern applied to the background.
    - None: Do not apply any class.
    - Triangles Left: Apply 'bg-triangles-left' class.
    - Triangles Centered: Apply 'bg-triangles-centered' class.
    - Triangles Right: Apply 'bg-triangles-right' class.
    - Trilines: Apply 'bg-trilines' class.
- text-with-background.full-width: Defines if paragraph type is full width (checked) or content width (unchecked).
    - Unchecked: Apply 'text-with-background' class and color/pattern classes to row div.
    - Checked: Apply 'text-with-background' class and color/pattern classes to outermost div.

<!-- Layout for content width style -->
<div class="">
    <div class="container">
        <div class="row text-with-background {{text-with-background.background-color}} {{text-with-background.background-pattern}}">
            <div class="col col-xs-12">
                <div class="content">
                    <h2 class="mt-0 bold {{text-with-background.center-title}}">{{text-with-background.title}}</h2>
                    <div>{{text-with-background.body}}</div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Layout for full width styles -->
<div class="text-with-background {{text-with-background.background-color}} {{text-with-background.background-pattern}}">
    <div class="container">
        <div class="row">
            <div class="col col-xs-12">
                <div class="content">
                    <h2 class="mt-0 bold {{text-with-background.center-title}}">{{text-with-background.title}}</h2>
                    <div>{{text-with-background.body}}</div>
                </div>
            </div>
        </div>
    </div>
</div>

**Comment by jcheek** [comment]
port of D7 content_chunks_full_width_bg_wrapper ?

**Comment by camikazegreen** [comment]
Yes, this is the port of D7 content_chunks_full_width_bg_wrapper.

**Comment by jcheek** [comment]
per @joeparsons see if it is possible to use paragraph behaviors for the layout/style settings

**Comment by jcheek** [comment]
Add my PP type to the list of types allowed in the (flexible) page, if needed

**Comment by jcheek** [comment]
add the css via an attached library -- name the library as az_paragraphs.(bundle) (ask Troy for details, if needed)
