### ISSUE TITLE
Exclude BigPipe from Quickstart installs on Pantheon

### ISSUE THREAD

**Issue by bberndt-uaz** [az-digital/az_quickstart#2916]
## Motivation
The [BigPipe module](https://www.drupal.org/docs/8/core/modules/big-pipe) is included in Drupal core and is currently installed by default with Quickstart. However, this module provides no benefit on Pantheon sites and [Pantheon recommends disabling it](https://docs.pantheon.io/modules-known-issues#bigpipe). Furthermore, we have come across issues related to this module. Most recently, we encountered a bug with the reset button for views which results in a blank view when users try to reset the view filters. See [this issue](https://www.drupal.org/project/insert_view_adv/issues/3158996) for more details. (That issue's module is not used in Quickstart, but as noted in a comment there, the problem affects other modules as well. See also [this issue for Better Exposed Filters](https://www.drupal.org/project/drupal/issues/3304746).)

Excluding the BigPipe module from the Quickstart installation profile for sites on Pantheon will ensure that Quickstart follows Pantheon's guidelines and will prevent any further issues related to views. Since the module is part of Drupal core, it can be easily installed at any time.

As observed by @joeparsons, "there have been some [recent developments with BigPipe in Drupal core](https://www.drupal.org/project/drupal/issues/3377570) (it will use a new PHP feature called 'fibers' in a future release)" as well as some updates to [this Pantheon issue to add support for BigPipe](https://github.com/pantheon-systems/drops-8/issues/146). Although BigPipe should not have any impact for anonymous users, @joeparsons notes that "BigPipe can improve performance for logged in users, especially if the platform supports it."

## Conditions of satisfaction
- [ ] The BigPipe module should no longer be installed by default on new Quickstart environments on Pantheon.

**Comment by joeparsons** [comment]
I think we probably only want to stop installing the module by default on Pantheon specifically since the module is beneficial on other hosting platforms.

**Comment by joeparsons** [comment]
We have this existing code in `az_quickstart.install` that conditionally installs extra modules on Pantheon:
https://github.com/az-digital/az_quickstart/blob/main/az_quickstart.install#L45-L59

We could probably do something similar to only install BigPipe if not on Pantheon (would probably also require removing it from the `az_quickstart.info.yml` file.
