### ISSUE TITLE
Update photo field label on news add/edit form to "Featured Photo" to match what it is called on field_az_featured_image_as_thumb

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#2927]
## User Story(s)
As a Content Administrator or Editor, I add news items and see an option `Use Featured Image as Thumbnail settings for News` but  can not find a "featured image" field on the form.

<img width="1728" alt="image" src="https://github.com/az-digital/az_quickstart/assets/1023167/6d9d0b6d-de62-4d18-af80-9f78e32ad2fd">

I think we need to determine the wording to be used.

**Comment by sanjanans** [comment]
100% agree on changing the photo field label to “Featured Photo or Image”. Whatever word we choose should be the same on both sides:
1. Photo field label 
2. Check box label referencing it.
