### ISSUE TITLE
Always show summary fields when adding or editing content.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#2928]
## User Story(s)
As a content editor or content admin, when adding or editing news, and other content types that come with Quickstart, it is not apparent that the Summary fields are very important fields.

It would make sense to me to have the summary section open by default when adding or editing content.

Slightly customized default
<img width="1728" alt="image" src="https://github.com/az-digital/az_quickstart/assets/1023167/53472f4b-5572-472f-87b9-0d9770a8e198">

Proposed
<img width="1728" alt="image" src="https://github.com/az-digital/az_quickstart/assets/1023167/08b2905f-6515-47e3-abaf-4d040de11191">

**Comment by camikazegreen** [comment]
I really like this proposal. Summary fields are used throughout the site in views, and also in the Marketing Cloud integration, and took some work to find when I was building out newsletter content.

**Comment by sanjanans** [comment]
Good improvement proposal. Thank you for thinking of this issue and suggesting an easy/straightforward solution. With this solution, summary field will no longer remain "hidden" and will catch the eye of the content editor to consider using it meaningfully.
