### ISSUE TITLE
Web page addresses and email addresses turning into links automatically in our summary field, breaks our displays.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#2929]
<img width="584" alt="image" src="https://github.com/az-digital/az_quickstart/assets/1023167/9c5a021a-0011-43ae-a4c4-433b5a94621f">

<img width="1084" alt="image" src="https://github.com/az-digital/az_quickstart/assets/1023167/759f74e1-096e-4c49-9431-31db6ba145e2">

**Comment by natebyerley** [comment]
@danahertzberg @trackleft - I rediscovered this issue today working with azs-commencement on their forthcoming finder tool for convocation events. 

I observed - if an email address is included in the Page Summary field, it will 

a) cause all text before the email address (and the address itself) to be <b>
b) indent all summary fields to the right (as though there is a summary image that is not displaying)

Can we escalate exploring a fix on this one?
