### ISSUE TITLE
Upgrade inline_entity_form to 3.x branch

### ISSUE THREAD

**Issue by joshuasosa** [az-digital/az_quickstart#2938]
## Problem/Motivation
The inline_entity_form module 2.x branch is marked as unsupported. See [3401656](https://www.drupal.org/project/inline_entity_form/issues/3401656).

## Proposed resolution
Edit: Upgrade to 3.x or downgrade to the 1.x branch.

**Comment by joeparsons** [comment]
Thanks for reporting @joshuasosa

**Comment by joeparsons** [comment]
There is a 3.x release available now as well:
https://www.drupal.org/project/inline_entity_form/releases/3.0.0-rc15
https://github.com/az-digital/az_quickstart/pull/3007

**Comment by joshuasosa** [comment]
Nice! The 3.x is probably the better option being that it's initially the same as 1.x and will probably be the more likely continued path forward.
