### ISSUE TITLE
(Needs review) Create Space paragraph

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#294]
**Name:** Space
**Description:** Add space between elements

**Requirements:**
- Space (pre-defined list of margins using bootstrap classes 1-10, default is 4)

**Notes:**
The idea behind this paragraph type is that spacing can be applied anywhere rather than be attached to each paragraph type. Smaller, more manageable paragraph types may be easier to understand. Default for items like Text with Background and Text on Media would be so they touch the surrounding paragraph types.

**_Dependent on AZ Digital's review/edits and approval these requirements_**

**Comment by smayden** [comment]
I'm not sure I'm understanding this one. Would this be used between paragraph elements to create space? Or would be paragraphs be nested inside the spacing paragraph?

This feels possibly more complicated to me than setting the desired spacing on each element.

**Comment by camikazegreen** [comment]
It was decided that the space options would just be included in the Text Area Paragraph item instead.
