### ISSUE TITLE
User Permissions Not Updating After Menu Block Module Enabled (perhaps Others)

### ISSUE THREAD

**Issue by natebyerley** [az-digital/az_quickstart#2943]
## Problem/Motivation

After installing **Quickstart Block Types - Menu Block** on several sites, Content Admin is unable to create a Menu Block (Step 2 of "How to Setup a Menu Block" in [these instructions](https://quickstart.arizona.edu/site-admin/managing-menus/menu-blocks))

### Describe the bug

Lengthy discussion with BB, JP and CG here in [Slack](https://uarizona.slack.com/archives/G6Z9FFKAL/p1694455547087959). 

CG - "I think this is because we aren’t running our **az-core-config-add-permissions** command after enabling modules that have permissions."

CG - "Those permissions live in the role [https://github.com/az-digital/az_quickstart/blob/e54469de6a8ae5a692fe669c6a14a30ce7058966/config/install/user.role.az_content_admin.yml#L36C1-L37C1](https://github.com/az-digital/az_quickstart/blob/e54469de6a8ae5a692fe669c6a14a30ce7058966/config/install/user.role.az_content_admin.yml#L36C1-L37C1)"

CG - "So we must not be syncing permissions every time we install a new module?"

### To Reproduce

1. Enable **Quickstart Block Types - Menu Block** Module on a site.
2. Masquerade as Content Admin
3. Follow steps in [these instructions](https://quickstart.arizona.edu/site-admin/managing-menus/menu-blocks))
4. You should not be able to add a Menu Block in Step 2 of "How to Setup a Menu Block" - you should only see "Flexible Block" and "Basic Block"

## Proposed resolution

Run **az-core-config-add-permissions** command after enabling modules that have permissions.

### Expected behavior

Content Admins can create Menu Blocks after module enabled.

**Comment by joeparsons** [comment]
Seems like this is something that needs to be handled on a site-by-site basis by utilizing `az-core-config-add-permissions` drush command when applying Quickstart updates to a site.  Feel free to re-open if there is something that needs to get updated in Quicsktart.
