### ISSUE TITLE
Video Thumbnail in Page/Event/News Editor Too Small + oEmbed Errors 

### ISSUE THREAD

**Issue by natebyerley** [az-digital/az_quickstart#2946]
## Problem/Motivation

Discovered during testing 2.8.1 in test.  Testing protocol is to build new page content and try to find issues with CK Editor 5.  Looking particularly at differences in how CK Editor works on a Page, vs Event, News, Person.

### Describe the bug

Note: All video visibility issues described below are when viewing page _editor_.  Front end displaying correctly in all cases. 

When embedding remote video in a [Person Bio](https://test-azs-honors.pantheonsite.io/person/nate-byerley) (or [News Article Body](https://test-azs-honors.pantheonsite.io/news/nkb-news-test) or [Event Description](https://test-azs-honors.pantheonsite.io/events/nkb-event)), the thumbnail for the video is tiny, and remains tiny regardless of the 'size' setting for the video.

On a [Page](https://test-azs-honors.pantheonsite.io/nate-test-page), embedding a remote video - the video is more visible (not tiny) but doesn't change size based on 'size' setting.

Also, getting an error "Could not retrieve the oEmbed resource." when adding a new video, though videos seem to display as expected on front end.

Screenshots below show:

- View of embedded video on a Page (editor)
- View of embedded video on News (editor) - which is the same as in Event Description or Person Bio
- oEmbed errors

### To Reproduce

1. On a site on QS 2.8.1
2. Embed a 'remote video' within a Person Bio, News Article Body or Event Description. 

Note tiny size, that does not adjust if you change the width of the video

## Proposed resolution

...

### Expected behavior

Seems like a true WYSIWYG editor experience would have video size change with video size setting.  So I'm not sure if the Page editor experience of embedding a video is 'expected' or just 'better than' the experience on News/Person/Event.

##  Screenshots

![Screenshot 2023-11-21 at 3 28 59 PM](https://github.com/az-digital/az_quickstart/assets/97116860/16d23dff-3f29-4282-9436-625946a36c2d)

![Screenshot 2023-11-21 at 3 35 57 PM](https://github.com/az-digital/az_quickstart/assets/97116860/033488d5-abad-47d3-b983-85622a53a0fd)

![Screenshot 2023-11-21 at 3 39 07 PM](https://github.com/az-digital/az_quickstart/assets/97116860/7afc00e8-d714-432c-9f00-a8e9be999329)

![Screenshot 2023-11-21 at 3 38 03 PM](https://github.com/az-digital/az_quickstart/assets/97116860/8c32ffe8-8893-458e-9474-ef77c08927fb)

### Desktop (please complete the following information):
 - OS: Mac OS
 - Browser : Safari and Firefox

**Comment by danahertzberg** [comment]
Created a branch, but have no useful changes committed yet.

Started looking at this https://stackoverflow.com/questions/57320194/ckeditor-5-showing-video-element-but-plain-html-inserted-in-a-div-does-not-show but don't know where to put mediaEmbed setting if that would even be a viable solution.

**Comment by danahertzberg** [comment]
Per @joeparsons: Possibly related (at least for the oEmbed error): https://www.drupal.org/project/drupal/issues/3188842
