### ISSUE TITLE
Unpublished Trellis Events appearing in the Events Importer

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#2957]
## Problem/Motivation
Unpublished Trellis Events should not be showing up in the search results of the Trellis Events Importer, but currently they do and are able to be imported.

### To Reproduce

1. Search for Trellis
2. The future "Trellis 102" events are not published events, but do show up in the list.
![image](https://github.com/az-digital/az_quickstart/assets/1509771/d2cf0e6f-f16e-4649-8b31-e5f71c560524)

## Proposed resolution
This may be more appropriately resolved at the Trellis API level, but we should at least be able to filter out unpublished events from showing up in our listings.

**Comment by danahertzberg** [comment]
@camikazegreen Do events that are unpublished on Trellis get imported as unpublished events in Drupal? I'd like to chat with Trellis UX to get insight on this need.
