### ISSUE TITLE
Drupal 10.2.0-rc1 Field Widget Core Delete Breaks Cards

### ISSUE THREAD

**Issue by tadean** [az-digital/az_quickstart#3025]
## Problem/Motivation
A long-awaited core feature, Drupal 10.2 seems to introduce [remove buttons on multiple value fields.](https://www.drupal.org/project/drupal/issues/1038316)

Presently, our custom card field widget institutes a workaround for this feature not having been available previously, in the form of a custom removal button. The implementation of our custom callback and the core callback are similar in approach, but conflict with each other.

### To Reproduce
On #2968 , create a flexible page with a card deck and attempt to delete an individual card with either removal button. An ajax error results.

## Proposed resolution
Remove our custom remove button and fall back on core behavior.

### Expected behavior
Core removal button should remove the card.

**Comment by joeparsons** [comment]
Not complete until #2968 is merged
