### ISSUE TITLE
Create Standard Text Format

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#306]
**Name:** Standard Text
**Description:** Add standard text, headings, links, buttons, etc.

**Requirements:**
- Undo/Redo
- Styles (same as QS 1.0)
- Bold/Italic/Strikethrough
- Link/unlink
- Align left/center/right
- Insert unordered/ordered list
- Block quote
- Insert grid
- Insert table
- Embed media/blocks/content
- Super/sub script
- Insert special characters
- Remove formatting
- Paste plain text
- View source

**Comment by camikazegreen** [comment]
We can copy one of the existing text format (filtered HTML?) and name it az_standard. Once that is merged, we will be able to reference it in the currently blocked Paragraph Items and then it will be able to be improved over time.
