### ISSUE TITLE
Publication: Add fields for the PMCID and ISSN identifiers.

### ISSUE THREAD

**Issue by ejsamboy** [az-digital/az_quickstart#3071]
## Motivation
The PMCID and ISSN identifiers are collected for all publications on the old Cancer Center website using Biblio.

### Is your feature request related to a problem? Please describe.
The PMCID and ISSN are collected for every publication on the old Cancer Center site (Uses Biblio). Publication on the new site has no fields dedicated to PMCID and ISSN.

## Additional context
<img width="1398" alt="Screenshot 2024-01-10 at 10 37 01 AM" src="https://github.com/az-digital/az_quickstart/assets/92047381/43dfef69-d047-45a2-b9c6-4aeb13b08944">

**Comment by tadean** [comment]
@ejsamboy for testing purposes, which citation style is in use by the Cancer Center site?
