### ISSUE TITLE
Changes to rendered HTML after update to Drupal 10.2

### ISSUE THREAD

**Issue by bberndt-uaz** [az-digital/az_quickstart#3097]
## Problem/Motivation
We have encountered changes in the display of certain text areas on our test sites that have been updated to Quickstart 2.9. For example, in the instance below, single line breaks in the HTML have been changed to two line breaks:

#### Before Quickstart 2.9:
![Screenshot 2024-01-16 at 11 06 45 AM](https://github.com/az-digital/az_quickstart/assets/74572157/85caef07-a7e9-4504-8cfa-e1378bcbc043)

#### After Quickstart 2.9:
![Screenshot 2024-01-16 at 11 06 42 AM](https://github.com/az-digital/az_quickstart/assets/74572157/9fce6d1c-56d1-4f76-99d7-eb2e63d8a455)

### Describe the bug
In the example above, the line break elements are represented as `<br />` in the field in the database. However, when rendering the block on the page, the HTML is output as two `<br>`s instead. CKEditor displays the `<br />`s as `<br>`s. Re-saving a node or block with a card that has `<br />`s DOES change the `<br />`s to `<br>`s, but ONLY if you click the “Edit Card” button in the card deck.

This change seems to be related to this Drupal change record:

- [The HTML utility classes and the filter system now output HTML5](https://www.drupal.org/node/3225468)

## Proposed resolution
TBD

We have considered updates to the actual HTML saved in the database (to replace `<br />` with `<br>` for example), but we considered this too risky and we should address the root cause of the change in HTML output.

### Expected behavior

The display of page content should not change with the update to Quickstart 2.9.0.

## Additional context
This issue does affect all browsers.

**Comment by bberndt-uaz** [comment]
Recap from the AZ Digital workshop:

In the database, this value for a text area will cause the issue of two `<br>` elements:
```
<p>first line<br>
second line</p>
```

Note the line break character after the `<br>` (a UTF-8 0A character in the database).

These values will NOT exhibit the issue:
`<p>first line<br>second line</p>`
`<p>first line<br />second line</p>`

These have no line break character after the `<br>`.

In the Standard text format, moving the "Convert line breaks into HTML (i.e. \<br\> and \<p\>)" filter above the "Limit allowed HTML tags and correct faulty HTML" filter also resolves the issue of two `<br>` elements being output where only one was before.

**Comment by tadean** [comment]
In local testing, it appears that this does not happen if https://git.drupalcode.org/project/drupal/-/blob/11.x/core/modules/filter/filter.module?ref_type=heads#L758 is updated to match `<br>` rather than `<br />`. It looks like the HTML5 changes to filters doesn't combine well with the fact that `_filter_autop`'s regexes weren't updated to match...

**Comment by joeparsons** [comment]
> In local testing, it appears that this does not happen if https://git.drupalcode.org/project/drupal/-/blob/11.x/core/modules/filter/filter.module?ref_type=heads#L758 is updated to match `<br>` rather than `<br />`. It looks like the HTML5 changes to filters doesn't combine well with the fact that `_filter_autop`'s regexes weren't updated to match...

Related D.O. issue: https://www.drupal.org/project/drupal/issues/2350049
