### ISSUE TITLE
Feature Request: Add Description to Quickstart Modules

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#3130]
## Motivation
Currently, administrators may encounter difficulties in understanding what each module does if there is no description in the .info.yml file for that module.

### Is your feature request related to a problem? Please describe.
No

## Proposed Resolution
Ensure all 53 Quickstart module `info.yml` files have a description in their info files. (This may need to be broken into multiple tickets if we can't agree on descriptions)

See search: https://github.com/search?q=repo%3Aaz-digital%2Faz_quickstart%20.info.yml&type=code

See drupal docs https://www.drupal.org/docs/develop/creating-modules/let-drupal-know-about-your-module-with-an-infoyml-file

**Comment by BaoNguyen09** [comment]
After searching through all info.yml files, I only found these modules without a description in .info.yml files:

- az_google_tag
- az_select_menu
- az_block_types_quick_links
- az_flexible_page
- az_seo
- az_flexible_block
