### ISSUE TITLE
Make "+ Add CAS User" button primary at /admin/people

### ISSUE THREAD

**Issue by natebyerley** [az-digital/az_quickstart#3141]
## Problem/Motivation

Our most common support ticket is User Admins having trouble adding new users. 

- Better documentation can help this, however it will be hard to avoid having users mistakenly use the "Add User" button rather than the "+ Add CAS User" button when adding users, as "+ Add User" is the wording that most clearly matches the intent of the User Admin.  The word CAS may actually subtly steer people away since it is not obvious the meaning of a CAS User.

### Describe the bug

Add User and Add CAS User are too similar visually, and the wording compels people to take the wrong action when adding site editors.

![Screenshot 2024-01-31 at 1 50 06 PM](https://github.com/az-digital/az_quickstart/assets/97116860/4dcbcff8-d2ad-441c-b4f6-fe3bb31e13f9)

## Proposed resolution

- Make most common action (+ Add CAS User) visually dominant.  
- Potentially alter wording to help users understand meaning of buttons
- Update documentation at quickstart.arizona.edu to support proper action

**Comment by natebyerley** [comment]
I think updating the language to be more natural may help, but if the 'add user' button is right next to it, and the same visual weight, people will still use that probably 50% of the time. 

Would it make sense to update the "Add User" button language to steer people away from this button?  I honestly am not 100% sure what the use case is for this button.

**Comment by joeparsons** [comment]
Spoke to @natebyerley about this on Slack.  We agreed that the `Add User` action/button should only be needed on sites that _don't_ have the `Disable login form` AZ CAS module setting turned on (which disables the default Drupal user login form):
![Screenshot 2024-02-13 at 10 38 15 AM](https://github.com/az-digital/az_quickstart/assets/471936/75be1c84-af61-4ddf-8e4f-e42cd3e22234)

I also reviewed Drupal core's code related to Menu Local Action plugins and their associated template(s), preprocess functions and alter functions to see what we might be able to easily change about the rendered action buttons. Unfortunately, although [hook_menu_local_actions_alter()](https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Menu!menu.api.php/function/hook_menu_local_actions_alter) and [menu-local-action.html.twig](https://api.drupal.org/api/drupal/core%21modules%21system%21templates%21menu-local-action.html.twig/10) exist, the Claro admin theme hard-codes the `button--primary` class that is getting added to the rendered buttons in [claro_preprocess_menu_local_action()](https://api.drupal.org/api/drupal/core%21themes%21claro%21claro.theme/function/claro_preprocess_menu_local_action/10) so it'd be pretty complicated to override that.  We could pretty easily modify the text of either action button and or change the order/weight pretty easily, if needed.

**Comment by trackleft** [comment]
Should we also link to the documentation site from that page? https://quickstart.arizona.edu/site-admin/managing-users

**Comment by joeparsons** [comment]
## Notes from 2024-02-14
- Suggested title for CAS users button: "Add user(s) with NetID"
- If we do make it possible to disable / omit the  "Add users" button, we should make sure whatever setting is controlling that describes that
- We should also be sure to update user admin documentation and link to it from the AZ CAS settings interface and/or the /admin/people UI
