### ISSUE TITLE
Color Block Page Element

### ISSUE THREAD

**Issue by JoeLutovsky** [az-digital/az_quickstart#3174]
## Motivation
I want more options for page design and creativity.

### Is your feature request related to a problem? Please describe.
not related to any issue

## Proposed Resolution
use  Text with Background as the starting point for this new page Element

### Describe the solution you'd like
I basically would just like a page element that is the same as the Text with Background element, just without the requirement of text. 

### Describe alternatives you've considered
i've thought about putting `&nbsp;`s into the Text with Background but it doesn't work well and is entirely unelegant. 

## Additional context
There have been points when building pages where a nice solid bar of color would really step the page up a notch visually and that's just not possible in the current system.

**Comment by mrbeiley** [comment]
<img width="1162" alt="image" src="https://github.com/az-digital/az_quickstart/assets/20604868/2c29d6de-08ee-4e91-829c-758824028bbd">
Is this the idea?

**Comment by mrbeiley** [comment]
@HenryzGreenberg to ensure brand adherence with Central Marketing

**Comment by mrbeiley** [comment]
@JoeLutovsky could you provide a few design specifics/requirements? right now we know a solid bar of color will be useful, but how about dimensions, images, colors, etc.? Thanks in advance.

**Comment by JoeLutovsky** [comment]
Really as long as it functioned exactly like the Text on Background element, without the text field, that would be sufficient. Instead of Space around Content, just make those options the height options.

**Comment by tkmccarthy** [comment]
The Marcom web experience team would be happy to explore more design options for marquees or ways to break up sections on a page. I do think this is needed.

However, I am curious if what you describing though is something that can already be done with a background color and text though?

**Comment by mrbeiley** [comment]
It seems like a Text with Background would work, except text is a requirement. This new element would just be a colored block. Maybe we can clone the Text with Background element and remove the text requirement.
