### ISSUE TITLE
Card Title Text-Align Options

### ISSUE THREAD

**Issue by JoeLutovsky** [az-digital/az_quickstart#3175]
### Describe the solution you'd like
Would be helpful if there were text align options that set the text alignment of Titles within Cards rather than them always being left justified. 

## Additional context
Sometimes centering the card title text would look better.

**Comment by joeparsons** [comment]
This is probably a duplicate of #2037

**Comment by joeparsons** [comment]
Closing this since we already have #2037 which has a pending PR (#2041)
