### ISSUE TITLE
Email announcement to IT Directors

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#318]

**Comment by smayden** [comment]
Draft for email #1: https://docs.google.com/document/d/19OJN5ftSdd1RTXQuKB9LkYkb1l-CWhfY1b-dWYdvWLk/edit?usp=sharing

Shoshana and Cameron plan to meet with Barrett and Donna to discuss and finalize.

**Comment by camikazegreen** [comment]
This email was sent to IT Directors from Donna Bieg on Monday, November 2nd.
It was followed up with on the next day with this presentation to the IT Director's Council:
https://docs.google.com/presentation/d/1B7QI0bJQS1_r8L_fhiBJl3ld33O6BcVAeC7Qc_1iXac/edit#slide=id.g9e61c19dbe_0_0
