### ISSUE TITLE
Adjust Carousel Item image style to 1110x500

### ISSUE THREAD

**Issue by djcelaya** [az-digital/az_quickstart#3218]
## Problem/Motivation
The Carousel Item image style scales and crops its target to 1400x500. This is larger than the max width of a carousel item (1110x500) and it should be adjusted to 1110x500 for a more intuitive editor experience.

### Describe the bug
Unusual and unexpected cropping occurs because the image container size and image size are not aligned. 

## Proposed resolution
Adjust the Scale and Crop effect on the Carousel Item image style to be 1110x500 (down from 1400x500).

## Additional context
The config for this image style is in az_media.

**Comment by bberndt-uaz** [comment]
@djcelaya Thanks for creating this issue! Along with the change to the Scale and Crop setting, it would be good to update the media field description which is recommending a minimum width of 1400px: see https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_carousel/config/install/field.field.node.az_carousel_item.field_az_media_image.yml#L13.

**Comment by djcelaya** [comment]
@bberndt-uaz Yes, agreed. I made an issue for that #3214
