### ISSUE TITLE
Add a "Getting Started" page to digital.arizona.edu

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#322]
In today's workshop we discussed whether developer documentation should live at quickstart.arizona.edu or digital.arizona.edu and are leaning toward the digital site. Updating title of this issue.

Documentation for Getting Started would cover:

- How to install (even without pantheon)
- Setting up site
- Managing codebase
- Composer
- Developing locally

**Comment by danahertzberg** [comment]
Closed per @camikazegreen
