### ISSUE TITLE
Remove duplicate version key in az_quickstart.info.yml on 2.8.x branch.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#3242]
## Problem/Motivation
There is a duplicate version key in the az_quickstart.info.yml

### Describe the bug
In InfoParserDynamic.php line 47:
                                                                                                                                             
  [Drupal\Core\Extension\InfoParserException]                                                                                                
  Unable to parse profiles/custom/az_quickstart/az_quickstart.info.yml Duplicate key "version" detected at line 83 (near "version: 2.8.8"). 
  
  
  We should probably create a new patch release for this bug.

**Comment by joeparsons** [comment]
Darn.  I think this was caused by a failed workflow when we created the 2.8.7 release: https://github.com/az-digital/az_quickstart/actions/runs/7994217234/job/21832461860

**Comment by trackleft** [comment]
Creating a new release using the create release workflow resolved this issue.
