### ISSUE TITLE
Add a status check to determine whether a site is using Google Tag in consent mode

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#3248]
## Motivation
To enhance site compliance and management efficiency, making Google Consent Mode settings visible at a glance on the status page is essential. This visibility ensures that site administrators can quickly and easily verify that the site is compliant with privacy regulations like GDPR.

### Is your feature request related to a problem? Please describe.
The main challenge is the lack of immediate visibility of Google Consent Mode's operational status on the site, particularly on the status page. Currently, verifying this requires navigating through multiple settings or performing manual checks, which is not ideal for quick assessments or for administrators who may not be deeply technical.

### Describe the solution you'd like
A clear and prominent display of Google Consent Mode's status directly on the status page of the AZ Quickstart site. This could include indicators of whether Consent Mode is enabled, correctly configured, and actively functioning as expected. Ideally, this would be a summary view with the option to click through for more detailed information if needed.

### Describe alternatives you've considered
An alternative might be periodic email reports or notifications regarding the status of Google Consent Mode. However, this is less immediate and could lead to oversight if emails are missed or not sent due to configuration errors.

### Roles and Permissions considerations
- **Anonymous user:** No direct impact, but indirectly benefits from the site's compliance and respect for user privacy.
- **Authenticated user:** No direct impact, but like anonymous users, they benefit from enhanced privacy protections.
- **Content editor and Content administrator:** These roles might see the status indicator for informational purposes but would typically not have the permissions to alter Consent Mode settings.
- **Administrator:** Administrators would have full access to the Consent Mode status on the status page, including details on its configuration and operational status, allowing them to ensure compliance and address any issues promptly.

## Additional context
Making Google Consent Mode settings and status easily accessible and visible at a glance on the status page supports our commitment to privacy, compliance, and user trust, and can lead to quicker discovery of a problem. This approach simplifies the management of these critical settings for site administrators, reducing the risk of oversight and non-compliance.

**Comment by trackleft** [comment]
This might make more sense as an issue on the[ google_tag project](https://www.drupal.org/project/google_tag).

**Comment by joeparsons** [comment]
> This might make more sense as an issue on the[ google_tag project](https://www.drupal.org/project/google_tag).

I guess I was thinking this would be something UArizona specific that may change over time as a consent management platform is introduced, etc.
