### ISSUE TITLE
Investigate moving dev dependencies and configuration to profile repo

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#33]
## What is the problem that we want to solve?
Our dev and test dependencies are currently defined and configured primarily in our [az-quickstart-scaffolding](https://github.com/az-digital/az-quickstart-scaffolding) repo.

As we've continued to work more on Quickstart, we've found that:
- We frequently need to make pull-requests on both the scaffold and profile repos at the same time to make changes to any of our dev/testing tools.
- Keeping various dependencies "in sync" between our scaffold and profile repos is becoming increasingly burdensome.  This is particularly true for dependencies that are tied to specific versions of Drupal core such as [drupal/core-dev-pinned](https://github.com/drupal/core-dev-pinned) and [drupal/core-composer-scaffold](https://github.com/drupal/core-composer-scaffold).

## Proposed resolution
Investigate and experiment with making our scaffolding repo as minimal as possible by moving dependencies from the scaffold repo to the profile repo.

A potential blocker that was brought up by @tadean was that the `zaporylie/composer-drupal-optimizations` composer plugin we are currently using has to be defined/configured in the "root" composer project to function correctly.  This may also be true for `drupal/core-composer-scaffold`.

@tadean and @joeparsons discussed some potential changes/workarounds that would be worth experimenting with:
- Keep composer.json configuration for `drupal/core-composer-scaffold` in scaffold repo but experiment with moving actual dependency to profile repo
- (Or) use less specific version constraint for `drupal/core-composer-scaffold` in the scaffolding repo's composer.json and let it select the version defined by the profile automatically
- `zaporylie/composer-drupal-optimizations` helps a lot, but it wouldn't be the end of the world to not have it. (And maybe we could implement something with a similar in the profile to what it's doing - it's basically just composer trickery that truncates symfony packages.)

## Conditions of satisfaction
- [ ] The considered options are documented
- [ ] A recommended next step is documented
- [ ] An estimate of time and effort is provided for the recommendation

**Comment by trackleft** [comment]
General strategy that might meet our needs:
Replace drupal specific dependencies version constraints in scaffolding repo with less specific versions so that it can rely on quickstart repo for version constraints.
