### ISSUE TITLE
Provide Enterprise Attribute Filtering for News Export

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#3305]
## Motivation

1. News articles in CatCloud _must_ have Enterprise Attributes to display correctly in CatCloud.
2. Sometimes we want to create News articles on our website that don't get imported to CatCloud.

## Proposed Resolution
_**Due in July 2024**_

### Describe the solution you'd like
We could make it so that only articles that are tagged with Enterprise Attributes get included in the Export.

### Describe alternatives you've considered
We could add a "Do not broadcast" checkbox, that shares that information with Trellis.

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Anonymous user
- Authenticated user
- Content editor
- Content administrator
- Administrator

**Comment by tadean** [comment]
Updated description to reflect allowing the user of the export API to filter if they choose, rather than it being mandatory.
