### ISSUE TITLE
Add alphabetical reset to AZ Person reorder view

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#3307]
## Motivation
I reordered the person view once, now I have a lot of people and want to order them alphabetically.

### Is your feature request related to a problem? Please describe.
A client reordered once, added a bunch more people, and can't get them to an alphabetical order easily now.

### Describe the solution you'd like
I want an option to reset my manual person order.

### Describe alternatives you've considered
Could a reset button reset the order to `0` or an order that coincides with the alphabetical

## Additional context
Clear documentation will be needed. Ie. If this button is pushed, _all_ reordering will be reset to an alphabetical listing.

**Comment by bberndt-uaz** [comment]
Related issue: [Alphabetical filter and search view for person](https://github.com/az-digital/az_quickstart/issues/1869).
