### ISSUE TITLE
Create workflow to handle repository_dispatch notification from arizona-bootstrap-packagist

### ISSUE THREAD

**Issue by kevcooper** [az-digital/az_quickstart#332]
This notification will inform az_quickstart that it needs to update the version of arizona-bootstrap that is being referenced

**Comment by trackleft** [comment]
name: Update Arizona Bootstrap
on:
  repository_dispatch:
    types: az_bootstrap_release
jobs:
  update_az_bootstrap:
    name: Create PR with latest tagged Arizona Bootstrap
    runs-on: ubuntu-18.04

**Comment by joeparsons** [comment]
Automated PR should:
- Update `az-digital/arizona-bootstrap` version in composer.json
- Update `AZ_BOOTSTRAP_STABLE_VERSION` value in [themes/custom/az_barrio/includes/common.inc](https://github.com/az-digital/az_quickstart/blob/main/themes/custom/az_barrio/includes/common.inc#L10)
