### ISSUE TITLE
Quickstart Finder - Distro Updates Needed

### ISSUE THREAD

**Issue by natebyerley** [az-digital/az_quickstart#3338]
## Problem/Motivation

Trying to test Quickstart Finder on this multidev: [https://alpha210-azs-quickstart.pantheonsite.io/](https://alpha210-azs-quickstart.pantheonsite.io/)

Working from these instructions: [https://quickstart.arizona.edu/page-elements/views/page-filter](https://quickstart.arizona.edu/page-elements/views/page-filter)

I'm stuck on step 3 under 'How to Implement' > "Next, enable the filter block..."

**I can't find these blocks:**

1. Row Page: Exposed form: az_page_by_category-row
2. Grid page: Exposed form: az_page_by_category-grid

## Proposed resolution

1. Augment the documentation at this page: [https://quickstart.arizona.edu/page-elements/views/page-filter](https://quickstart.arizona.edu/page-elements/views/page-filter)

Add a callout section at top that reads:

"Note: An administrator must enable the "Quickstart Finder" module on your site in order for the block elements to be available for use."

2. Import config distro for these modules

![image (7)](https://github.com/az-digital/az_quickstart/assets/97116860/a76e2799-39e8-4468-bfa3-2b9a0033da09)

### Expected behavior

1. With "Quickstart Finder" module enabled...
2. The following blocks should be able to be added to a block region

- Row Page: Exposed form: az_page_by_category-row
- Grid page: Exposed form: az_page_by_category-grid

**Comment by trackleft** [comment]
Test on other sites before heading down the path to a fix.

**Comment by joeparsons** [comment]
## 2024-04-10 Workshop notes

- @trackleft noticed that our `Drupal\az_core\Plugin\ConfigProvider\QuickstartConfigProvider` class was logging a notice on sites that the views weren't being updated on upon installing the `az_finder` module (see https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php#L334C45-L334C100):
  ```
  Disallowing override of customized configuration @name
  ```
- @tadean was able to track down an actual config diff that was probably preventing our `QuickstartConfigProvider` class from being able to apply overrides related to the dynamically computed `cache_metadata` properties of the view(s).
- @joeparsons Found that the code in the views module that adds/updates the cache metadata to views is not always run during config sync or module install operations: https://git.drupalcode.org/project/drupal/-/blob/10.2.x/core/modules/views/src/Entity/View.php?ref_type=heads#L301-306
