### ISSUE TITLE
Special characters in Trellis Events aren't being displayed on Drupal site

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#3349]
## Problem/Motivation
I want all characters input to Trellis to migrate to website as-is.

### Describe the bug
Special characters (such as em dash) are not being rendered appropriately on the Drupal site.

### To Reproduce
For example, the news.arizona site shows `???` for the em dash.

Search `doctoral` on the following sites:
- https://news.arizona.edu/admin/trellis-event-importer
- https://quickstart.arizona.edu/admin/trellis-event-importer

## Proposed resolution
N/A

### Expected behavior
I expect my text and characters to look the same on the website as I put them in Trellis Events.

**Comment by tadean** [comment]
Further testing seems to show that this issue is non-deterministic - it happens on some requests and not others.

**Comment by tadean** [comment]
This was found to be an encoding issue in the production endpoint of the Trellis event API and has seemingly been resolved by the Trellis team. I am no longer able to reproduce the issue.
