### ISSUE TITLE
Add HTML paragraph to AZ News

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#3351]
## Motivation
I want to add a Spotify podcast to a specific news item on the website.

### Is your feature request related to a problem? Please describe.
I can add a useful HTML paragraph to a page, but not to a News item.

## Proposed Resolution
Allow HTML paragraph type in the "Extra page elements" section.
Only allow if associated module is enabled.

### Describe the solution you'd like
Add option for HTML paragraph type in Extra page elements section on AZ News.

### Describe alternatives you've considered
Considered adding the full HTML text formatter to the article body field. Determined this would not be useful since the UI is not very user-friendly to have on the entire body field.

## Additional context

> **Dana Hertzberg** [4 days ago](https://uarizona.slack.com/archives/G6Z9FFKAL/p1712935202917659)
> @here I was curious what the reason was for having the Article Body field of AZ News only allow the Standard text format and not the Full HTML text format. Since the user HTML administrator exists, would it make sense to allow the Full HTML text format on the AZ News body field in Quickstart?
> Or could we allow the full HTML paragraph type in the News content type? The client wants to embed Spotify podcasts on the news items.
> 
> **Cameron Green** [4 days ago](https://uarizona.slack.com/archives/G6Z9FFKAL/p1712937819247249?thread_ts=1712935202.917659&cid=G6Z9FFKAL)
> Would those make sense added at the end in the extra body content field by using HTML paragraphs?
> 
> **Dana Hertzberg** [4 days ago](https://uarizona.slack.com/archives/G6Z9FFKAL/p1712937865208679?thread_ts=1712935202.917659&cid=G6Z9FFKAL)
> I think that would certainly help in this case. Is there any other concern with doing this? Or concern it couldn't be done when enabling the HTML module?
> 
> **Cameron Green** [4 days ago](https://uarizona.slack.com/archives/G6Z9FFKAL/p1712938066250499?thread_ts=1712935202.917659&cid=G6Z9FFKAL)
> All the normal caveats of “use full HTML at your own risk”, but otherwise it seems like it should work without customizing anything. As long as having the Podcasts embedded at the end of the news articles rather than in the body works for the client.
> 
> I do know that our Full HTML text formatter is very user-unfriendly in general, so I’m not sure that they’d want to write whole articles without any WYSIWIG support, so hopefully this would be a better editor experience as well.
> 
> **Dana Hertzberg** [4 days ago](https://uarizona.slack.com/archives/G6Z9FFKAL/p1712938217152629?thread_ts=1712935202.917659&cid=G6Z9FFKAL)
> Okay awesome. I'll make sure that's workable via the client (Casual Astronaut for BIO5) and make a coordinating QS ticket. Thanks!
> 
> **Cameron Green** [4 days ago](https://uarizona.slack.com/archives/G6Z9FFKAL/p1712938253702119?thread_ts=1712935202.917659&cid=G6Z9FFKAL)
> Oof, it’s that site…
> 
> **Cameron Green** [4 days ago](https://uarizona.slack.com/archives/G6Z9FFKAL/p1712938344223879?thread_ts=1712935202.917659&cid=G6Z9FFKAL)
> That might be the only site that would potentially have a conflict with this approach, since they are using that extra body content field to associate News articles with people in their MemberTrack system. 
> 
> [@parsonsj](https://uarizona.slack.com/team/U0D9L7ZPG) Do you see any conflicts with HTML paragraphs and MemberTrack ID paragraphs being attached to the same article?
> 
> **Joe Parsons** [4 days ago](https://uarizona.slack.com/archives/G6Z9FFKAL/p1712940708421619?thread_ts=1712935202.917659&cid=G6Z9FFKAL)
> Probably not

**Comment by Krystation** [comment]
Hey @danahertzberg , there's already and HTML paragraph module and paragraph. Ive just added it to the news content type under extras. Tried to click the slack for more context. I did this on a multidev. Let me know if I misunderstood what was asked

[https://html-para-ua-news-redesign.pantheonsite.io/news/new-ai-coaching-bot-may-enhance-medical-education-training](https://html-para-ua-news-redesign.pantheonsite.io/news/new-ai-coaching-bot-may-enhance-medical-education-training )

**Comment by danahertzberg** [comment]
Thanks @Krystation! This is exactly what we want. I just want the HTML field to be available on News items in Quickstart sites by default when the HTML paragraph type is enabled.

**Comment by danahertzberg** [comment]
Available to do via admin privileges
1. Enable the HTML paragraph type
2. Enable the HTML paragraph type on the AZ News content type - customization

**Comment by danahertzberg** [comment]
Enabling this in AZ News makes future updates to use Drupal new features (Starshot, layout builder, etc) more challenging. Site-specific overrides can be made on an as-needed basis.

**Comment by danahertzberg** [comment]
Could look into this as an alternative. https://www.drupal.org/project/media_remote/issues/3301838
