### ISSUE TITLE
Configure Easy Breadcrumb preferred menu setting with main menu by default

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#3365]
## Motivation
If I have a page in multiple menus (like the Select Menu and the Main Menu), I want the breadcrumbs to reflect the location within the Main Menu.

### Is your feature request related to a problem? Please describe.
Easy Breadcrumb module setting is not set by default.

### Describe the solution you'd like
I want the default settings for Easy Breadcrumb to set the Preferred menu to Main Menu by default.

## Additional context
![image](https://github.com/az-digital/az_quickstart/assets/59745109/15c9c5a6-13ef-44ea-a917-ab75e2808b70)

**Comment by joeparsons** [comment]
FWIW, this was a new feature that was added to the Easy Breadcrumb module as part of the 2.0.4 release (released Nov 2022):
https://www.drupal.org/project/easy_breadcrumb/issues/3276168
