### ISSUE TITLE
Add version indicator to admin toolbar

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#338]
## Motivation
As a content editor, I want to be able to quickly tell which version of Quickstart I am using. 

This will also help me to understand which parts of the Quickstart documentation pertain to my site, since there will be documentation specific to both versions of Quickstart.

## Proposed Resolution
We could add a version indicator to the Admin toolbar that clearly states "Quickstart 2.0" or whatever the current version is.

## Additional context
![quickstart_version_indicator](https://user-images.githubusercontent.com/52931751/95393608-baba4280-08af-11eb-8813-2c314ca01692.jpg)

**Comment by akslay** [comment]
![quickstart_version_indicator](https://user-images.githubusercontent.com/52931751/95393531-a1b19180-08af-11eb-9aa4-8e7c3c8b90cb.jpg)

**Comment by joeparsons** [comment]
## Implementation options

### Drupal 7
https://git.drupalcode.org/project/navbar/-/blob/7.x-1.x/navbar.api.php#L13-150

### Drupal 9
https://api.drupal.org/api/drupal/core%21modules%21toolbar%21toolbar.api.php/function/hook_toolbar/9.0.x
