### ISSUE TITLE
Aggregation issues when using Asset Injector

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#3434]
## Problem/Motivation
We've started encountering this error after applying recent upstream updates on Pantheon sites that have Asset Injector installed:
```
Symfony\Component\HttpKernel\Exception\BadRequestHttpException: The libraries to include are encoded incorrectly. in Drupal\system\Controller\AssetControllerBase->Drupal\system\Controller\{closure}() (line 168 of /var/www/html/web/core/modules/system/src/Controller/AssetControllerBase.php).
```
### Describe the bug
Asset Injector assets are not able to be preprocessed by sites on Drupal 10.2.6 and higher.
This breaks other CSS and JS that aren't added via asset injector.

### To Reproduce

- Quickstart 2.10.x Drupal core 10.2.6 
- Asset injector 2.19 enabled
 - Add either CSS or JS rules (Ensure they are set to be preprocessed)
 - Turn on CSS and JS preprocessing/aggregation
 
## Proposed resolution
Update Asset Injector to version 2.20 to include fix.

**Comment by trackleft** [comment]
How to reproduce
- Quickstart 2.10.x Drupal core 10.2.6 
- Asset injector 2.19 enabled
 - Add either CSS or JS rules (Ensure they are set to be preprocessed)
 - Turn on CSS and JS preprocessing/aggregation
