### ISSUE TITLE
Composer 2.0

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#349]
## What is the problem that we want to solve?
We need to investigate how ready we are to move to Composer 2.0, which will be released soon.

Packagist has started triggering the following warnings in the output of composer commands run using version 1.x:
```
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is about to be released and the older 1.x releases will self-update directly to it once it is released. To avoid surprises update now to the latest 1.x version which will prompt you before self-updating to 2.x.
```

Upgrade guide:
https://getcomposer.org/upgrade/UPGRADE-2.0.md

**Comment by trackleft** [comment]
Seems that all we would need to do, is create two PR's one against az-quickstart-scaffolding and another against az_quickstart.

In az_quickstart edit the composer.json to say
```        "composer/installers": "^1.7",
        "cweagans/composer-patches": "^1.0",```

In az-quickstart-scaffolding 

```        "composer/installers": "1.9.0",
        "cweagans/composer-patches": "1.7.0",```

**Comment by trackleft** [comment]
In https://github.com/az-digital/az-quickstart-dev/blob/main/composer.json
Changed
```    "require": {
        "dealerdirect/phpcodesniffer-composer-installer": "0.6.2",
        "drupal/core-dev-pinned": "*",
        "mglaman/drupal-check": "1.1.2",
        "pheromone/phpcs-security-audit": "dev-master#1b8a61d4ac8f4f1554bcbf67865f8e1c1b213bdd",
        "phpcompatibility/php-compatibility": "9.3.5",
        "sensiolabs/security-checker": "6.0.3"
    },
```
to
```
    "require": {
        "dealerdirect/phpcodesniffer-composer-installer": "0.7.0",
        "drupal/core-dev-pinned": "*",
        "mglaman/drupal-check": "1.1.2",
        "pheromone/phpcs-security-audit": "dev-main",
        "phpcompatibility/php-compatibility": "9.3.5",
        "sensiolabs/security-checker": "6.0.3"
    },
```

Forked https://github.com/FloeDesignTechnologies/phpcs-security-audit as https://github.com/az-digital/phpcs-security-audit

Applied composer 2 compatibility patch https://github.com/FloeDesignTechnologies/phpcs-security-audit/compare/master...az-digital:master

Made these changes to scaffolding repo, remove drupal console
https://github.com/az-digital/az-quickstart-scaffolding/pull/26/files

Made these changes to az_quickstart
https://github.com/az-digital/az_quickstart/pull/356/files
