### ISSUE TITLE
Remove deprecated set-env and add-path commands from actions

### ISSUE THREAD

**Issue by kevcooper** [az-digital/az_quickstart#353]
**Do not disclose security vulnerabilities here, please email us instead: 
az-digital-security@list.arizona.edu**

## Conditions of satisfaction
- [x] Replace all instances of set-env
- [x] Replace all instances of add-path
- [x] Update aws-actions/configure-aws-credentials

See the following for more details:
- https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
- https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path

**Comment by mmunro-ltrr** [comment]
Looks like this affects almost every repository where we used Actions!
