### ISSUE TITLE
User Profile manageable by faculty or staff using CAS account login

### ISSUE THREAD

**Issue by kevdevlu** [az-digital/az_quickstart#3553]
## Motivation
This is currently a feature in a custom College of Humanities module that could also be useful in QuickStart. 

**For faculty**, we would like for them to be able to update or add information to their profile page on their department's website by logging in using their netID. This information can include: 
- profile picture
- bio
- office hour location, hours, and scheduling information
- links to websites, publications, CV, etc.

Additionally, the user would be able to login (`.../cas`) and logout (`.../user/logout`) via a button on the footer. 
<img width="912" alt="image" src="https://github.com/user-attachments/assets/08951d38-0ef9-4521-b557-86479a5bb233">

**For site admin's** of departmental sites, we would like for them to be able to create a faculty account in the backend via their netID. This creation process also imports user fields as dictated beforehand by the site admin. These are some example fields that can be imported from EDS: 
- `phoneBookDisplayName`
- `employeeTitle`

## Proposed Resolution
People profiles (`az_person`) are a content type in Quickstart. We would want to continue using this content type. 
I am assuming that this was the original design because most departments don't want a giant list of actual users in the Drupal backend. 
When someone adds a CAS user from the backend, we would have a checkbox for them to also create a corresponding user profile accessible by the user that's being created.
This would create an az_person content type whose owner is the CAS user that was created. 
When the CAS user is logged in, they can edit their own content type (but not make new content). 

### Roles and Permissions considerations
No new role would need to be added. We only need to enable the permission `Person: Edit own content` for `Authenticated user`

## Additional context
Here's the current workflow in the custom COH module: 
1. A user admin goes to the backend and adds a CAS user 
    <img src="https://github.com/user-attachments/assets/a533304b-40b8-4bb2-9325-b22bbcd4b784" width="550" >

3. The system automatically creates a default image for the user and then imports "Full name" and "Campus Title" from EDS. The user admin then sets the new CAS user as a "Faculty" 
    <img src="https://github.com/user-attachments/assets/3462030b-37e9-4605-a924-2ec575280257" width="550" >

5. In the people view on the frontend, because the user is now a "Faculty", they show up in the Faculty section: 
     <img src="https://github.com/user-attachments/assets/67e794b8-bd3b-48aa-ac78-f7a3020f2717" width="550" >

7. The created user can now login as themselves and edit their own profile: 
     <img src="https://github.com/user-attachments/assets/ca70d898-1c84-471b-8ab0-cbffd340078a" width="550" >

**Comment by joshuasosa** [comment]
This sounds like a neat idea!

Letting nodes be owned by the person the profile is about sounds like a simple way to go about it. It'd just be pertinent for site owners to decide how content owned by others is handled when they leave.
![image](https://github.com/user-attachments/assets/ab2d2641-4b30-48d1-8da8-52990f7dfe58)

An alternative method, albeit more complicated, is the use of ACL and Content Access modules. In PTYS, we use those to add netIDs in a node's Access control area to let people edit their own profiles.
![image](https://github.com/user-attachments/assets/398ac1ef-13c8-4497-b075-db2e5103155d)

There are sometimes certain fields that admins want to keep control over. For example, PTYS wants to control what images are used for profile photos (no rubber duckies) and what email people can list (no personal ones, only UA ones). For that, we use the Field Permissions module to set that anyone can view the field, but only Content Administrator can edit the field.
