### ISSUE TITLE
Trellis Event Import Bulkform Issue

### ISSUE THREAD

**Issue by tadean** [az-digital/az_quickstart#3556]
## Problem/Motivation
Beginning in 2.11, the Trellis Event Import Form throws the following error:

```
Exception: No entity type for field Id on view az_event_trellis_import in Drupal\views\Plugin\views\HandlerBase->getEntityType() (line 735 of /app/web/core/modules/views/src/Plugin/views/HandlerBase.php).

#0 /app/web/core/modules/views/src/Plugin/views/field/BulkForm.php(181): Drupal\views\Plugin\views\HandlerBase->getEntityType()
#1 /app/web/core/modules/views/src/Plugin/views/field/BulkForm.php(594): Drupal\views\Plugin\views\field\BulkForm->getEntityTypeId()
```
 Seemingly this might be due to some changes in the BulkForm class in 10.3.

### To Reproduce
Visit `/admin/trellis-event-importer`

## Proposed resolution
Update the BulkForm child class `AZEventTrellisViewsField ` to avoid the issue

### Expected behavior
Event importer should not crash on view.

**Comment by joeparsons** [comment]
Possibly related Drupal 10.3 change records:
- https://www.drupal.org/node/3295826
- https://www.drupal.org/node/3115868

**Comment by tadean** [comment]
Looks like this is due to [Add an API for allowing modules to mark their forms as workspace-safe](https://www.drupal.org/project/drupal/issues/2986005)

Bulkform's implementation for checking whether a bulkform is safe for a workspace involves checking if the entity backing the field is tagged as workspace safe.

Since there is no entity backing the field in this case, that's understandable.
