### ISSUE TITLE
Embedding any block in a text paragraph breaks linked images

### ISSUE THREAD

**Issue by bberndt-uaz** [az-digital/az_quickstart#3569]
### Describe the bug
A link may be added to an image embedded in a text paragraph by clicking on the image to select it and then clicking the **Link media** button in the pop-up media toolbar. See this issue regarding the implementation of this feature in Quickstart: [Allow displaying images as linked images #2366](https://github.com/az-digital/az_quickstart/issues/2366).

However, if a block is embedded in the same text area, the link for the image will not work on the published page. Any block causes this behavior, even an empty flexible block.

**Note:** For guidance about the accessible use of images, especially those that are linked, see https://www.w3.org/WAI/tutorials/images/.

### To Reproduce

1. When editing a page, add a new Text paragraph to a page by clicking the **Add Text** button.
2. Click the **Insert Media** button in the editor toolbar.
3. Select an image and insert it into the text area.
4. Click the image to select it.
5. Click the **Link media** button in the row of icons above/below the image.
6. Enter any link and click the green check mark button.
7. Click elsewhere in the text area to deselect the image (you may need to click the new line button on the image).
8. Click the **Embed Content Block** button in the editor toolbar.
9. Select any block, click the **Next** button, and then click the **Embed** button.
10. Save the page.
11. Observe that the image link does not work on the published page.

## Proposed resolution
This may be a CKEditor 5 issue. As a workaround, users can arrange their content to ensure that linked images are not embedded in the same text paragraph as a content block.

### Expected behavior

Linked images should be functional regardless of what other content is embedded in the same text paragraph.

## Additional context
When the link of the linked image works correctly, it appears that the HTML of that section is malformed: the `<p>` element containing the `<a>` element is closed before the `<a>` element is closed. Then, after the `<a>` element is closed, an extra unclosed `<p>` tag is added.

**Comment by joeparsons** [comment]
Possibly related Drupal core/contrib issues:

- [_filter_autop() breaks links around the tag](https://www.drupal.org/project/drupal/issues/3075527)
- [Prevent drupal links being added to embedded entities that contain links when rendered](https://www.drupal.org/project/entity_embed/issues/3061449)

**Comment by bberndt-uaz** [comment]
This issue was likely introduced in Quickstart [2.9.0](https://github.com/az-digital/az_quickstart/releases/tag/2.9.0). In testing a couple sites, I found that the issue was **not** present on a Quickstart 2.8.3 site, but it **was** present on a Quickstart 2.9.5 site.
