### ISSUE TITLE
MVP 2 Update View paragraph options

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#360]
- Filter views listing to only front-end views (Don't allow master display selection)
- Add more options for include title, items per page, pagination?
- Update argument field to use taxonomy term names instead of IDs?
- Assess additional options per view

**Comment by trackleft** [comment]
Release note needed to explain what to do when a view previously selected before this update in a views reference field no longer exists in the list of referenceable views.

**Comment by trackleft** [comment]
To disallow master, we might just have to disable the master display for each view.

**Comment by joeparsons** [comment]
Per @camikazegreen:
>I might eventually make a separate issue about “Update argument field to use taxonomy term names instead of IDs?” but it’s not high priority.

Placeholder issue created: #3134
