### ISSUE TITLE
Add Recent News Marquee demo content

### ISSUE THREAD

**Issue by djcelaya** [az-digital/az_quickstart#3653]
## Motivation
There is a possible visual error in Recent News Marquee (see #3438). Rather than recreating the exact circumstances for that regression to appear, I would like to adjust the existing demo content to present this issue. I will then correct the error in a follow up issue. This allows us to always now have a Recent News Marquee element available to test with future improvements.

### Is your feature request related to a problem? Please describe.
Yes, this is foundational work for #3438 

## Proposed Resolution
I will adjust the News Views page so that a Recent News Marquee is present on the bottom of the page. I will additionally add a caption and photo credit to the top news story. This should cause the Recent News Marquee paragraph to show the error presented [here](https://github.com/az-digital/az_quickstart/issues/3438). If not, increase the length of the caption.

### Describe alternatives you've considered
Do not adjust demo content and instead just create News items and the Recent News Marquee paragraph manually.

**Comment by djcelaya** [comment]
I have discussed this with @danahertzberg on 8/19/14 and she would also like a summary added for the top news story - just so we have one in place to see and test in the future.

**Comment by djcelaya** [comment]
@danahertzberg I discovered that some of our demo News stories already have summaries set but the importer is not configured correctly to read those into the appropriate field. I tested and fixed that locally...it's a 1-2 liner. Should I include that here (a little bit scope creepy) or address that in a separate issue?

**Comment by danahertzberg** [comment]
> @danahertzberg I discovered that some of our demo News stories already have summaries set but the importer is not configured correctly to read those into the appropriate field. I tested and fixed that locally...it's a 1-2 liner. Should I include that here (a little bit scope creepy) or address that in a separate issue?

Add it here if you can. It pertains to news. If it makes sense to get this merged and allow more time for that issue separately, I'll let that be your call. Thanks!
