### ISSUE TITLE
JS Theme Exception

### ISSUE THREAD

**Issue by joshuasosa** [az-digital/az_quickstart#3671]
## Problem/Motivation
In certain cases, an exception may be thrown with the compressed JS file.

### Describe the bug
Exception: Only file JavaScript assets can be optimized. in Drupal\Core\Asset\JsOptimizer->optimize() (line 31 of /core/lib/Drupal/Core/Asset/JsOptimizer.php).

> #0 /core/lib/Drupal/Core/Asset/JsCollectionOptimizerLazy.php(178): Drupal\Core\Asset\JsOptimizer->optimize()
> #1 /core/modules/system/src/Controller/AssetControllerBase.php(184): Drupal\Core\Asset\JsCollectionOptimizerLazy->optimizeGroup()
> #2 [internal function]: Drupal\system\Controller\AssetControllerBase->deliver()
> #3 /core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()
> #4 /core/lib/Drupal/Core/Render/Renderer.php(638): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
> #5 /core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(121): Drupal\Core\Render\Renderer->executeInRenderContext()
> #6 /core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()
> #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(181): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
> #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
> #9 /core/lib/Drupal/Core/StackMiddleware/Session.php(53): Symfony\Component\HttpKernel\HttpKernel->handle()
> #10 /core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle()
> #11 /core/lib/Drupal/Core/StackMiddleware/ContentLength.php(28): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
> #12 /core/modules/big_pipe/src/StackMiddleware/ContentLength.php(32): Drupal\Core\StackMiddleware\ContentLength->handle()
> #13 /core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\big_pipe\StackMiddleware\ContentLength->handle()
> #14 /core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
> #15 /core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle()
> #16 /core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
> #17 /core/lib/Drupal/Core/StackMiddleware/AjaxPageState.php(36): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
> #18 /core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\AjaxPageState->handle()
> #19 /core/lib/Drupal/Core/DrupalKernel.php(741): Drupal\Core\StackMiddleware\StackedHttpKernel->handle()
> #20 /index.php(19): Drupal\Core\DrupalKernel->handle()
> #21 {main}

### To Reproduce
It's not exactly clear how to reproduce, but it can appear in site logs.

## Proposed resolution
I encountered multiple similar exceptions and investigated the cause by going into JsCollectionOptimizerLazy.php and having it print the $js_asset. I fixed them by adding `{ type: external, minified: true }` to my CSS and JS externally-sourced files listed in my custom module's libraries.yml.

It similarly printed this file as being the issue:
Array ( [preprocess] => [type] => external [group] => -100 [data] => https://cdn.digital.arizona.edu/lib/arizona-bootstrap/2.0.27/js/arizona-bootstrap.bundle.min.js [version] => -1 [weight] => 3.3333333333333E-5 [cache] => 1 [attributes] => Array ( ) [license] => Array ( [name] => GPL-2.0-or-later [url] => https://www.drupal.org/licensing/faq [gpl-compatible] => 1 ) [scope] => footer )

In AZ Barrio's `az_barrio_library_info_alter` function, I tried adding:
`$az_bootstrap_js_info['minified'] = TRUE;`
after
`$az_bootstrap_css_info['minified'] = TRUE;`
and that resolved the error for me.

I would propose to add that minified option to the az_bootstrap JS info.

### Expected behavior
A normal JavaScript file is generated instead of the exception.

## Additional context
AZ Quickstart 8.11.1, PHP 8.3.10

**Comment by joeparsons** [comment]
Wow, good find!
