### ISSUE TITLE
Add Generator Metatag 

### ISSUE THREAD

**Issue by tadean** [az-digital/az_quickstart#3678]
## Motivation
In quickstart 1, we had a metatag that indicated the generator of the markup:
```
<meta name="generator" content="UA Quickstart 7 (https://quickstart.arizona.edu)" />
```
We have had requests for a similar generator tag for Quickstart 2 to determine sites that are using the quickstart distribution.

### Is your feature request related to a problem? Please describe.
It would be useful for web teams on campus to be able to identify if a site is a Quickstart site.

## Proposed Resolution
Add a generator metatag to Quickstart 2.

### Describe the solution you'd like
Notably, we should not add any information about version or patch level, as this would be an unnecessary information disclosure.

### Describe alternatives you've considered
Not having a generator tag, with the view that this is information disclosure.

**Comment by bberndt-uaz** [comment]
For reference, here is where the tag is set in Drupal: https://git.drupalcode.org/project/drupal/-/blob/11.x/core/modules/system/system.module#L623-631.
```php
    // Show Drupal and the major version number in the META GENERATOR tag.
    'system_meta_generator' => [
      '#type' => 'html_tag',
      '#tag' => 'meta',
      '#attributes' => [
        'name' => 'Generator',
        'content' => 'Drupal ' . $version . ' (https://www.drupal.org)',
      ],
    ],

```

**Comment by joshuasosa** [comment]
Another point of reference, my dept has generator disabled for a little less information disclosure.

**Comment by tadean** [comment]
> Another point of reference, my dept has generator disabled for a little less information disclosure.

Thanks @joshuasosa - Do you use `remove_generator` for this purpose? Or another mechanism?

I think it would be desirable that if the functionality in this issue is implemented, that we ensure that it doesn't take place on any site where the generator tag has been removed.

**Comment by joshuasosa** [comment]
Using [remove_http_headers](https://www.drupal.org/project/remove_http_headers/)
