### ISSUE TITLE
Standard text formatter is converting line breaks into HTML on embedded entities (media) breaking embedded media HTML.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#3689]
## Problem/Motivation
I'm seeing weird space in embedded media.

### Describe the bug
The current filter processing order is this.
<img width="602" alt="image" src="https://github.com/user-attachments/assets/f94f231b-bbc4-4732-a6b0-da88ea3bdcd2">

In practice, this means that the rendered media is processed, which is not desireable.

### To Reproduce

Create a media image.
Add caption and credit
Embed that media image in a text area using the az_standard text format.
See extra spaces in the caption area.
<img width="887" alt="image" src="https://github.com/user-attachments/assets/35d8ec2a-4145-46a6-9e06-7843b89cda38">

<img width="1097" alt="image" src="https://github.com/user-attachments/assets/ba4c045c-79ae-4749-9b24-d8d176899e16">

## Proposed resolution

Change the  filter processing order so that embedded content is added last.

<img width="829" alt="image" src="https://github.com/user-attachments/assets/570bf3ca-c700-4929-89a0-751c16c93955">

### Expected behavior

Media should be embedable without being altered by the text formatter.

**Comment by bberndt-uaz** [comment]
With a local 2.11.1 build, I tested switching the order of `Embed media` and `Convert line breaks into HTML (i.e. <br> and <p>)` and unfortunately this solution appears to break linked images.

**Comment by bberndt-uaz** [comment]
Regarding linked images, here are some related drupal.org issues as found by @joeparsons in a comment on [Embedding any block in a text paragraph breaks linked images #3569](https://github.com/az-digital/az_quickstart/issues/3569):

> Possibly related Drupal core/contrib issues:
> 
> - [_filter_autop() breaks links around the tag](https://www.drupal.org/project/drupal/issues/3075527)
> - [Prevent drupal links being added to embedded entities that contain links when rendered](https://www.drupal.org/project/entity_embed/issues/3061449)
