### ISSUE TITLE
Regression in Full Width Media Width

### ISSUE THREAD

**Issue by tadean** [az-digital/az_quickstart#3693]
## Problem/Motivation
Sometimes, full width media paragraphs load as the same width as the surrounding container, and a brief while later visibly expand to fill the screen. This has been reported as a regression in the `2.11.x` branch, and also reported in `2.10`.x by a few users though seemingly to a lesser extent.

### Describe the bug
In sites where the bug is in evidence, full width media paragraphs will load with their width equal to the surrounding bootstrap container, and then a (brief) time later, expand to fill the screen.

Potentially this may indicate that javascript load order has changed, or other potential time-based issues.

### To Reproduce
Repeatedly load a page containing a full width media. The issue will only be in evidence for a short time.

## Proposed resolution
TBD - determine cause. A change in javascript load order is suspected.

### Expected behavior
As near as possible, full width media should be full width a very short time after pageload, if not initially. In particular it's desirable there be no visual pop in width that is visible to the user.

##  Screenshots
![Screenshot from 2024-09-09 14-40-51](https://github.com/user-attachments/assets/64d192ab-a046-4249-a1e3-83bf6a6ae0b9)

**Comment by trackleft** [comment]
This file does all of the resizing of the https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_paragraphs/js/az_paragraphs_full_width.es6.js
