### ISSUE TITLE
Extra main landmark role in page template

### ISSUE THREAD

**Issue by bberndt-uaz** [az-digital/az_quickstart#3714]
### Describe the bug
According to [Mozilla Developer Network documentation regarding the `main` landmark role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/main_role#use_only_one_main_role_per_document):

> 
> The main [landmark role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles#3._landmark_roles) should only be used once per document.
> 

This is an accessibility concern.

Bootstrap Barrio includes a `main` element on all pages, which effectively has the role of `main`. (In fact, [the role attribute is added to this element](https://git.drupalcode.org/project/bootstrap_barrio/-/blob/5.x/bootstrap_barrio.theme?ref_type=heads#L187-191) anyway.)
```php
  $variables['content_attributes'] = [
    'class' => ['main-content', $content_width],
    'id' => ['content'],
    'role' => ['main'],
  ];

```

The Arizona Barrio page template adds an extra `main` landmark role:
https://github.com/az-digital/az_quickstart/blob/main/themes/custom/az_barrio/templates/layout/page.html.twig#L173

```twig
<div id="main" role="main">
```

### To Reproduce

View any Quickstart page and observe that there are two instances of `role="main"`.

## Proposed resolution
Remove the extra `role="main"` from the AZ Barrio page template.

### Expected behavior

Quickstart pages should only have one `main` landmark role per document.

**Comment by joshuasosa** [comment]
Considering this minor issue with attribute placement, it could be good to do a fuller validation on AZ Quickstart.
Example: https://validator.w3.org/nu/?doc=https%3A%2F%2Fquickstart.arizona.edu%2F

Technically, W3's validator says:

> Warning: The main role is unnecessary for element main.

But it might still be useful as a backup for old browsers that could be in use which don't support main element's semantics. However, on that point, I don't think AZ Quickstart necessarily supports old browsers, which could mean the main role attribute could be removed. But as far as I know, it doesn't hurt to have this redundancy.
