### ISSUE TITLE
Restore the display of 12:00 am and 12:00 pm as "midnight" and "noon" for events

### ISSUE THREAD

**Issue by bberndt-uaz** [az-digital/az_quickstart#3747]
## Problem/Motivation
We encountered a bug with the display of event dates that end at 12:00 pm: when the date range is displayed using the AP Style formatter, that end time is changed to match whatever the start time is (e.g., `10:00 am - 12:00 pm` becomes `10:00 am - 10:00 am`). This problem occurs with both 12:00 am and 12:00 pm when they are set as the end time for an event. When they are set as the start time, they are displayed correctly.

In troubleshooting this issue, we discovered that Quickstart event displays do not have the AP Style setting enabled to show 12:00 pm and 12:00 am with the words "noon" and "midnight". However, from reviewing test sites on Quickstart 2.7 and 2.10, it appears that Quickstart has always displayed "noon" and "midnight" even though the setting was not enabled. The change in display is likely due to updates in [AP Style Date 2.0.2](https://www.drupal.org/project/date_ap_style/releases/2.0.2).

### To Reproduce

1. Create a new event
2. Set the start time to a time in the morning (before noon)
3. Set the end time to 12:00 pm
4. Save the page
5. Observe that the end time displayed is not 12:00 pm. Instead, it is the same as the start time.

## Proposed resolution
We could change the display of time ranges for events to replace "12:00 pm" and "12:00 am" with the words "noon" and "midnight"), restoring the behavior of previous Quickstart versions. Enabling this setting for the AP Style formatter would also resolve the issue we originally encountered.

We should consider whether to enable the setting to capitalize "noon" and "midnight" as well.

**Comment by joeparsons** [comment]
AP Style Date module issue that sounds related:
https://www.drupal.org/project/date_ap_style/issues/3387403
