### ISSUE TITLE
Capture akslay's layout builder work

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#38]
## Motivation
We need to capture @akslay's really cool layout builder work in a prototype module (or multiple modules).

## Proposed Resolution
Export config from @akslay's development site on Pantheon

**Comment by akslay** [comment]
Relevant document associated with this PR: https://docs.google.com/document/d/1Nr7dF6B5tf8jkU9FD039begFGbhkuznF9q0d5WRKqvE/edit?usp=sharing
