### ISSUE TITLE
Create New Templates for Heading Elements in field_group

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#3861]
## Problem/Motivation

Some content editors have been relying on a bug in `field-group-html-element.html.twig` to add space between elements. Currently, blocks embedded in content are output using the `field-group-html-element.html.twig`, which applies the spaceless filter to all rendered HTML. 

The spaceless filter was applied in this commit: https://github.com/az-digital/az_quickstart/commit/a119b5cd314a38992e7f24589fe86134860a0fdd#diff-85998c378764d17df837312a6a3594e772f590e5ef1f3311eaf4252c886ff3f7

### Describe the bug
The spaceless filter is too aggressive in the `field-group-html-element.html.twig` template, resulting in unintended removal of spaces that content editors may rely on for layout purposes. 

## Proposed resolution
I propose creating new templates specifically for heading elements that do not utilize the spaceless filter. This will allow content editors to maintain the necessary spacing for headings while still benefiting from the existing functionality for other elements.

Proposed files:
`field-group-html-element.h1.twig`
`field-group-html-element.h2.twig`
`field-group-html-element.h3.twig`
`field-group-html-element.h4.twig`

##  Screenshots
![image](https://github.com/user-attachments/assets/c27fb106-4fcd-41ff-ac8a-138507bfaff4)

## Additional context
This issue is most prevalent with inline buttons within embedded content blocks.

**Comment by natebyerley** [comment]
Potentially also happening with taxonomy labels

![Screenshot 2024-11-06 at 3 23 20 PM](https://github.com/user-attachments/assets/2be63f61-5ec3-4d66-9b55-fea03cddc386)

![Screenshot 2024-11-06 at 3 29 08 PM](https://github.com/user-attachments/assets/dabdfa1d-b76a-4d22-b000-1101f0eaa970)
