### ISSUE TITLE
Update Global Footer Links

### ISSUE THREAD

**Issue by natebyerley** [az-digital/az_quickstart#3863]
## Conditions of satisfaction

A. Update 'Annual Security Report' link to point to https://clery.arizona.edu/asr - [https://app.screencast.com/tfhNGTRX9S6dn](https://app.screencast.com/tfhNGTRX9S6dn)

B. Please remove the 'Outreach & Extension' footer link (this subdaomin was taken down ~May of this year)

C. Add a 'Campus Store' link https://shop.arizona.edu/ , to match the recent change on Arizona.edu: [https://app.screencast.com/3lyjJRMihif8K](https://app.screencast.com/3lyjJRMihif8K)

Above requests came in via two tickets:

A. [SCTASK0056500](https://uarizona.service-now.com/nav_to.do?uri=sc_task.do%3Fsys_id=65f9e6fa1bc95a103578773bdc4bcbec%26sysparm_stack=sc_task_list.do%3Fsysparm_query=active=true)

B. & C. [SCTASK0057828](https://uarizona.service-now.com/nav_to.do?uri=sc_task.do%3Fsys_id=0fb353731ba15ad03578773bdc4bcba3%26sysparm_stack=sc_task_list.do%3Fsysparm_query=active=true)

**Comment by danahertzberg** [comment]
Can we put a db update with this as well?
