### ISSUE TITLE
Update AZEnterpriseAttributesMigrationSync

### ISSUE THREAD

**Issue by tadean** [az-digital/az_quickstart#3866]
## Motivation
`AZEnterpriseAttributesMigrationSync`'s parent class, `MigrationImportSync` (in `migrate_tools`) has been changed in version `6.0.5` to no longer use state for its storage. We need to update our implementation to match. 

This event subscriber is responsible for unpublishing enterprise attributes which disappear from the feed.

### Describe the solution you'd like
`AZEnterpriseAttributesMigrationSync` should be refactored to not use state for storage.

**Comment by trackleft** [comment]
Hopefully we'll get their reported performance improvements.

**Comment by tadean** [comment]
https://www.drupal.org/project/migrate_tools/releases/6.0.5
