### ISSUE TITLE
Apply Bootstrap styles inside CKEditor

### ISSUE THREAD

**Issue by jwmoore1** [az-digital/az_quickstart#387]
## Motivation
Currently, styles can be applied, but can only be seen once the page is saved, which makes for a poor editing experience.

### Describe the solution you'd like
When styles are selected, they should be applied to the text in the editor, so the resulting styling can be seen in real time while edits are being made.

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
This would apply to all roles that can make edits with CKEditor.

**Comment by trackleft** [comment]
This may or may not be useful https://www.drupal.org/docs/8/theming-drupal-8/defining-a-theme-with-an-infoyml-file#ckeditor_stylesheets
