### ISSUE TITLE
Boostrap Grid "Choose a layout" displays options off screen

### ISSUE THREAD

**Issue by jwmoore1** [az-digital/az_quickstart#389]
## Problem/Motivation
When using Bootstrap Grid within CKEditor, the "Choose a layout" options display off screen and horizontal scrolling is required. This causes a poor user experience because it is not easy to see the available options.

### To Reproduce
1. Selection the BS Grid button in CKEditor on a Page
2. choose any number of columns. 
3. The following selection of options on "Choose a layout" will be pushed off screen.

## Proposed resolution
Add/fix CSS so all options are always visible.

### Expected behavior
When viewing "Choose a layout" options, they should always be visible to the user.

**Comment by danahertzberg** [comment]
Covered in #736
