### ISSUE TITLE
Investigate Two-step Edit Forms for Card Widget

### ISSUE THREAD

**Issue by tadean** [az-digital/az_quickstart#390]
## What is the problem that we want to solve?

During comparison between the approach of nested paragraphs and custom field plugins for cards, one benefit of the nested paragraphs approach is that the preview of each card was rendered and cards could be edited individually. This was convenient since it meant fewer active edit forms and kept page length down, and also made it easier to reorder cards within a deck.

By comparison, with the card field plugin, opening a card deck means rendering the edit form of every card, which makes it relatively more difficult to navigate and find the card you need to edit.

Now that we have custom plugins, we could investigate making the edit form of each card start off with a card preview and only render the edit form for that card if an edit button is pressed. (implementing this as a two-step form with an ajax refresh)

This would give some of the **UI advantages** of the nested paragraph approach without the corresponding database bloat issues of paragraphs.

## Conditions of success

Experiment if the card forms can be rendered as two-step pop open forms with an edit button.

**Comment by trackleft** [comment]
FYI I found this which seems to include orderability on multi-value field content within paragraphs https://www.drupal.org/project/paragraphs/issues/2825575
