### ISSUE TITLE
Spike: Determine the best way to implement schema.org metatags.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#3902]
## Problem Statement
To ensure our web entities are accurately represented and consumable by bots and search engines, we need a scalable solution to implement **templated schema.org markup** through our enterprise CMS (QuickStart).

## Feature Request and Context
The [schema.org Metatag module](https://www.drupal.org/project/schema_metatag) is central to schema implementation in Drupal but currently lacks the **CollegeOrUniversity** schema type. For institutions like the University of Arizona, this is critical, as this schema type is the most appropriate way to represent university websites.

**Relevant schema reference**: [CollegeOrUniversity](https://schema.org/CollegeOrUniversity).

---

## Proposed Solution
Determine whether the schema_metatag module can handle our use cases.
Determine feasibility of extending the [schema.org Metatag module](https://www.drupal.org/project/schema_metatag) by adding a new schema type: **CollegeOrUniversity**. 

## Alternatives Considered
1. **Custom Module**:
   - Create a standalone solution within the installation profile. However, this approach reduces scalability for updates or module compatibility.
2. **Alternative Schema Modules**:
   - Evaluate [JSON:LD module](https://www.drupal.org/project/jsonld). However, this module might require significant customization for seamless integration with the Metatag module.

---

### Anonymous User
- **None**: No impact.

### Authenticated User
- **None**: No impact.

### Content Editor
- Gains the ability to create, modify, or delete any **schema.org metatags** via the UI.

### Content Administrator
- Gains the ability to manage any **schema.org metatags**, including assigning values or defaults to fields.

### Administrator
- Gains the ability to:
  - Enable/disable schema types at a module level.
  - Set default values for any **schema.org metatags**.

**Comment by RyanDool** [comment]
Also a good resource as it considers Google's assumptions around Schema Markup https://docs.google.com/document/d/1EPY0-2zrUXmTGR4o01GcRm_IhA9YZxlGsDJKBSjfc6M/edit?usp=sharing

**Comment by trackleft** [comment]
It was determined that we can in fact use the schema_metatag module along with its sub-modules like schema_metatag_organization to achieve most of what we need, and it is feasible to add in some patches to get the rest.

In order to move quickly we can break this project into multiple steps that are easy to review.
- #3903
- #3904
- #3905
- #3644
- #3906
- #3907
- #3908
