### ISSUE TITLE
View Bulk Operations (VBO) version 4.3.0 has a missing submodule

### ISSUE THREAD

**Issue by ejsamboy** [az-digital/az_quickstart#3929]
## Problem/Motivation
Websites with View Bulk Operations (VBO) 4.3.0 previously installed are running into issues during upstream updates due to the missing actions permissions module, which was removed in this version. Updating VBO to 4.3.2 in Quickstart will fix this and prevent future errors.

**Reference:** https://www.drupal.org/project/views_bulk_operations/issues/3482519

### To Reproduce

- Apply Configuration Updates (QS 2.11.7) to a site already running the View Bulk Operations (VBO) module version 4.3.0.
- The error below will show up.
<img width="634" alt="Screenshot 2024-12-06 at 10 47 51 AM" src="https://github.com/user-attachments/assets/c4742ad9-bc37-45a5-89f3-5749b69985ec">

## Proposed resolution

- Update the View Bulk Operation module to the 4.3.2 version in Quickstart

**Comment by joeparsons** [comment]
Fix included in [2.11.8](https://github.com/az-digital/az_quickstart/releases/tag/2.11.8) and [2.12.0](https://github.com/az-digital/az_quickstart/releases/tag/2.12.0).
