### ISSUE TITLE
Update CKEditor icons for entity embed buttons

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#396]
Goal: Update CKEditor icons for entity embed buttons so they don't all use "E" and are more easily identifiable in Standard text format

**Comment by smitahantzios** [comment]
Hi Team,

Please provide the new icon that need to be updated and replaced for the "E" CKEditor icon. 

cc: @danahertzberg  @joeparsons

**Comment by smitahantzios** [comment]
@danahertzberg & @joeparsons - The above changes are content update. How can I commit these changes. Please advise me. If we want to do it directly on site. please share the credentials.

**Comment by cpoff** [comment]
New icons are:

Embed Content: https://fonts.google.com/icons?selected=Material+Icons+Sharp:token:&icon.query=post+add
Embed Content Block: https://fonts.google.com/icons?selected=Material+Icons+Sharp:token:&icon.query=dashboard+customize
