### ISSUE TITLE
Update paragraph previews to have expand/collapse functionality

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#403]
**Do not disclose security vulnerabilities here, please email us instead: 
az-digital-security@list.arizona.edu**

## Motivation
Allow content editors to expand truncated previews if looking for specific text to edit. Expand/collapse all or one at a time would provide the ultimate flexibility.

## Proposed Resolution
Provide expand/collapse all button near top of page. Provide expand/collapse button at bottom of each truncated paragraph preview.

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Content administrator: restrict to higher level permissions?
- Administrator

**Comment by smayden** [comment]
@danahertzberg Can this ticket be closed?

**Comment by danahertzberg** [comment]
@smayden Because we have the reorder drag and drop option now, right?

**Comment by danahertzberg** [comment]
Resolved already
