### ISSUE TITLE
Add in contextual filter for term category on AZ_Person

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#407]
## Motivation
We need to be able to filter People by Taxonomy term for use on Taxonomy pages or when using Arguments on the Persons Views. 

### Describe the solution you'd like
There should be a contextual filter added that will allow for filtering by either of the Taxonomy Terms.

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Anonymous user
- Authenticated user
- Content editor
  - Should be able to assign taxonomy terms to people
  - Should be able to add those taxonomy terms as arguments to the Person views to filter the view.
- Content administrator
- Administrator

**Comment by danahertzberg** [comment]
Can be pushed to GA release if no time
