### ISSUE TITLE
Re-visit grouping in the Person reorder/sort view

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#408]
## Motivation
The way that people and/or taxonomy terms are grouped in the Reorder Person view is less than ideal. 

### Is your feature request related to a problem? Please describe.
Draggable views sort does not sort, but can be enabled in the view settings

## Proposed Resolution
[ ] Set both person views to use the person draggable view to sort.

## Additional context
Drupal.org https://www.drupal.org/project/draggableviews/issues/3153830

**Comment by danahertzberg** [comment]
@joeparsons will assess patch in linked Drupal.org issue.

**Comment by trackleft** [comment]
Reading the issue on drupal.org, the status of the ticket is **Closed/Fixed** but the recommendation is to resave any view with the issue.

**Comment by natebyerley** [comment]
I believe this is happening on sites less than 15 months old.  Sites that this has been an issue:

azs-cbc | created Feb 11 2022 | [SCTASK0021600](https://uarizona.service-now.com/nav_to.do?uri=sc_task.do%3Fsys_id=67d2e98e1b565510bdf95465624bcb66%26sysparm_stack=sc_task_list.do%3Fsysparm_query=active=true)
azs-psychology | created Oct 26 2021

**Comment by trackleft** [comment]
The underlying issue is that the option for displaying all values in 1 row for multi-value field is not working as expected.

Instead of showing a node once when it references multiple taxonomy terms, it shows that node once for each referenced term.

**Comment by trackleft** [comment]
Turns out that the issue is with the sorting mechanism in views.
Sorting the draggable view by category, which is a multi-value field, overrides the "Display all values" setting.
