### ISSUE TITLE
Add Chosen to AZQS install profile

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#409]
## Motivation
It's nice to be able to select multiple elements, so a checkbox is preferred over a select list, but some sites have extremely long lists of taxonomy terms that make the checkbox interface too cumbersome. 

### Describe the solution you'd like
In Quickstart 1.0, we solved this using the Chosen module:
https://www.drupal.org/project/chosen

This module provides a select list interface, but makes it easy to use autocomplete and intuitively multi-select.

*I don't really think that this fits within the Person MVP, but I do think that it could easily be added as part of MVP and is part of parity with QS1. I do think though that this would classify more as "polish" and is therefore lower priority in my mind.

**Comment by akslay** [comment]
The Chosen module requires the Chosen JS library. This poses the question of how this is going to work in Pantheon. Note from @tadean :
> In order to have that working, that drush command has to be run during the install process somehow or chosen won't be present
