### ISSUE TITLE
Fix narrow editing area

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#423]
**Issue:** Editing area of a page is not taking up all of the allowable space.

Looks like this max-width is affecting the narrow editing area.
```
@media screen and (min-width: 61rem)
.layout-region--node-main .layout-region__content, .layout-region--node-footer .layout-region__content {
    max-width: 48rem;
    margin-right: auto;
    margin-left: auto;
}

**Comment by danahertzberg** [comment]
I'm not seeing any existing Claro theme overrides or settings in the az_quickstart repo. How should I proceed with making this change?

**Comment by trackleft** [comment]
Turns out there is an issue about this on D.O. https://www.drupal.org/project/drupal/issues/3184667#comment-13925157

**Comment by trackleft** [comment]
And there is an "Undo" patch https://www.drupal.org/files/issues/2020-12-16/3184667-8.patch

**Comment by trackleft** [comment]
Back to normal https://7492ce2e-d4f2-428a-9817-fb7ad0a8f3bc.probo.build/user?destination=node/add/az_flexible_page
