### ISSUE TITLE
Config Distro Import Ignore Bug

### ISSUE THREAD

**Issue by tadean** [az-digital/az_quickstart#428]
## Problem/Motivation
On the Config Distro import screen, it is intended that there be a way to ignore updates to a given module during the import process. Currently, if module updates are deselected the updates to that module are still imported anyway on import. This is an issue that affects the Config Distro module itself and not just within quickstart. If possible, a solution for the issue should be found.

Most likely it seems that the config update form is not respecting the value of the checkbox (or something simliar)

**Comment by joeparsons** [comment]
Does the 'Config Distro Ignore' submodule have anything to do with this?
https://git.drupalcode.org/project/config_distro/-/tree/8.x-1.x/modules/config_distro_ignore

**Comment by tadean** [comment]
No, that module is for ignoring specific configuration elements by name (similar to a list of paths in a block page visibility list). The issue above refers to the fact that the form that performs imports is ignoring the checkboxes that allow the user to ignore a specific module at import time.

**Comment by joeparsons** [comment]
> No, that module is for ignoring specific configuration elements by name (similar to a list of paths in a block page visibility list). The issue above refers to the fact that the form that performs imports is ignoring the checkboxes that allow the user to ignore a specific module at import time.

Ok, sorry/thanks.
