### ISSUE TITLE
Find a better home for `az_card` and `az_row` view modes

### ISSUE THREAD

**Issue by akslay** [az-digital/az_quickstart#437]
The following view mode files are currently defined/housed within `/modules/custom/az_person/config/install`: 

- core.entity_view_mode.node.az_card.yml
- core.entity_view_mode.node.az_row.yml

While this works, they should really be housed in a more generic location since other entities can make use of the view modes. I tried moving the view modes to the root `config` folder, but it resulted in "unmet dependencies" errors for AZ Person. Also tried moving the items that require those view modes to the `optional` folder (instead of `install`) but that resulted in things not working properly for the AZ Person content type.

Further research/testing required.

This came about during work performed on this ticket: https://github.com/az-digital/az_quickstart/issues/413
Was going to fix it in that issue, but it was becoming a blocker and would be better as a separate issue.

**Comment by danahertzberg** [comment]
Is this done? Does it need further discussion?

**Comment by danahertzberg** [comment]
Joe confirmed this is complete by way of #471

**Comment by danahertzberg** [comment]
https://github.com/az-digital/az_quickstart/tree/main/modules/custom/az_core/config/install
