### ISSUE TITLE
Add .nav-stacked styles to Arizona Bootstrap

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#444]
Update the heading on sidebar navs to contain the classes `h4` `mt-md-5`

**Comment by trackleft** [comment]
Looks like we missed this in the migration section, but vertical orientation looks like the likely alternative?
https://digital.arizona.edu/arizona-bootstrap/docs/2.0/components/navs/#vertical

**Comment by danahertzberg** [comment]
Looks like that is still just styling the main nav which stops at 2 levels deep. It makes sense to me to add the styles specific to the sidebar nav so there isn't any CSS confusion. What do you think @trackleft?

**Comment by danahertzberg** [comment]
I would recommend we keep the same classes for all levels (`nav` `nav-pills` `flex-column`) and we can style that in bootstrap similar to how I defined the nested styles in BS3.

**Comment by danahertzberg** [comment]
Bootstrap sidebar updates

- [ ] Add h4 class to heading (az_quickstart ticket needed)
- [ ] Update sidebar nav styles on Arizona Bootstrap

```
ul.nav.nav-pills.flex-column>li {
    border: solid 1px $bg-gray-200;
    margin: -1px 0 0 0;
}
ul.nav.nav-pills.flex-column>li>a:hover,
ul.nav-pills.flex-column>li>a:focus {
    background-color: $bg-gray-200;
}
ul.nav.nav-pills.flex-column>li>ul>li {
    border: none;
}
ul.nav.nav-pills.flex-column>li>ul>li>a {
    font-weight: 400;
    color: $blue;
    padding-left: 25px;
}
```


$bg-gray-200 = #e9ecef
$blue = #0c234b

**Comment by joeparsons** [comment]
Drupal 8.x change record Re: the core change that makes it harder to apply region-specific styles/templates to blocks:
https://www.drupal.org/node/2011434

**Comment by trackleft** [comment]
Just wonder if I forgot why it was supposed to be region specific.
