### ISSUE TITLE
Summary link field cannot use tokens

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#446]
In D7 several content types have the ability to add a "summary link" that is used to point to a different site/url when that item appears in different view modes (e.g. takes a news story outside the site). By default the link field points to [node:url] to take users to the node.

For the news content type, we were unable to create the summary link field since in D9 you cannot add a token for the default on the field. In the 1/13/21 we decided to remove from news content type and explore solutions as a separate issue.

**Comment by danahertzberg** [comment]
Does the token module do what we need?? https://www.drupal.org/project/token

**Comment by smayden** [comment]
> Does the token module do what we need?? https://www.drupal.org/project/token

I don't think so. We already have the token module enabled in QS2. If I'm remembering right there was an existing issue with the module where the URL field wasn't working.

**Comment by danahertzberg** [comment]
Investigate existing patches or modules as first step. Compare those to creating custom solution.

**Comment by smayden** [comment]
This Drupal ticket may be relevant and has some recent patch/work that we might want to look at:

https://www.drupal.org/project/drupal/issues/2903336

**Comment by trackleft** [comment]
Added a merge request to drupal core: https://git.drupalcode.org/project/drupal/-/merge_requests/1076 which adds context to tokens so we can use tokens like [node:url:path]

**Comment by trackleft** [comment]
The obvious alternative to this we might consider is an external news content type.
