### ISSUE TITLE
Add EditorConfig file to Quickstart

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#449]
## Motivation
[EditorConfig](https://editorconfig.org/) helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs.

### Describe the solution you'd like
We should consider copying the EditorConfig file from Drupal core to the Quickstart repo.

**Comment by trackleft** [comment]
Drupal version https://git.drupalcode.org/project/drupal/-/blob/9.2.x/.editorconfig
