### ISSUE TITLE
Decide whether or not to keep Display Suite

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#45]
## What is the problem that we want to solve?
The contrib [Display Suite module](https://www.drupal.org/project/ds) was added as a dependency as part of #38 and #39.  We need to decide whether we want to keep the module as a dependency long term or not.

Display Suite was used for #39 primarily because @akslay preferred the more minimal markup of the Display Suite provided layout plugin templates over the layout plugin templates provided by core out of the box.  It should be possible to create our own layout plugins and templates with whatever markup we want as a replacement if none of the other features provided by the module are needed/used.

As is, the module has added stub configuration to the `third_party_settings` of various other exported configuration entities including entity_view_display settings which we probably don't want to have to maintain if not really needed ([example third party settings](https://github.com/az-digital/az_quickstart/blob/d6de6c775b1e640e253c80024927d73da76d2a2a/modules/custom/az_blocks/config/install/core.entity_view_display.block_content.az_accordion.default.yml#L13-L38)).  We should determine if any of the exported Display Suite third party settings are actually needed/being used for anything.

## Conditions of satisfaction
- [ ] The considered options are documented
- [ ] A recommended next step is documented
- [ ] An estimate of time and effort is provided for the recommendation
- [ ] …

**Comment by camikazegreen** [comment]
The decision was made to not include/remove Display Suite from Quickstart.
