### ISSUE TITLE
Add sort packages configuration to composer.json

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#462]
## Conditions of satisfaction
- [x] Composer should automatically sort packages alphabetically when added.

Example: https://stackoverflow.com/a/52852369/1086610
Example in scaffolding repo: https://github.com/az-digital/az-quickstart-pantheon/blob/master/composer.json#L27

**Comment by michaelhagedon** [comment]
Let me see if I can use this seemingly simple task as a way to figure out how to make a contribution.
