### ISSUE TITLE
Move templates for 'Text with Background' and 'Text on Media' Paragraph types to submodules

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#463]
## Problem/Motivation
The templates for the 'Text with Background' and 'Text on Media' paragraph types are currently included in the AZ Barrio templates directory instead of within the corresponding az_paragraphs submodules.

### Describe the bug
The implementation that we merged for #290 added a template for the 'Text with Background' paragraph type to the AZ Barrio theme.  This is inconsistent with how we've organized our templates in the past.

## Proposed resolution
We discussed this issue in our 2021-01-22 Friday meeting and it was decided that it would be best to move the 'Text with Background' template into the `az_paragraphs_text_background` module instead.  Doing so may require altering Drupal's default template suggestions via a module hook but this is the way we've organized our templates so far and we want to remain consistent.

**Comment by trackleft** [comment]
This clears up how I was thinking about this, I'd thought that we had discussed all templates being in the theme long ago, I am fine with either way as long as it is consistent.
