### ISSUE TITLE
Remove unused CSS files in az_flexible_page module

### ISSUE THREAD

**Issue by jwmoore1** [az-digital/az_quickstart#485]
There are multiple CSS files in the css directory within the az_flexible_page module; however, only the az-flexible-page-edit-form.css file is currently being used from the az_flexible_page.libraries.yml file. The other files are mostly leftover from previous work involving layout builder. Any css/files related to layout builder can be removed.

## Conditions of satisfaction
- [ ] Should remove all CSS/files no longer in use in az_flexible_page module

**Comment by BaoNguyen09** [comment]
I found in the [az_flexible_page.libraries.yml](https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_flexible_page/az_flexible_page.libraries.yml) file that az_flexible_page.theme.css is also being used so there're only 2 css files to be removed (az_flexible_page.css and az_flexible_page_layout.css) right?
