### ISSUE TITLE
Menu link saving destination

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#502]
## Problem/Motivation
After adding a menu link, I am taken to the list of menus which is unexpected.

### To Reproduce
1. Navigate to Structure > Menus
2. Click "Edit menu" next to Main navigation
3. Click "Add link"
4. Complete the form and Save
5. View the issue: brought back to /admin/structure/menu

### Expected behavior
After saving a link, I would expect to see the list of links in the menu I added the link to. OR I would expect to see a new add link form.

**Comment by trackleft** [comment]
https://www.drupal.org/project/drupal/issues/2957953
