### ISSUE TITLE
Create module to document Quickstart use

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#509]
## Motivation
Leadership needs to know how many live websites are using Quickstart 2 at any given time.

## Proposed Resolution
Kevin will fix it!

### Describe the solution you'd like
Proposed requirements:
- Separate out "sandbox" sites from live sites
- Have a method for anyone to gather the data? 
- Dashboard (:cringe:)? Possibly in ServiceNow.
- Provide a way to gather domains?

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Administrator

## Additional context
How many sites ever existed is not an accurate representation of how many live sites are currently using Quickstart. It would include any site spun up for a day and deleted.

**Comment by camikazegreen** [comment]
Closed by pull request 704.
