### ISSUE TITLE
DS Layout Plugins do not function with Layout Builder Drag and Drop

### ISSUE THREAD

**Issue by tadean** [az-digital/az_quickstart#51]
## Problem/Motivation
The Layout Plugins provided by display suite do not seem to function properly with Layout Builder Drag and Drop functionality. 

### Describe the bug
When a layout builder section is created from one of the layout plugins provided by display suite, it doesn't seem possible to drag and drop blocks within the section. This is also present in a fresh non-quickstart Drupal site using nothing but layout builder and the latest display suite.

### To Reproduce

1. Create a page
2. Click Layout
3. Click Add Section
4. Choose a section type that uses a DS Layout, eg. **One column layout**
5. Add several blocks to the section
6. Attempt to drag and drop block within the section to reorder them

## Proposed resolution
It seems like this may be caused by missing markup that Layout Builder is expecting. Add potential patch to fix missing markup, or potentially switch to other Layout plugins (#45 ) that do not have the issue (custom plugins, `bootstrap_layouts`, etc)

### Expected behavior
Blocks should be able to be reordered within a section via drag and drop.

##  Screenshots
![image](https://user-images.githubusercontent.com/51835841/76572735-1d617200-6478-11ea-8875-b665ef177176.png)

Note that the DS Layout Plugin is missing the hashed outline that is present from the standard layout plugins. It seems like some markup may be missing.

**Comment by joeparsons** [comment]
Should we create a drupal.org issue for this as well?

**Comment by tadean** [comment]
I think so most likely. I've been doing a bit more research trying to find out more information about what's causing it, and searching through the issue queue to see if it might be a known or related issue already. I'm currently thinking it's a "twig accidentally not printing out needed attributes" issue, but trying to track it down.

It's also possible that DS layout plugins might not really be intended to be used with layout builder, since the two mostly do the same thing. (But it seems like they shouldn't be trimming out layout builder's extra markup anyway).

**Comment by mschmeling14** [comment]
Closed. Work not performed. Decided to go a different direction.
