### ISSUE TITLE
Build new front page carousel

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#512]
Implement as a content type - same as QS1

**Comment by geijutsuka** [comment]
Recommended library: https://kenwheeler.github.io/slick
Contrib module: https://www.drupal.org/project/slick

**Comment by camikazegreen** [comment]
@geijutsuka Would using this library be dependent on Troy's third party library ticket?

**Comment by tadean** [comment]
> @geijutsuka Would using this library be dependent on Troy's third party library ticket?

Looking at the deployment options it seems so I think.

**Comment by geijutsuka** [comment]
Added the dependency between the two issues. 
Definitely needs to load a third party library (module page mentions distros which d/l the libraries—which I assume means our distro would need to do the same). 
...How do the other distributions mentioned on the Slick module page handle it?
*Mentioned distros:*
Lightning - https://www.drupal.org/project/lightning
Open Y - https://www.drupal.org/project/openy
Presto! - https://www.drupal.org/project/presto
Thunder - https://www.drupal.org/project/thunder
Varbase - https://www.drupal.org/project/varbase
Brainstorm profile - https://www.drupal.org/project/brainstorm_profile
Seeds - https://www.drupal.org/project/seeds
