### ISSUE TITLE
Full-width display of paragraph types issue

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#528]
## Problem/Motivation
The full-width display of paragraph types `Text on Media` and `Text with Background` has added left side space and horizontal scroll when used on a page with a block in the left sidebar region.

ALSO happens when content is in the right sidebar region. The full-width content gets shifted to the left.

### To Reproduce
1. Add a page to the menu so it will display a sidebar nav
2. Add a full-width paragraph type
3. Save the page and observe display issue

Example of issue:
![image.png](https://images.zenhubusercontent.com/5eb9d10a2b1f2c51836b60e3/81690ec3-4049-492f-b49c-8b16ecaf0001)

### Expected behavior
I expect the content to remain in the content region while the background spans full-width. Ideally the full width background would appear behind the sidebar nav as necessary.

**Comment by trackleft** [comment]
One possible solution:
Use sidebar classes in conjunction with media queries for breakpoints to set widths via css 
<img width="717" alt="bodyclasses" src="https://user-images.githubusercontent.com/1023167/108928951-57337600-7600-11eb-9e1e-90fb672e1913.png">

**Comment by camikazegreen** [comment]
Closed with https://github.com/az-digital/az_quickstart/pull/898
