### ISSUE TITLE
ES6 Transpiler Architecture

### ISSUE THREAD

**Issue by tadean** [az-digital/az_quickstart#54]
## Motivation
It was noticed in #42 that the existing eslintrc file in use by Drupal core that provides our lint settings is rather geared towards ES6 and transpiled ES5, rather than standard ES5. This lead to the realization that Drupal core's process for how they develop javascript has changed in Drupal 8/9:

- Developers edit and work with `*.es6.js` files
- Development environment uses `yarn` and `babel` to transpile the `es6.js` files to `.js` files, which are what is actually used by the Drupal theme infrastructure
- `.js` files are not intended to be editable by humans
- transpiled `.js` files are a committed part of the codebase; they are not transpiled on the fly during site operation.

More information:
https://www.drupal.org/node/2815083

As documented at https://confluence.arizona.edu/pages/viewpage.action?pageId=105505925 we elected that it would be good to follow this same path, and that we should update our tooling to allow for usage of this process. Going forward, this means we would write our javascript in es6, and allow babel to create the browser-usable versions.

A good first step in that regard would be to update our Lando and DDEV workflows to allow for yarn to be installed and have tooling to run a babel transpile process on our install profile's future `.es6.js` files.

Please see Drupal core's `core/package.json` for necessary dependencies.

### Is your feature request related to a problem? Please describe.
It's currently difficult to write ES5 javascript code that passes the drupal core eslint settings.

### Describe the solution you'd like
Yarn tooling integrated into Lando/DDEV set up with scripts to transpile .es6.js files. It would also be nice if there was "watch" functionality to transpile whenever files change. It's possible that lack of true `inotify` support in VMs may complicate watch functionality - TBD.

### Describe alternatives you've considered
Available alternatives:

- Continue to write ES5 javascript with a custom `eslintrc.json` to avoid problematic eslint sniffs that are difficult to avoid in readable ES5.

## Additional context
This avenue was chosen due to desiring to follow core-friendly workflows, and the knowledge that ES6 will gradually become the browser standard as time goes on.

**Comment by tadean** [comment]
Currently, it seems that the babel tooling used in Drupal core isn't geared towards transpiling contrib modules yet. (discussion [here](https://www.drupal.org/project/drupal/issues/2957390) )

Would it be reasonable to include our own `package.json` that does similar transpilation until such time as core supports contrib folders?

**Comment by mmunro-ltrr** [comment]
It's sad that there was so little progress in getting the tooling available beyond Core in the last year or so: we should certainly do something as a stopgap (& it looked like some of the suggested solutions were a bit more elaborate than just adding an extra file).

**Comment by tadean** [comment]
It seems that a fair amount of the difficulties come from getting the babel environment going with its associated dependencies but running outside of the context of the packages.json root location, which exists in `web/core`. I'd guess there are probably some issues with assumptions that are being made about where `node_modules` are being installed.

It might be possible to mirror the js-related dependencies into an install profile `package.json` and put in a relative path to reuse cores existing `babel-es6-build.js`/`babel-es6-watch.js` files which might sidestep the difficult issue the Core team is trying to solve at the moment.
