### ISSUE TITLE
Create News feeds importer

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#559]
Generally: Match Quickstart 1 (except we probably won't be using feeds)

Requirements:
- Bring in articles from news.arizona.edu (see fields below)
- External articles will appear alongside internal news content type in all associated views
- Users go to article on news.arizona.edu when selecting article from all associated views
- External articles on a site should not appear in site map
- External articles should have canonical URL set to the news.arizona.edu URL
- Site admins/Content admins can set which articles they want to have imported based on tag (and can have multiple tags) and then display news on site based on those tags - This will likely need some sort of UI
- New external articles automatically imported daily
- If article changes on news.arizona.edu (e.g. headline change), change is reflected on the site??
- If article is deleted should be deleted?

Example of feed from news.arizona.edu: https://news.arizona.edu/feed/json/stories/id/312

Fields that get imported to site:

- Title
- Date of Publication
- Photo (plus alt text, title text, crops)
- News tags
- Summary link
- Summary
- Canonical URL
- Short title (not currently using this in QS2)

**Comment by danahertzberg** [comment]
Could use migrate in D9

**Comment by joeparsons** [comment]
D7 module:
https://bitbucket.org/ua_drupal/ua_quickstart/src/7.x-1.x/modules/custom/uaqs_news/uaqs_news_feeds/
