### ISSUE TITLE
Prevent dropdown menu items from scrolling off screen

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#567]
## Motivation
When a nested menu item has a long title and is near the right side of the screen, the menu will get cut off on the right side.

## Screenshot of issue
![image.png](https://images.zenhubusercontent.com/5eb9d10a2b1f2c51836b60e3/d17dbb63-5a96-4504-81f3-691b6e3bbd88)

## QS1 fix
https://bitbucket.org/ua_drupal/ua_quickstart/src/7.x-1.x/themes/custom/ua_zen/js/uaqs_navigation_dropdown_direction.js

**Comment by danahertzberg** [comment]
Other menu bugs
- https://github.com/az-digital/az_quickstart/issues/753
- https://github.com/az-digital/arizona-bootstrap/issues/281

**Comment by camikazegreen** [comment]
Issue moved to [az-digital/arizona-bootstrap #337](https://github.com/az-digital/arizona-bootstrap/issues/337) via [**ZenHub**](https://www.zenhub.com/)
