### ISSUE TITLE
Add title field to Cards paragraph type

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#570]
## Motivation
Allow title to be added before the Cards without the need for a separate Text paragraph type.

## Proposed Resolution
Still need to consider how to implement formatting and style options.

**Comment by joeparsons** [comment]
@Carris-Toupin have you already started working on this?  @djcelaya said he'd be happy to work on this one if not.

**Comment by Carris-Toupin** [comment]
No, David is welcome to it.
