### ISSUE TITLE
Add Content > Blocks tab

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#589]
## Motivation
Currently, you can only view and edit blocks by navigating to Structure > Blocks > Custom block library. It would be nice to have the same experience as QS1 by way of Content > Blocks navigation.

## Solution
Add a new display for Blocks to the admin view displaying the Content page.

**Comment by barrettbaffert** [comment]
Rather than working on this ticket now, should we just wait for it to (potentially) be added to core? See two drupal.org issues referenced in portion of [this blog post](https://evolvingweb.ca/blog/5-things-new-drupal-site-builders-struggle):

> Site builders new to Drupal don’t usually stumble across the Block Types page on their own. In fact, I think a lot of site builders don’t know about block types at all. Probably because "Block Types" is not listed in the in the 2nd level of the administration menu under “Structure”, but instead buried in the third level of the menu. There's [already work underway](https://www.drupal.org/project/drupal/issues/2987964) to make this change.
> 
> Similarly, site builders might never find the “Custom block library” page for creating block content. Depending on how blocks are being used on a particular site, this page might be more logically nested under “Content”. If you like this idea, there's [an issue on Drupal.org](https://www.drupal.org/project/drupal/issues/2862564) to make this update and a discussion about how best to integrate it into Drupal 8 (or 9).

Counterpoint: this blog post was written Dec 19, 2018, and still we wait....

**Comment by trackleft** [comment]
There are patches...

**Comment by barrettbaffert** [comment]
I haven't had luck with the patches, so far. One survived the build without issue, but I didn't notice the expected difference. The other has given me very helpful "Cannot apply patch" errors when I rebuild. More soon, hopefully!
