### ISSUE TITLE
Investigate Security Recommendations for Webforms.

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#595]
## What is the problem that we want to solve?
Webforms are one of the most common areas for security vulnerabilities in Drupal sites. The purpose of this spike is to investigate:
- What is the current state of security concerns for the Drupal 9 version of webform?
- Which types of configuration should be put in to place to mitigate any risks?
- How should we implement adding this configuration to Quickstart?

## Conditions of satisfaction
- [ ] The considered options are documented
- [ ] A recommended next step is documented
- [ ] An estimate of time and effort is provided for the recommendation

**Comment by kevcooper** [comment]
Port some of our old uits_webform_private to ensure file uploads are not publicly accessible.
