### ISSUE TITLE
Figure out mail modules needed for D9

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#60]
## User Story(s)
As a site administrator, I'd like to be able to send mail from my site.

## Conditions of satisfaction
- [ ] The mail module/library we choose supports attachments correctly (including inline attachments)
- [ ] The mail module/library we choose should work with the Rules module

**Comment by jwmoore1** [comment]
@joeparsons @kevcooper Is this completed by #465, the az_mail module?
