### ISSUE TITLE
Fix off-canvas nav scroll issue

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#615]
Update Arizona Header with new search and menu open buttons for mobile once they are finalized. Use the same markup for both.

**Requirements:**

Markup on AZ Barrio should match Arizona Bootstrap (reduce extra markup as much as possible)

- Update main menu template
- Address scrolling issues on menu (should scroll) and background (should not scroll az-digital/az_quickstart#614)

**Comment by akslay** [comment]
Blocked by: https://github.com/az-digital/arizona-bootstrap/issues/213

**Comment by akslay** [comment]
- [ ] Update Arizona Header with new search and menu open buttons for mobile once they are finalized. Use the same markup for both.
- [ ] Markup on AZ Barrio should match Arizona Bootstrap (reduce extra markup as much as possible)
- [ ] Update main menu template
- [ ] Address scrolling issues on menu (should scroll) and background (should not scroll #614)
