### ISSUE TITLE
Determine feasibility of anonymous review workflow with blocks & layout builder

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#62]
## What is the problem that we want to solve?
The anonymous review feature of UA Quickstart (D7) has seen a large increase in usage across many Quickstart sites over the last couple of weeks.  We need to make sure that the way we're implementing flexible pages for Quickstart 2.0 (blocks, layout builder, etc) won't prevent us from being able to support the same functionality going forward.

## Conditions of satisfaction
- [ ] The considered options are documented
- [ ] A recommended next step is documented
- [ ] An estimate of time and effort is provided for the recommendation

**Comment by mschmeling14** [comment]
Closed. Work not performed. Decided to go a different direction.
