### ISSUE TITLE
Give content editors and admins permissions to add/edit flexible blocks

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#627]
Content editors and admins currently do not have permissions to edit or create flexible blocks.

## Conditions of satisfaction
- [ ] Content editors should be able to create flexible blocks
- [ ] Content editors should be able to edit flexible blocks
- [ ] Content editors should be able to embed content blocks via the CK editor
- [ ] Content editors should be able to delete own flexible block
- [ ] Content admins should be able to delete any flexible block
- [ ] Content admins should be able to place flexible blocks into regions

**Comment by danahertzberg** [comment]
Requires contrib module: https://www.drupal.org/project/block_content_permissions
