### ISSUE TITLE
Media embed with enter button issue

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#638]
## Describe the bug
When trying to embed media via the CKEditor. Hitting enter after typing in alt text brings you to an error page.

## Additional context
Per @geijutsuka: There was an error when entering after uploading the media, but appears to be a Media/Core problem? This is all I could find relating to the error:

https://www.drupal.org/forum/general/general-discussion/2020-10-20/the-specified-ajax-callback-is-empty-or-not-callable
https://www.drupal.org/project/drupal/issues/2866330
Error:
Symfony\Component\HttpKernel\Exception\HttpException: The specified #ajax callback is empty or not callable. in Drupal\Core\Form\FormAjaxResponseBuilder->buildResponse() (line 67 of /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Form/FormAjaxResponseBuilder.php).

**Comment by joeparsons** [comment]
I was not able to reproduce this bug on a generic Drupal 9.1.8 installation so I'm thinking there is something Quickstart-specific that is causing this.

These were the steps I followed on a clean Drupal 9.1.8 install (standard profile) to try to reproduce the issue:
- Install media and media_library modules
- Enable "Embed Media" filter and "Insert from Media Library" CKeditor button on Basic HTML text format
- Navigate to "Add Basic Page"
- Click "Insert from Media Library" ckeditor button on body field
- Add new image file
- Type in "Alternative text" field
- Press enter key on keyboard

**Comment by joeparsons** [comment]
Looks like this is a known [Image Widget Crop module bug](https://www.drupal.org/project/image_widget_crop/issues/3117828).  The issue has already been fixed but has not yet been included in a release.  Working on a Quickstart PR now.
