### ISSUE TITLE
Text on Media paragraph type updates

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#656]
**Requirements:**
- [x] #893
- [x]  #1024  
- [x]  #995 Allow bottom style media to be cropped/adjusted 
- [ ] ~#1039~
- [x] #1041
- [x] #1044
- [x] #1028  
**Additional context:**
Will need to ensure option updates are applied to both image and video backgrounds

**Comment by danahertzberg** [comment]
Related to #693

**Comment by danahertzberg** [comment]
## For ability to adjust padding requirement

### Text on Media: Column style
- Apply the following options to the `<div class="column content light">`
  - Zero | py-0
  - 1 (0.25rem | ~4px) | py-1
  - 2 (0.5rem | ~8px) | py-2
  - 3 (1.0rem | ~16px) | py-3
  - 4 (1.5rem | ~24px) | py-4
  - 5 (3.0rem | ~48px) | py-5 (default selection)
  - 6 (4.0rem | ~64px) | py-6
  - 7 (5.0rem | ~80px) | py-7
  - 8 (6.0rem | ~96px) | py-8
  - 9 (7.0rem | ~112px) | py-9
  - 10 (8.0rem | ~128px) | py-10

This padding is what should change.
![image.png](https://images.zenhubusercontent.com/5eb9d10a2b1f2c51836b60e3/f564c22e-03b8-4f9a-baa0-d6e528d6e81c)

### Text on Media: Box style
- Apply the following options to the `<div class="content box light">`
  - Zero | my-0
  - 1 (0.25rem | ~4px) | my-1
  - 2 (0.5rem | ~8px) | my-2
  - 3 (1.0rem | ~16px) | my-3
  - 4 (1.5rem | ~24px) | my-4
  - 5 (3.0rem | ~48px) | my-5 (default selection)
  - 6 (4.0rem | ~64px) | my-6
  - 7 (5.0rem | ~80px) | my-7
  - 8 (6.0rem | ~96px) | my-8
  - 9 (7.0rem | ~112px) | my-9
  - 10 (8.0rem | ~128px) | my-10

This margin is what should change.
![image.png](https://images.zenhubusercontent.com/5eb9d10a2b1f2c51836b60e3/41f2f893-2858-4e3f-84ae-3c842a41daf4)

**Comment by camikazegreen** [comment]
We need to have a size 15 option as well to meet the use case of just having a heading in the content box. 
This is very common.

**Comment by joeparsons** [comment]
It should be possible to copy the changes made in #793 with only minor modifications for this.
