### ISSUE TITLE
User migration

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#662]
## Motivation
Migrating users from Quickstart 1.0 sites to Quickstart 2.0 sites will be a critical part of migration. 

### Is your feature request related to a problem? Please describe.
Drupal 9's core migrate functionality already migrates users, but there are some limitations for our use case:

- All Quickstart sites use CAS as the login solution instead of the standard Drupal logins. This is not handled successfully by Core Migrate.

- Quickstart 1.0 did not come with standard Roles and Permissions, but Quickstart 2.0 does. For most use cases, we **do not** want to carry over the roles and permissions from QS1 sites, and instead would prefer to allow mapping during the migration. Note: for sites that have intentionally added more roles, we want to allow them to be migrated.

### Describe the solution you'd like
CAS: 
The users' netids should be listed as the cas username, and the "Allow user to log in via CAS" checkbox should be checked.
<img width="1220" alt="Screen Shot 2021-04-09 at 3 42 50 PM" src="https://user-images.githubusercontent.com/1509771/114247606-56ee0080-994a-11eb-8230-b82323f81c91.png">

Roles & Permissions:
This is a harder question and is probably worth some group discussion.

- We can map any users with only "Authenticated User" to the same role in QS2, but there aren't many of these users.
- Any higher permissioned users could be migrated to the "Content Editor" role by the principal of least privilege, and then expect any higher roles to be explicitly granted on a case by case basis.

### Describe alternatives you've considered
If there is an easy way to do this, we could provide an interactive component (either via UI or drush) that would:
- display the roles in the QS1 site
- allow you to map those roles to QS2 roles (Note: Quickstart 2 roles are additive, so it is expected that someone with the Content Administer role will also have the Content Editor role or they won't be able to do much)

Note: There are also many cases in QS1, where site builders never created any roles beyond the default and just assigned the admin role to all users. _This should not be carried over to new sites_.

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Anonymous user
- Authenticated user
- Content editor
- Content administrator
- Administrator

**Comment by danahertzberg** [comment]
- D7 Administrators will be migrated to D9 Administrator role
- D7 Content administrator and Content editors will be migrated to D9 Authenticated user role
- D7 blocked users will not be migrated
- D7 blocked user content will be migrated to Anonymous author

**Comment by joeparsons** [comment]
We'll need this add this patch for the CAS module:
https://www.drupal.org/project/cas/issues/3038662
