### ISSUE TITLE
Investigate Files and Media migrations

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#663]
## What is the problem that we want to solve?
We need to verify that we are using Media consistently between each of our content types in Quickstart 1 and 2. If we are not, we might need to convert some of our files from Quickstart 1 to media entities in Quickstart 2 during our migrations.

## Conditions of satisfaction
- [ ] The method of adding images to News, Event and Person content types is documented for both Quickstart 1 and 2.
- [ ] A recommended next step is documented
- [ ] An estimate of time and effort is provided for the recommendation

**Comment by joeparsons** [comment]
## File/Media-related modules used in D7 Quickstart
Module name | Version | Patches | Enabled by Default | Needed in D8+ | Existing migration plugins available
------------- | -------- | -------- | ------------------- | --------------- | ----------------------------------- 
[editor](https://www.drupal.org/project/editor) | 7.x-1.0-alpha7 | Yes | editor, editor_ckeditor | No | 
[entity_embed](https://www.drupal.org/project/entity_embed) | 7.x-**3.x**-**dev** | No | entity_embed | Yes | **No**
[file_entity](https://www.drupal.org/project/file_entity) | 7.x-2.30 | Yes | file_entity | No | Yes
[file_entity_inline](https://www.drupal.org/project/file_entity_inline) | 7.x-1.0-rc2 | No | file_entity_inline | 
[media](https://www.drupal.org/project/media) | 7.x-2.26 | No | media | No | Yes
[media_oembed](https://www.drupal.org/project/media_oembed) | 7.x-2.8 | Yes | media_oembed | No | Yes
[plupload](https://www.drupal.org/project/plupload) | 7.x-1.7 | Yes | plupload | Should probably use DropzoneJS instead | N/A

**Comment by camikazegreen** [comment]
## Content Type Image and File use
Content Type | Label | Machine Name | Field Type | Field Widget 
------------- | ------ | --------------- | ---------- | --------------- 
Carousel Item | Slide Image | field_uaqs_photo | Image | Image
Event | Event Photos | field_uaqs_photos | Image | Image
Event | Attachments | field_uaqs_attachments | File | File
Flexible Page | Photo | field_uaqs_photo | Image | Media browser
News | Photo | field_uaqs_photo | Image | Media browser
News | Attachments | field_uaqs_attachments | File | File
News | News Article Photos | field_uaqs_photos | Image | Image
Person | Photo | field_uaqs_photo | Image | Media browser
Person | CV / Documents | field_uaqs_cv_documents | File | File
Deprecated | ----------- | -------------------------- | --- | ----
Publication | Publication Photos | field_uaqs_photos | Image | Image
Unit | Media | field_uaqs_photo | Image | Media browser

**Comment by camikazegreen** [comment]
## Paragraph Type Image and File use
Paragraph Type | Label | Machine Name | Field Type | Field Widget 
---------------- | ------ | --------------- | ---------- | --------------- 
Image with caption | Photo | field_uaqs_photo | Image | Media browser
Marquee | Media | field_uaqs_photo | Image | Media browser
File attachment | UAQS Download File | field_uaqs_download_file | File | File | edit | delete
File attachment | UAQS Download Preview Image | field_uaqs_download_preview | Image | Image
Full width media row | Media | field_uaqs_photo | Image | Media browser
Photo gallery | Gallery Photos | field_uaqs_photos | Image | Media browser

## Field Collections Image and File use
Field Collection | Label | Machine Name | Field Type | Field Widget 
---------------- | ------ | --------------- | ---------- | --------------- 
field_uaqs_cards | Photo | field_uaqs_photo | Image | Media browser
field_uaqs_carousel | Photo | field_uaqs_photo | Image | Media browser

**Comment by camikazegreen** [comment]
Is it safe to say that if the field widget is:
File == File
Image == File Entity
Media browser == Media Entity
