### ISSUE TITLE
Upgrade to drupal version 9.2

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#679]
## Conditions of satisfaction
- [ ] Drupal version should be 9.2
- [ ] All tests should pass.
- [ ] All dependencies should resolve.

**Comment by joeparsons** [comment]
Ideally we would also want to synchronize the Javascript tooling (package.json file, configuration files, and scripts) that we copied from Drupal core with the upstream versions as part of this (we use only a subset):

https://git.drupalcode.org/project/drupal/-/blob/9.2.x/core/package.json
https://git.drupalcode.org/project/drupal/-/blob/9.2.x/core/.eslintignore
https://git.drupalcode.org/project/drupal/-/blob/9.2.x/core/.eslintrc.json
https://git.drupalcode.org/project/drupal/-/tree/9.2.x/core/scripts/js
