### ISSUE TITLE
Fix block regions

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#689]
**Do not disclose security vulnerabilities here, please email us instead: 
az-digital-security@list.arizona.edu**

## Conditions of satisfaction
Should match UAQS regions

- [ ] Header utilities region should span section width
- [x] Header 2 region should span section width
- [ ] Navigation bar region should span content width
- [x] Add Help region
- [x] Move Highlighted region below Featured content
- [x] Content top region should span content width
- [x] Content column stacked regions should span section widths
- [x] Content bottom region should span content width
- [x] Sub footer region should span content width
- [x] Add Page bottom region
- [x] All regions should align on left and right sides (padding issue)

### UAQS
![screencapture-uasites-arizona-edu-admin-structure-block-demo-ua-zen-2021-04-27-13_46_10.png](https://images.zenhubusercontent.com/5eb9d10a2b1f2c51836b60e3/62e849d0-9021-43da-a1c4-9e5a1e958d9e)

### AZQS
![screencapture-live-azs-it-pantheonsite-io-admin-structure-block-demo-az-barrio-2021-04-27-13_46_05.png](https://images.zenhubusercontent.com/5eb9d10a2b1f2c51836b60e3/f1554e1d-ea9a-40a2-a13c-086ec35f1753)

**Comment by danahertzberg** [comment]
To span content width, additional div with class="col" inside the row div is needed

**Comment by danahertzberg** [comment]
Maybe this is just a card issue compared to a region issue. Some content respects the col-# classes (like footer menu blocks) and other content does not (like cards with certain settings).

This screenshot is of a flexible block placed in the footer sub region. The flexible block has a cards paragraph added to it with these settings:

- Borderless
- Background: Transparent
- Cards per row: 3
- Cards added: 2

![Screen Shot 2021-05-12 at 2.38.00 PM.png](https://images.zenhubusercontent.com/5eb9d10a2b1f2c51836b60e3/75c7510f-3ae5-4539-8c17-2f535ab8bff7)

**Comment by danahertzberg** [comment]
Example site (see footer) http://live-azs-it.pantheonsite.io/

**Comment by trackleft** [comment]
@danahertzberg header utilities is used for those menu buttons for search and triggering the menu, so I might need to look harder at that region.

**Comment by danahertzberg** [comment]
@trackleft Good call. Thank you for looking into that further! 🙏🏻
