### ISSUE TITLE
Add padding options to Text with Background paragraph type

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#691]
## Motivation:
I want the row to be extra fat or extra skinny around my text.

## Requirements:
- Add ability to adjust padding around text (use more content editor friendly language)

- Apply the following options to the div surrounding the container `<div data-quickedit-entity-id="paragraph/1" class="background-wrapper bg-azurite bg-triangles-centered full-width-background mb-4 paragraph paragraph--type--az-text-background paragraph--view-mode--default py-5 text-with-background" data-quickedit-entity-instance-id="0">`

- Space around content
  - Zero | py-0
  - 1 (0.25rem | ~4px) | py-1
  - 2 (0.5rem | ~8px) | py-2
  - 3 (1.0rem | ~16px) | py-3
  - 4 (1.5rem | ~24px) | py-4
  - 5 (3.0rem | ~48px) | py-5 (default selection)
  - 6 (4.0rem | ~64px) | py-6
  - 7 (5.0rem | ~80px) | py-7
  - 8 (6.0rem | ~96px) | py-8
  - 9 (7.0rem | ~112px) | py-9
  - 10 (8.0rem | ~128px) | py-10

Should adjust this padding:
![image](https://user-images.githubusercontent.com/59745109/119050028-28fed180-b976-11eb-9abb-e23763e0447e.png)

**Comment by joeparsons** [comment]
@danahertzberg Do we want an empty/"None" option that doesn't add any class?

**Comment by danahertzberg** [comment]
@joeparsons I think the Zero option achieves that same goal. 

Once the default is set here, we will also be able to remove the `padding: 3rem 0;` CSS from the `.background-wrapper` class.

**Comment by joeparsons** [comment]
@danahertzberg Should the `padding: 3rem 0;` _not_ be removed from `.background-wrapper` as part of this PR for this issue?

**Comment by danahertzberg** [comment]
> @danahertzberg Should the `padding: 3rem 0;` _not_ be removed from `.text-with-background` as part of the PR for this issue?

@joeparsons I guess I didn't know this was set for 2 different classes. Taking both designations out and replacing it with the padding class produces the desired result. 

Is `.text-with-background` or `.background-wrapper` referenced from anywhere else besides the Text with Background paragraph type?

[Arizona Bootstrap documentation](https://digital.arizona.edu/arizona-bootstrap/docs/2.0/components/background-wrappers/) only references the `.background-wrapper` class. Now I'm re-thinking if we should just not mess with the CSS and only focus on adding the new functionality.
