### ISSUE TITLE
Maintain version reference in az_quickstart.info.yml

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#692]
## Problem/Motivation
The `version` [property of az_quickstart.info.yml](https://github.com/az-digital/az_quickstart/blob/main/az_quickstart.info.yml#L4) is currently set to `0.0.1`.

The value is displayed in the Drupal install UI and in the site status report and is confusing to developers and site builders.

## Proposed resolution
We should update this value and also add steps to our release workflow(s) to update this value automatically each time we create new releases.

##  Screenshots
![Screen Shot 2021-04-27 at 4 02 16 PM](https://user-images.githubusercontent.com/471936/116323015-0d871900-a772-11eb-963a-75a52582dfd4.png)
![Screen Shot 2021-04-27 at 3 54 56 PM](https://user-images.githubusercontent.com/471936/116323013-0c55ec00-a772-11eb-84ee-0610e96e0b5b.png)

## Additional context
We used to do something similar in D7 Quickstart (see our old [release.sh script](https://bitbucket.org/ua_drupal/ua_quickstart/src/b6f173f04f28c85ccbd32d08b9611c5b2af50986/release.sh#lines-102:118)).

**Comment by danahertzberg** [comment]
GA release: Remove static `0.0.1` version
Future release: Add functionality to display current version of QS
