### ISSUE TITLE
Figure out ChromeDriver dependencies for tooling stack

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#72]
## What is the problem that we want to solve?
We need to be able to run D8 Javascript Functional Tests both locally and on our CI tools.

We should look into what Drupal.org is doing for this and also at what tools are already installed/available on ProboCI's docker images.

UC Davis' SiteFarm project has Functional Javascript tests and they use ProboCI.

## Conditions of satisfaction
- [ ] Test dependencies are documented
- [ ] Lando/ddev support is considered

**Comment by camikazegreen** [comment]
Troy: That issue has not been resolved yet. The views PR linked it because a unit test couldn't be written for the Views paragraph because it would necessitate being a javascript test and we didn't have chromedriver yet in our tool stack.

**Comment by joeparsons** [comment]
Drupal.org Documentation Re: Running PHPUnit Javascript tests:
https://www.drupal.org/docs/automated-testing/phpunit-in-drupal/running-phpunit-javascript-tests

Docker Image used by Drupal.org test runners:
https://hub.docker.com/r/drupalci/webdriver-chromedriver/
