### ISSUE TITLE
Configure how taxonomy term pages should display

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#735]
Currently if a user clicks on the a taxonomy term on an event or person item they go to a page that lists the title of the node, a read more link, and an rss icon/link

Event:
![image](https://user-images.githubusercontent.com/10873398/118369439-38d27c00-b558-11eb-9913-bd7f10462fe4.png)

Person:
![image](https://user-images.githubusercontent.com/10873398/118369604-d2019280-b558-11eb-9708-12a77c8a6851.png)

Not sure what the ideal content and styling should be on these (perhaps something similar to the event calendar and person row). QS 1 did show more information but without much styling.

Note: this may also apply to news and page taxonomy pages, but right now those content types do no display a taxonomy term on the node.

**Comment by bberndt-uaz** [comment]
I think we could take the following approach for this issue:

- Add a new display to the view for each of the four main Quickstart content types (the views `az_events`, `az_news`, `az_page_by_category`, and `az_person`). These new view displays would allow control over the appearance of taxonomy term pages for the vocabulary associated with each content type (such as the News Tags vocabulary for the AZ News content type).
- Establish that the current `taxonomy_term` view is intended for all other taxonomy vocabularies. This view should be left as is unless we want to make any visual changes at this time.

Questions regarding requirements for the new view displays:

1. Should the new view displays mimic the existing views we have for each content type? For example, should the view display for Event Categories terms be essentially the same as the /calendar view for events?
2. Should the new view displays have a path reflecting the vocabulary name (/event-categories/<term>) or should the path match with the nodes (/events/<term>) or main view (/calendar) for the content type?
3. Is it correct that the breadcrumbs for these view displays should include a link to the main view for the content type (such as /calendar)?

In my testing, I found that the new view displays could be created with a unique path, such as /event-categories, which would not interfere with existing views. To have the main view linked in the breadcrumbs, a redirect (not an alias) could be created from that path (/event-categories) to the main view (/calendar). Some additional customization may be needed to have the breadcrumbs appear correctly. I believe the title of each view display would need to be set using a hook_views_post_render() function in the .module file for each module.

**Comment by joeparsons** [comment]
Closing this issue because work has already started on #2383 which basically duplicates this one.
