### ISSUE TITLE
Improve UX for creating/editing grids

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#736]
When creating content on the new admissions site, content editors had lots of trouble when it came to using grids

-Difficult to see which column they are editing within the ckeditor without viewing source code (visual of grid outlines only appears on hover and then the columns are stacked not side by side)
-Need default settings for the column width (perhaps auto or equal width?). Numerous editors did not edit the default selection of "None" and then didn't understand why the columns did not appear side by side
-Make column width settings appear with in the dialog box (this is already addressed in #389)
-Possibly reduce the amount of choices or add help text - Content editors did not understand the different options for small, medium, large screen sizes or how best to select those options; It would be great if defaults were similar to QS 1 and then more custom options were part of something similar to advanced settings

![image](https://user-images.githubusercontent.com/10873398/118370697-c06eb980-b55d-11eb-9ea1-d941f7c0bab3.png)

## Conditions of satisfaction
- [ ] Content editors can easily add a grid (similar to QS1) with default settings
- [ ] Content editors easily know which part of the grid they are editing content for
- [ ] Grid displays as expected on different screen sizes (with default settings)
- [ ] Grid options all appear on screen

**Comment by danahertzberg** [comment]
Maybe we need to consider using a different module?

Current modules: 
- https://www.drupal.org/project/bootstrap_utilities
- https://www.drupal.org/project/ckeditor_bs_grid

Other options out there:
- https://www.drupal.org/project/ckeditor_bootstrap_grid
- https://www.drupal.org/project/ckeditor_bs_grid

**Comment by danahertzberg** [comment]
Shoshana and Dana to further define defaults and conditions of satisfaction
