### ISSUE TITLE
Fix/clean up media display modes for images

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#743]
Content editors currently have several options when they edit media for their display sizes:
-default
-background
-card image
-large
-medium (360px)
-natural size
-square
-thumbnail (100x100)
-full content
-media library
-token

Many of these do not seem to affect the image size at all (square, token, etc.) and some labels are confusing or redundant (what is the difference between default and natural size?

![image](https://user-images.githubusercontent.com/10873398/118379018-69340d80-b58c-11eb-8ce1-be0b6116a631.png)

## Conditions of satisfaction
- [ ] Options should either match QS1 (small, medium, large used in QS1) or be an improvement that makes sense to content editors 
- [ ] All options should produce the correct image display
- [ ] Unneeded options should be removed

**Comment by danahertzberg** [comment]
Update display titles of media selections

- Small (33%width)
- Medium (66% width)
- Large (100% width)
- Square
- Card
- Default/natural size?
