### ISSUE TITLE
Content butts up against footer

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#746]
## Problem/Motivation
For our news, events, and person content types (and possibly some paragraphs on page) the content area butts up agains the footer with no padding.

##  Screenshots
![image](https://user-images.githubusercontent.com/10873398/118379602-620efe80-b590-11eb-99a3-a65130c48d02.png)

**Comment by danahertzberg** [comment]
Agreed, we should fix for Person/News/Events. I believe we discussed changing the default bottom margin on paragraph types to zero to reduce gaps between Text with Background paragraphs. But I could be mistaken.

**Comment by danahertzberg** [comment]
Best path forward would be to add a margin bottom class on the row class around all the content for News, Event, and Person content types

**Comment by cpoff** [comment]
Finally located the person-full twig and got it all deployed. But now it's throwing packagist errors I'll need to troubleshoot.

**Comment by cpoff** [comment]
Got my Personal Access Token renewed and errors went away. All tests passed in the PR.
