### ISSUE TITLE
Add link field to Text on Media

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#747]
## Motivation
Both the full width media row and marquee in QS1 had a link field as part of the paragraph. This is useful, easy way for content editors to add a call to action to this type of content.

### Is your feature request related to a problem? Please describe.
Currently in QS2 there no link field. If content editors want to add a CTA button they can in the body and apply stylings but this will likely be more difficult and result inconsistent styles being applied.

## Proposed Resolution
Create an optional link field with button styling options similar to QS1

### Roles and Permissions considerations
- Content editor and content administrators will be able to easily add call to actions to this type of content with default styles applied.

**Comment by danahertzberg** [comment]
I believe this was discussed and we opted to put all links/buttons in the body of the Text on Media because there wasn't a need to have the entire area be clickable. So the link field would only be for the purposes of creating a button which is already possible in the body (reducing # of fields).

**Comment by joeparsons** [comment]
Sounds like we don't really want to do this.  Issue could be re-opened if needed.
