### ISSUE TITLE
Embedded entity migration

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#756]

**Comment by zsaenz** [comment]
QS1 uses FID, while QS2 uses the UUID, which is not in d7. Here's what I found:

1. FID after migration differs, so we need to get the new FID after migration.
2. Using a table like file_managed, we get the new UUID for the media item. (Do we need to match the MID with the FID in QS2, or can we get that on its own?)
3. Then, perform these three replacements in a text field:
    - In the embed source, replace <drupal-entity> with <drupal-media>
    - Replace data-entity-type="file" with data-entity-type="media"
    - Replace the empty data-entity-uuid-"" with the newly generated matching UUID from migration.

Doing this manually in the editor (by finding the old and new fid/mid/uuids in the database) I was able to recreate a missing entity embed. These three text replaces appears to be the bare minimum for migrating an image entity.
