### ISSUE TITLE
Update CKEditor to use site's version of Arizona Bootstrap

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#760]
Follow up ticket to this PR: https://github.com/az-digital/az_quickstart/pull/754

**Comment by trackleft** [comment]
See if we can use the hook here: https://github.com/az-digital/az_quickstart/pull/757

Try to see if a library discovery service can find existing arizona-bootstrap library.

**Comment by trackleft** [comment]
Irrelevant with CKEditor5
