### ISSUE TITLE
Text with Background content size

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#765]
When a full-width Text with Background paragraph type is used on a page with sidebar content, the content of the paragraph type should align with the content body region.
![image.png](https://images.zenhubusercontent.com/5eb9d10a2b1f2c51836b60e3/e957e7d3-88d8-45c2-b583-d4df0bf701fb)

**Comment by joeparsons** [comment]
Is this a different issue than https://github.com/az-digital/az_quickstart/issues/528?

**Comment by camikazegreen** [comment]
@danahertzberg After looking this over a bit more, I think that the content is appropriately positioned to be full-width. We should leave it in the hands of the site owners to ensure that they don't put any full-width content at the top of the page where it would conflict with anything that they have in their sidebars.

**Comment by danahertzberg** [comment]
> @danahertzberg Is this a different issue than #528?

@joeparsons It appears these issues have the same cause (sidebar existence) but the bug to fix is essentially different. This ticket is to change the width of the content, #528 is to fix the background alignment. Maybe they could be addressed together?

**Comment by danahertzberg** [comment]
> @danahertzberg After looking this over a bit more, I think that the content is appropriately positioned to be full-width. We should leave it in the hands of the site owners to ensure that they don't put any full-width content at the top of the page where it would conflict with anything that they have in their sidebars.

@camikazegreen This would be hard to rely on content editors to account for all screen sizes. There may also be reasonable instances where the sidebar and a full width element at the top of the page are needed. I would be fine re-labeling this to low priority but think it should still be fixed.
