### ISSUE TITLE
Default user roles & permissions

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#77]
## User Story(s)

As a Quickstart site administrator, I'd like to have default roles with sensible permissions already configured when I create a new Quickstart site.

As a site administrator, I would like to be able to change permissions associated with roles  without worrying about losing my changes on code updates.

As a Quickstart developer I would like to be able to add new features and assign roles and permissions for new installations of Quickstart, as well as provide defaults for when said feature is enabled.

## Conditions of satisfaction
- [x] Default roles should be provided
- [x] Default permissions should be provided
- [x] Default permissions are override-able after installation.
- [x] Default permissions for modules that are yet to be enabled will be set once enabled.
- [ ] New features can be added with default permissions.
- [x] Additional roles can be added other than the defaults after installation.

## Out of scope, but related (Could be a spike).
- How to apply upstream changes to permissions if default permissions **are** overridden.
- How to apply upstream changes to permissions if default permissions **are not** overridden.

## User focused documentation will be needed following any decisions made.

**Comment by joeparsons** [comment]
Existing Drupal.org issue for adding a content editor to core:
https://www.drupal.org/project/ideas/issues/2703367

**Comment by joshuasosa** [comment]
Some resources:
- [Editor role diff between patches](https://www.diffchecker.com/DImi0VWS)
- [Umami Author role](https://git.drupalcode.org/project/drupal/-/blob/8.8.x/core/profiles/demo_umami/config/install/user.role.author.yml)
- [Umami Editor role](https://git.drupalcode.org/project/drupal/-/blob/8.8.x/core/profiles/demo_umami/config/install/user.role.editor.yml)
- [Umami Author and Editor role diff](https://www.diffchecker.com/rQoW2Wya)

Useful role/access-related modules:
- [Role Delegation](https://www.drupal.org/project/role_delegation)
- [Content Access](https://www.drupal.org/project/content_access)
- [Access Control Lists](https://www.drupal.org/project/acl)

**Comment by joeparsons** [comment]
Some open questions / decisions related to roles:
- Should our `az_content_admin` role contain all of the permissions of `az_content_editor` or would it be better to maintain only admin-specific permissions in that role?
  - Having only the permissions unique to `az_content_admin` configured in its role would be easier to maintain
  - We could provide documentation / training for users to grant _both_ roles as needed
- Are we OK with all of the roles/permissions config living at the install profile level?
  - One thought that occurred to me is that it might we may want to create an `az_admin` module similar to the `uaqs_admin` module we have for D7 that provides administration features/enhancements and it _might_ make sense to package the roles/permissions there instead of with the profile.
  - Keeping the roles configured at the install profile level might be necessary since each role (and its associated permissions) is represented by one configuration entity/file.
