### ISSUE TITLE
Create text logo option

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#771]
Match QS1 settings

**Comment by joeparsons** [comment]
There was a fairly significant change to Drupal core starting with Drupal 8 related to the site branding elements:
[Branding block used in place of page template branding variables (site name, slogan, site logo)](https://www.drupal.org/node/2544012)

We may be able to use [hook_block_build_BASE_BLOCK_ID_alter()](https://api.drupal.org/api/drupal/core%21modules%21block%21block.api.php/function/hook_block_build_BASE_BLOCK_ID_alter/9.2.x) or [hook_block_view_BASE_BLOCK_ID_alter()](https://api.drupal.org/api/drupal/core%21modules%21block%21block.api.php/function/hook_block_view_BASE_BLOCK_ID_alter/9.2.x) to customize the display of the system branding block to suit our needs but doing so would probably require implementing a trusted callback (see https://www.drupal.org/node/2966725).
