### ISSUE TITLE
Migrate Full Width Background Wrapper paragraph type

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#782]
See migration mapping doc for details: https://docs.google.com/spreadsheets/d/134UMiYtE8f1YAKYgSukL2JxFzDJF6-TgCAvYFC-vxqQ/edit#gid=0

**Comment by camikazegreen** [comment]
@danahertzberg What should we do about migrating deprecated background wrapper patterns?

**Comment by danahertzberg** [comment]
Not migrate them. Just have no background pattern IMO.
