### ISSUE TITLE
Update duration settings with Event migration

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#821]
## Motivation
The Smart Date field's duration is null in the database and appears as "1 hour" to the content editor since that is the default setting. 
- We should consider calculating the duration to have this match the start/end dates that are migrated.
- Or consider a new default setting (Custom?)

**Comment by trackleft** [comment]
https://git.drupalcode.org/project/smart_date/-/blob/3.4.x/src/Commands/SmartDateDrushCommands.php
