### ISSUE TITLE
Search Engine Optimization

### ISSUE THREAD

**Issue by barrettbaffert** [az-digital/az_quickstart#83]
Determine if part of MVP and where in priority

Add meta tag configuration (3)
Sitemap (3) 
  We'll have to add/remove based on published status
Redirects (3)
  Make sure settings are the same on existing QS
  Migrate redirects?
Pathauto (2 if not already configured)
  Copy over alias patterns from D7

Great information from a BADCamp sessions:
Google Tag Manager: https://2020.badcamp.org/session/advanced-google-analytics-and-other-integrations-gtm-and-datalayer
Metatags: https://2020.badcamp.org/session/implementing-top-notch-search-and-social-media-meta-tag-strategy

**Comment by barrettbaffert** [comment]
Here's a starting point for contrib modules that are used in d7/uaqs. Each row could probably translate to an individual issue/pull request. I suggest "must haves" for MVP, and should/could for future versions of az quickstart

https://docs.google.com/spreadsheets/d/1u-cM2g-hRUlrgCEeiTRfCQJPLHD45iAdPHmguwpD-uI/edit?usp=sharing

**Comment by camikazegreen** [comment]
These modules should be added for MVP 1:
xmlsitemap
redirect
globalredirect
metatag
pathauto
