### ISSUE TITLE
Add Photo gallery paragraph item to News content type

### ISSUE THREAD

**Issue by sanjanans** [az-digital/az_quickstart#842]
## Motivation
This request has been made by couple of clients from multiple units for this feature to be added in news. For example, if there is a news related to commencement, it would be wonderful to have the photos added in the news article as a gallery.

### Is your feature request related to a problem? Please describe.
n/a

### Describe the solution you'd like
I would like to be able to use the photo gallery paragraph item on News content type.

### Describe alternatives you've considered
Customized one of the sites.

### Roles and Permissions considerations
The following roles should have access to this feature:
- Content editor
- Content administrator
- Administrator

**Comment by smayden** [comment]
This is a very easy configuration change. Would we want to add any other paragraph types? (originally we thought we would not want to allow all).

Options right now: 
![image](https://user-images.githubusercontent.com/10873398/122082668-0b762980-cdb5-11eb-914c-1c1cdd2b0e25.png)

**Comment by sanjanans** [comment]
Thanks, Shoshana. For now, adding photo gallery option would be most helpful. I'm thinking what could be the use cases for allowing the option to add views?

**Comment by camikazegreen** [comment]
I can only think of use cases for Photo Gallery at the moment. I'd be happy to revisit adding others later if someone has a need for it.
