### ISSUE TITLE
View unpublished content by other authors

### ISSUE THREAD

**Issue by geijutsuka** [az-digital/az_quickstart#844]
## Problem/Motivation
At the moment, the only way to allow users access to all unpublished content in Drupal (without using a contributed module), is to enable the permission "Bypass content access control". This permission must be used with extreme caution as it has far more consequences than just allowing access to unpublished content. Allowing this permission is not a feasible option.

### Describe the bug
Users without the "Bypass content access control" permission can create unpublished content but other users (except those with the permission) cannot view the node(s) in the content overview page nor the node page itself—they get an access denied. This becomes a problem when more than one user needs to work on unpublished content.

### To Reproduce
Get two users without "Bypass content access control" as a permission
1. Go to '/node/add/page'
2. Create a page and make sure it is unpublished
3. Save the page
4. Have the other user without the permission try to find the page in content overview or go directly to the node page to try to access
5. Result: node will not show for them in the content overview page and they will get an access denied if trying to view directly.

## Proposed resolution
This is a problem with Drupal core, but there may be a contributed module which will help close the gap such as https://www.drupal.org/project/view_unpublished

### Expected behavior
Editors on a site should be able to collaborate on unpublished nodes.

## Additional context
- https://www.drupal.org/docs/7/managing-users/viewing-unpublished-content#s-drupal-7 (says D7, but still a problem)

**Comment by smayden** [comment]
Tested this on a Probo site and verified that if I create unpublished content as a "Content Admin" and then log in as a "Content Editor" I know longer can see the unpublished content.

**Comment by akslay** [comment]
@danahertzberg Should we include this in the GA release since it does impact a site editor's ability to edit content on the site?

**Comment by danahertzberg** [comment]
@akslay Looks like it's already in GA and I agree :)

**Comment by akslay** [comment]
Update as per 2021/07/02 PR review:
We will use "Content Moderation" from core instead. View Unpublished changes the permissions to a per node basis (on the back end, not in the Permissions UI), whereas Content Moderation keeps permissions on a per node type basis. Even if you enable Content Moderation, it won't add a review workflow unless you manually enable it for specific content types.

To Do:
- [ ] Make a new branch (same issue)
- [ ] Enable "Content Moderation" in the install profile

**Comment by trackleft** [comment]
Updated drupal.org here https://www.drupal.org/docs/7/managing-users/viewing-unpublished-content#s-drupal-9
