### ISSUE TITLE
Extra spacing above body content

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#852]
## Motivation
I want my content with colored or media background to touch the main menu if it is the first element on the page.

## Example
![image.png](https://images.zenhubusercontent.com/5eb9d10a2b1f2c51836b60e3/83fcda89-40be-4305-807a-31c94f48230d)

**Comment by danahertzberg** [comment]
Potential issue is `node__content` class adding margin-top

**Comment by mmunro-ltrr** [comment]
PR #921 re-introduced this bug.
