### ISSUE TITLE
Release Plan

### ISSUE THREAD

**Issue by barrettbaffert** [az-digital/az_quickstart#86]
Define ongoing plan for releases.

How many minor releases are we going to support at one time, and for how long?

What is our branch naming strategy?

How are Quickstart, Barrio and Bootstrap releases tied together?

Where do we publish this information?

**Comment by camikazegreen** [comment]
First draft of release policy doc: https://docs.google.com/document/d/1v5zcgPyrTCV7J6CbzQt8er8G1XExLoMarmBIg42FxKU/edit#heading=h.6bc1i9lfifes

**Comment by joeparsons** [comment]
See https://github.com/az-digital/az_quickstart/blob/main/RELEASES.md
