### ISSUE TITLE
Add optional Title field to Card Decks

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#883]
## Motivation
I often want to add a title to my card decks to give an overview of what is in the cards themselves.

### Is your feature request related to a problem? Please describe.
 I currently have to add a Text Area just for adding this title. This makes the page heavier and the editing experience more cumbersome

### Describe the solution you'd like
I would like there to be an optional Title field at the top of the Cards paragraph item. 

### Roles and Permissions considerations
The same roles and permissions that are required to add/edit cards

**Comment by danahertzberg** [comment]
Duplicate of #570
