### ISSUE TITLE
Person content type

### ISSUE THREAD

**Issue by barrettbaffert** [az-digital/az_quickstart#93]
Maintain current functionality... or use the User as the Person in the future.

**Comment by danahertzberg** [comment]
Duplicate of https://app.zenhub.com/workspaces/quickstart-20-5e8f25351c5b8596956ebb92/issues/az-digital/az_quickstart/298

**Comment by trackleft** [comment]
It was determined that using the User entity type as content would be less ideal than adding a permission that allows authenticated users to edit their own content.

Related to: #3553
