### ISSUE TITLE
Anonymous visitors can create accounts (w/ admin approval)

### ISSUE THREAD

**Issue by geijutsuka** [az-digital/az_quickstart#932]
## Problem/Motivation
At the moment, visitors can create accounts on a new build (but admin approval is required to activate the account). The settings can be found here: /admin/config/people/accounts under "Registration and cancellation"

## Proposed resolution
By default, have new builds have the "Who can register accounts?" set to "Administrators only".

**Comment by joeparsons** [comment]
https://github.com/az-digital/az_quickstart/blob/main/config/install/user.settings.yml#L12
