### ISSUE TITLE
Icons not displaying correctly on accordions in Editor mode

### ISSUE THREAD

**Issue by sanjanans** [az-digital/az_quickstart#937]
## Problem/Motivation
Icons not displaying correctly on accordions in Editor mode

### To Reproduce
An example of the page showing the bug in editor mode : http://live-azs-quickstart.pantheonsite.io/page-elements/accordions

##  Screenshots
<img width="899" alt="Screen Shot 2021-07-16 at 12 19 29 PM" src="https://user-images.githubusercontent.com/71897492/125999153-52901c3f-19ab-4310-8407-ffa7256b5531.png">

**Comment by joeparsons** [comment]
@sanjanans Which browser(s) did you see this in?

**Comment by sanjanans** [comment]
@joeparsons on chrome and firefox browsers.

**Comment by smayden** [comment]
Happening for me in Chrome. I do not see this on the sites where RC1 not applied yet (such as https://live-azs-demo.pantheonsite.io/node/6/edit).
