### ISSUE TITLE
No margin between nodes in az-row view mode when on flexible pages or if a listing of flexible pages.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#941]
### Describe the bug
https://github.com/az-digital/az_quickstart/blob/main/themes/custom/az_barrio/css/style.css#L205-L207 is supposed to cover all non-flexible pages, but there are times when we embed nodes in flexible pages, or list flexible pages in alternate view modes from full page.

### To Reproduce
https://live-azs-demo.pantheonsite.io/events/annual-events
http://live-azs-quickstart.pantheonsite.io/live-training
https://live-azs-demo.pantheonsite.io/page-list

## Proposed resolution
I'd suggest either scoping margin to the view mode

```
.node--view-mode-az-row .node__content {
  margin-bottom: 1rem;
}
```

Or, editing each view mode that needs it, to add an `mb-2` class on node.

**Comment by mmunro-ltrr** [comment]
I'm wondering if something even more specific on the `margin-top` override would be best. The only reason we're messing with this at all is because of Issue #852, which is just in one very specific context.

**Comment by trackleft** [comment]
ha https://twitter.com/chriscoyier/status/804354359882579968?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E804354359882579968%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fcss-tricks.com%2Fmargin-bottom-margin-top%2F

**Comment by trackleft** [comment]
@mmunro-ltrr you're probably right, we should just make the other one more specific

**Comment by mmunro-ltrr** [comment]
Experimenting with an _extremely_ specific rule for where the margin-top override should apply (just pushed a branch that seems to work locally).
