### ISSUE TITLE
Quickstart should include Google Analytics

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#943]
## Motivation
Google Analytics is the standard way that we track web analytics.

### Is your feature request related to a problem? Please describe.
We need to have a solution for analytics available at launch.

### Describe the solution you'd like

- Google Tag Manager enabled by default with the same Container ID (GTM-ML2BZB) as QS1 included. 
- Google Analytics included, but disabled by default (to allow for departments to add their own property id)

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Anonymous user
- Authenticated user
- Content editor
- Content administrator
- Administrator

**Comment by joeparsons** [comment]
We included both the Google Analytics and Google Tag Manager modules in D7 but Google Tag Manager was the thing that was enabled by default and that we provided default configuration for.  Do we need to prioritize getting that added before Google Analytics?

**Comment by trackleft** [comment]
I have a question about this in my MBM standup channel, asking if we need Google Tag Manager, Universal Analytics, or Global Site Tag or all of them

**Comment by trackleft** [comment]
Additionally, I asked what @Krystation, and @RyanDool use for their enrollment management projects, and they said, just GTM.

**Comment by camikazegreen** [comment]
I updated the Issue with more refined requirements after meeting with Sanjana, Shoshana and Catherine.

Still need to determine version numbers.

**Comment by smayden** [comment]
Related ticket from UA Quickstart for GTM: https://jira.arizona.edu/browse/UADIGITAL-144
