### ISSUE TITLE
Blank fields on Person content should not be rendered.

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#956]
**Do not disclose security vulnerabilities here, please email us instead: 
az-digital-security@list.arizona.edu**

## Problem/Motivation
On the new IT Site, we left off phone, email and addresses for our people, but those sections are still being displayed which causes display issues.

### Describe the bug
All of this extra markup is still being added to the display of the person even when empty.
<img width="438" alt="Screen Shot 2021-07-22 at 3 56 00 PM" src="https://user-images.githubusercontent.com/1509771/126719137-3b224c73-86cf-4004-940f-d53ea492466c.png">

### To Reproduce

1. Add a person
2. Leave phone, email and address fields blank
3. View person
4. See error (This is especially noticeable with Person nodes embedded on a colored background, but even against white there is a border)

## Proposed resolution
Empty fields should not be rendered.

##  Screenshots
Issue on the IT Site:
<img width="1199" alt="Screen Shot 2021-07-22 at 3 58 48 PM" src="https://user-images.githubusercontent.com/1509771/126719334-054e086f-2710-45d3-8e51-135ecf49452a.png">

**Comment by joeparsons** [comment]
Enabling theme debugging would be helpful for this ticket:
https://github.com/az-digital/az_quickstart/blob/main/CONTRIBUTING.md#theme-debugging-and-the-development-site-mode
