### ISSUE TITLE
Provide design options for landing grid

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#982]
This will likely need to be done hand-in-hand with the gathering of requirements.

## Conditions of satisfaction
- [x] Should use Arizona Bootstrap
- [x] Should meet all accessibility requirements
- [x] Should include mockups of all states available in requirements
  - [ ] Version with sidebar on the page
  - [ ] Mobile display
  - [x] Links in body
  - [x] Different colors applied to border
  - [x] Hover states

**Comment by akslay** [comment]
![Screen Shot 2021-09-01 at 1 27 24 PM](https://user-images.githubusercontent.com/52931751/131740245-5f1bb757-0d8a-42aa-b21f-7fa13e93e1cc.png)
Selected design

**Comment by akslay** [comment]
**Follow-up tasks:**

- [ ] Make ticket for AZ Bootstrap to update Landing Grid styles
- [ ] Make ticket for AZ Bootstrap to add "clickable card" styles for all card options. This should include adding validation when using "clickable card" option (no body links allowed). Link field should also be required when clickable.
- [ ] Make ticket for AZ Quickstart to add "clickable card" checkbox to cards
- [ ] Make ticket for AZ Quickstart to add Landing Grid style as an option for cards
- [ ] Start work on https://github.com/az-digital/az_quickstart/issues/749 (add button class options for card links)
