### ISSUE TITLE
PHP 8.0 compatibility needed for Quickstart

### ISSUE THREAD

**Issue by mmunro-ltrr** [az-digital/az_quickstart#983]
## Motivation
Drupal 9 recommends PHP v8.0 (as well as v7.4), but Quickstart's dependencies are not compatible with v8.

### Is your feature request related to a problem? Please describe.
A Quickstart installation fails almost immediately on a LAMP stack using PHP v8.0.8.

## Proposed Resolution
Investigate workarounds and version bumps for Quickstart in PHP 8 test environments.

**Comment by mmunro-ltrr** [comment]
Looks like it might just need a version bump of liuggio/fastest to v1.8.0. That would be a PR on the az-quickstart-dev repository, and should follow PR 20 there (@joeparsons replacing raveren/kint with kint-php/kint). A local Lando build worked.

![quickstart_with_php_8](https://user-images.githubusercontent.com/5680584/129985052-1df36a44-9024-46a6-ab90-eea3f6daed7a.png)

**Comment by michaelhagedon** [comment]
Looks like liuggio-fastest is updated in -dev, so now with lando updated to PHP 8, the site installs and tests pass via `lando phpunit-fastest`.

**Comment by joeparsons** [comment]
I think the immediate issue(s) that were causing these failures have been resolved.
