### ISSUE TITLE
Address field differences between QS1 & QS2 cause migration issues

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#986]
## Problem/Motivation
Z in SBS noticed while trying to migrate some person content from a QS1 site that there is a difference between the allowed text formats for the address field in Quickstart 1 and Quickstart 2.

### Describe the bug
The `field_uaqs_addresses` field on the UAQS Person content type in Quicsktart 1 is a text format field that allows any text format to be used (`uaqs_standard` is the default).

The `field_az_address` field on the AZ Person content type in Quickstart 2 is also a text format field but _only_ allows plain text.

This causes a problem when importing person content from a Quickstart 1 site using our `az_migration` module because rich text is rendered as plain text.

## Proposed resolution
We either need to change the address field in QS2 to be not be plain text or potentially add a custom process step/plugin to the person migration that strips out HTML tags from the source value.

**Comment by joeparsons** [comment]
@tadean pointed out that allowing anything other than plain text in the AZ Person address field could cause problems for this issue: #478.

**Comment by trackleft** [comment]
Consensus was to add process step/plugin to the person migration that strips out HTML tags from the source value.
